Repository kubermatic/kubeone, pull requests merged in 2019-07, with the labels that each got.

#523 On reset remove /var/lib/etcd on control plane nodes
  pkg/installer/installation/reset.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#528 Update the pull requests template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#529 Add more details about DCO to the contributing guide
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#532 Revert "node local dns cache"
  Gopkg.lock
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/features/activate.go
  pkg/features/dynamic_audit_log.go
  pkg/features/metrics-server.go
  pkg/features/node_local_dns_cache.go
  pkg/features/oidc.go
  pkg/features/psp.go
  pkg/installer/installation/reset.go
  pkg/templates/dnscache/deployment.go
  pkg/templates/dnscache/helper.go
  pkg/templates/kubeadm/kubeadmargs/args.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/webhook.go
  pkg/templates/metricsserver/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#504 Prepare for the release v0.9.0
  CHANGELOG.md
  README.md
  docs/release_process.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#536 Use systemd cgroup manager for Docker on Ubuntu
  pkg/installer/installation/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#538 Add information about the AUR package to README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#540 Fix weave-net CNI plugin to respect podSubnet
  pkg/templates/weave/weave-net.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#541 Use systemd cgroups driver on CoreOS and enable kubelet by default
  pkg/installer/installation/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#546 Update CHANGELOG for v0.9.1
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#549 Update machine-controller to v1.4.0 and add new OpenStackSpec fields
  examples/terraform/openstack/output.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/templates/machinecontroller/deployment.go
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#554 Prefix v in the URL for CNI plugins.
  pkg/installer/installation/prerequisites.go
  pkg/upgrader/upgrade/kubernetes_binaries.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#556 Fix kubelet upgrade on Container Linux
  pkg/upgrader/upgrade/kubernetes_binaries.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#558 Add changelog for v0.9.2
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#563 Add AUR badge
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#551 Update machine-controller to v1.4.1 and add credentials validation
  docs/environment_variables.md
  examples/terraform/openstack/output.tf
  pkg/credentials/credentials.go
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#565 Some dependency packages upgrades
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#566 Use sdandard GOFLAGS=-mod=readonly flag in Makefile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#564 Taint control plane nodes by default
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#568 Fix Terraform integration not taking multiple workersets
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#569 Add my humble self to the OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#567 Bastion support
  examples/terraform/aws-private/README.md
  examples/terraform/aws-private/main.tf
  examples/terraform/aws-private/output.tf
  examples/terraform/aws-private/variables.tf
  examples/terraform/aws/output.tf
  examples/terraform/azure/output.tf
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/defaults.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/cmd/config.go
  pkg/installer/installation/prerequisites.go
  pkg/ssh/connection.go
  pkg/ssh/connector.go
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#572 Update machine-controller to v1.4.2 and add additional OpenStack field
  examples/terraform/openstack/output.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/templates/machinecontroller/deployment.go
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#574 Fix install subcommand not running without terraform output
  pkg/apis/kubeone/config/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#576 Ansible
  README.md
  examples/ansible/kubeone-install.yml
  examples/ansible/kubeone-upgrade.yml
  examples/ansible/roles/kubeone-install/defaults/main.yml
  examples/ansible/roles/kubeone-install/tasks/main.yml
  examples/ansible/roles/kubeone-install/templates/config.yaml.j2
  examples/ansible/roles/kubeone-upgrade/defaults/main.yml
  examples/ansible/roles/kubeone-upgrade/tasks/main.yml
  examples/ansible/roles/kubeone-upgrade/templates/config.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#582 Add changelog for v0.10.0-alpha.0
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#584 Prevent printing out usage if cmd line is correct but something else fails
  pkg/cmd/root.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#587 Update GoReleaser settings
  .goreleaser.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#585 Improve ansible
  examples/ansible/install.yml
  examples/ansible/kubeone/.gitignore
  examples/ansible/kubeone/galaxy.yml
  examples/ansible/kubeone/roles/kubeone_config/defaults/main.yml
  examples/ansible/kubeone/roles/kubeone_config/tasks/main.yml
  examples/ansible/kubeone/roles/kubeone_config/templates/config.yaml.j2
  examples/ansible/kubeone/roles/kubeone_install/tasks/main.yml
  examples/ansible/kubeone/roles/kubeone_reset/tasks/main.yml
  examples/ansible/kubeone/roles/kubeone_upgrade/tasks/main.yml
  examples/ansible/reset.yml
  examples/ansible/roles
  examples/ansible/roles/kubeone-install/defaults/main.yml
  examples/ansible/roles/kubeone-upgrade/defaults/main.yml
  examples/ansible/roles/kubeone-upgrade/templates/config.yaml.j2
  examples/ansible/upgrade.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#588 Update release date for the v0.10.0-alpha.0 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#597 Cleanup Makefile
  Makefile
  hack/run-ci-e2e-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#591 Upgrade DO CCM to v0.1.16
  pkg/templates/externalccm/digitalocean.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#600 Update the release process documentation
  docs/release_process.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#598 Better flannel configuration
  go.mod
  pkg/certificate/ca.go
  pkg/clientutil/create_or_update.go
  pkg/credentials/secret.go
  pkg/features/activate.go
  pkg/features/psp.go
  pkg/installer/installation/cni.go
  pkg/installer/installation/coredns.go
  pkg/installer/installation/install.go
  pkg/installer/installation/kubeconfig.go
  pkg/state/context.go
  pkg/templates/canal/canal.go
  pkg/templates/canal/daemonset.go
  pkg/templates/canal/helper.go
  pkg/templates/canal/prerequisites.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/externalccm/packet.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/helper.go
  pkg/templates/machinecontroller/machines.go
  pkg/templates/machinecontroller/webhook.go
  pkg/templates/metricsserver/deployment.go
  pkg/templates/metricsserver/helper.go
  pkg/templates/weave/helper.go
  pkg/templates/weave/weave-net.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#603 Propagate signals in E2E tests script
  hack/run-ci-e2e-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#605 Unconditionally add GOPATH/bin to PATH
  hack/run-ci-e2e-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#604 Add workers-pool name to tags for GCP loadbalancer creation
  examples/terraform/gce/output.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#606 Take static networking into account when contructing machineDeployment
  pkg/templates/machinecontroller/machines.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#602 Upgrade machinecontroller to v1.5.1
  examples/terraform/aws-private/main.tf
  examples/terraform/aws-private/output.tf
  examples/terraform/aws-private/variables.tf
  go.mod
  go.sum
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/templates/machinecontroller/deployment.go
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
