Repository kubermatic/kubeone, pull requests merged in 2019-04, with the labels that each got.

#325 update hetzner terraform config
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#323 Update docs to use v1.14.0
  config.yaml.dist
  docs/quickstart-aws.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#324 Add v0.5.0 to the README.md file
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#328 Implement Retryable tasks
  pkg/installer/installation/install.go
  pkg/task/task.go
  pkg/upgrader/upgrade/upgrade.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#330 Increase E2E tests timeouts
  hack/run_ci_e2e_test.sh
  test/e2e/main_test.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#331 Add the Terraform workerset integration for Hetzner
  examples/terraform/hetzner/output.tf
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#332 Implement E2E tests for Hetzner
  test/e2e/conformance_test.go
  test/e2e/helper.go
  test/e2e/provisioner.go
  test/e2e/testdata/config_hetzner_1.13.5.yaml
  test/e2e/testdata/config_hetzner_1.14.0.yaml
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#333 Add GoDoc and GoReportCard badges to the readme
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#334 Enable scaling machinedeployments subresource
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#336 Set Hetzner token when running E2E tests
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  hack/run_ci_e2e_test.sh
  test/e2e/kubeone.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#335 Fix the lint and misspell errors caught by the GoReportCard
  pkg/task/task.go
  pkg/templates/canal/daemonset.go
  test/e2e/kubeone.go
  test/e2e/kubetest.go
  test/e2e/provisioner.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#339 Fix vsphere name
  config.yaml.dist
  pkg/config/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#341 Update the upgrades proposal status
  docs/README.md
  docs/proposals/20190211-upgrades.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#340 Update e2e tests to use Kubernetes v1.14.1
  hack/run_ci_e2e_test.sh
  test/e2e/conformance_test.go
  test/e2e/testdata/config_aws_1.14.1.yaml
  test/e2e/testdata/config_do_1.14.1.yaml
  test/e2e/testdata/config_hetzner_1.14.1.yaml
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#342 BREAKING: Change features flags from boolean to structures
  config.yaml.dist
  pkg/config/cluster.go
  pkg/features/activate.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#338 metrics server
  Gopkg.lock
  Gopkg.toml
  config.yaml.dist
  examples/terraform/digitalocean/output.tf
  pkg/cmd/root.go
  pkg/config/cluster.go
  pkg/features/activate.go
  pkg/features/metrics-server.go
  pkg/templates/metricsserver/deployment.go
  pkg/templates/metricsserver/helper.go
  pkg/upgrader/upgrade/upgrade_machine_deployments.go
  vendor/k8s.io/kube-aggregator/LICENSE
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/helpers.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/doc.go
  vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/scheme/register.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#344 OIDC Support
  config.yaml.dist
  pkg/config/cluster.go
  pkg/features/activate.go
  pkg/features/dynamic_audit_log.go
  pkg/features/oidc.go
  pkg/features/psp.go
  test/e2e/kubetest.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#345 Ensure documentation is up-to-date
  README.md
  docs/README.md
  docs/frequently_asked_questions.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#346 Add KubeOne logo
  README.md
  docs/img/kubeone-logo-text.png
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#348 Fix the 'on-prem' typo in README and Frequently Asked Questions
  README.md
  docs/frequently_asked_questions.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#351 rename metrics_server.disable to metrics_server.enable
  config.yaml.dist
  pkg/config/cluster.go
  pkg/features/activate.go
  pkg/features/dynamic_audit_log.go
  pkg/features/metrics-server.go
  pkg/features/psp.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#350 ssh_username terraform variable
  examples/terraform/aws/README.md
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/output.tf
  examples/terraform/digitalocean/variables.tf
  examples/terraform/gce/README.md
  examples/terraform/hetzner/README.md
  examples/terraform/openstack/README.md
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#354 Add GCE support to features
  README.md
  docs/project_structure.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#355 aws private network example
  examples/terraform/aws-private/README.md
  examples/terraform/aws-private/main.tf
  examples/terraform/aws-private/output.tf
  examples/terraform/aws-private/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#357 docs: Clarification about cluster_name
  docs/quickstart-aws.md
  docs/quickstart-digitalocean.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#358 Update the KubeOneCluster API proposal
  docs/README.md
  docs/proposals/20190409-kubeonecluster-api.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#359 Fix minor lint error in the API
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#360 Add the KubeOneCluster API scheme
  Gopkg.lock
  pkg/apis/kubeone/scheme/scheme.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#361 -external-cloud-provider machine-controller flag
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#362 patch coreDNS deployment for external cloud provider
  pkg/installer/installation/coredns.go
  pkg/installer/installation/install.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#364 Deploy external CCMs
  .golangci.yml
  pkg/config/cluster.go
  pkg/installer/installation/install.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/machinecontroller/helper.go
  pkg/upgrader/upgrade/upgrade.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#370 Parse all supported digitalocean params
  examples/terraform/digitalocean/output.tf
  pkg/terraform/config.go
  test/e2e/testdata/config_aws_1.13.5.yaml
  test/e2e/testdata/config_aws_1.14.1.yaml
  test/e2e/testdata/config_do_1.13.5.yaml
  test/e2e/testdata/config_do_1.14.1.yaml
  test/e2e/testdata/config_hetzner_1.13.5.yaml
  test/e2e/testdata/config_hetzner_1.14.1.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#373 Add the initial changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#375 Update machine-controller to v1.1.4 and Cluster-API to c63bf6f
  Gopkg.lock
  Gopkg.toml
  pkg/templates/machinecontroller/deployment.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/common/consts.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#378 Update machine-controller to v1.1.5
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#379 Improve the new KubeOneCluster API and add missing fields
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/credentials.go
  pkg/apis/kubeone/v1alpha1/defaults.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#392 Don't wait for machine-controller if it's not deployed
  pkg/templates/machinecontroller/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#393 Add the backwards compatibility policy. Promote KubeOne to beta
  README.md
  docs/README.md
  docs/backwards_compatibility_policy.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
