Repository kubermatic/kubeone, pull requests merged in 2019-05, with the labels that each got.

#390 Migrate to the KubeOneCluster API
  CONTRIBUTING.md
  config.yaml.dist
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/defaults.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/certificate/ca.go
  pkg/cmd/install.go
  pkg/cmd/kubeconfig.go
  pkg/cmd/reset.go
  pkg/cmd/shared.go
  pkg/cmd/upgrade.go
  pkg/features/activate.go
  pkg/features/dynamic_audit_log.go
  pkg/features/metrics-server.go
  pkg/features/oidc.go
  pkg/features/psp.go
  pkg/installer/installation/certs.go
  pkg/installer/installation/controlplane.go
  pkg/installer/installation/coredns.go
  pkg/installer/installation/kubeadm_config.go
  pkg/installer/installation/kubeadm_leader.go
  pkg/installer/installation/kubeconfig.go
  pkg/installer/installation/prerequisites.go
  pkg/installer/installation/reset.go
  pkg/installer/installer.go
  pkg/ssh/connector.go
  pkg/templates/canal/canal.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/kubeadm/kubeadm.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/helper.go
  pkg/templates/machinecontroller/machines.go
  pkg/templates/machinecontroller/webhook.go
  pkg/terraform/config.go
  pkg/upgrader/upgrade/kubeadm_config.go
  pkg/upgrader/upgrade/kubernetes_binaries.go
  pkg/upgrader/upgrade/preflight_checks.go
  pkg/upgrader/upgrade/upgrade_follower.go
  pkg/upgrader/upgrade/upgrade_leader.go
  pkg/upgrader/upgrade/util.go
  pkg/upgrader/upgrader.go
  pkg/util/config/cluster.go
  pkg/util/context.go
  pkg/util/credentials/credentials.go
  pkg/util/kubeconfig.go
  pkg/util/task.go
  test/e2e/testdata/config_aws_1.13.5.yaml
  test/e2e/testdata/config_aws_1.14.1.yaml
  test/e2e/testdata/config_do_1.13.5.yaml
  test/e2e/testdata/config_do_1.14.1.yaml
  test/e2e/testdata/config_hetzner_1.13.5.yaml
  test/e2e/testdata/config_hetzner_1.14.1.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#394 Decouple credentials secret creation from machine-controller
  pkg/installer/installation/install.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/machinecontroller/deployment.go
  pkg/upgrader/upgrade/upgrade.go
  pkg/util/credentials/secret.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#395 Update KubeOne documentation
  docs/adding_provider_support.md
  docs/project_structure.md
  docs/quickstart-aws.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#396 Fix ClusterNetwork defaulting
  pkg/apis/kubeone/v1alpha1/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#399 Packet docs
  README.md
  docs/README.md
  docs/environment_variables.md
  docs/frequently_asked_questions.md
  docs/quickstart-packet.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#400 Add KubeOne demo asciicast to README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#401 Openstack
  examples/terraform/openstack/README.md
  examples/terraform/openstack/datasources.tf
  examples/terraform/openstack/etc_gobetween.tpl
  examples/terraform/openstack/gobetween.sh
  examples/terraform/openstack/main.tf
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
  pkg/apis/kubeone/validation/validation.go
  pkg/util/credentials/credentials.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#405 Update README files in examples/terraform
  examples/terraform/aws-private/README.md
  examples/terraform/aws/README.md
  examples/terraform/digitalocean/README.md
  examples/terraform/gce/README.md
  examples/terraform/hetzner/README.md
  examples/terraform/openstack/README.md
  examples/terraform/packet/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#408 Implement 'config migrate' command
  Gopkg.lock
  pkg/cmd/config.go
  pkg/cmd/root.go
  pkg/config/migrate.go
  pkg/config/migrate_test.go
  pkg/config/testdata/config-apiserver.yaml
  pkg/config/testdata/config-apiserver.yaml.golden
  pkg/config/testdata/config-aws.yaml
  pkg/config/testdata/config-aws.yaml.golden
  pkg/config/testdata/config-do-external.yaml
  pkg/config/testdata/config-do-external.yaml.golden
  pkg/config/testdata/config-features-0.5.0.yaml
  pkg/config/testdata/config-features-0.5.0.yaml.golden
  pkg/config/testdata/config-features.yaml
  pkg/config/testdata/config-features.yaml.golden
  pkg/config/testdata/config-hosts.yaml
  pkg/config/testdata/config-hosts.yaml.golden
  pkg/config/testdata/config-machine-controller.yaml
  pkg/config/testdata/config-machine-controller.yaml.golden
  pkg/config/testdata/config-network.yaml
  pkg/config/testdata/config-network.yaml.golden
  pkg/config/testdata/config-os-cloudconfig.yaml
  pkg/config/testdata/config-os-cloudconfig.yaml.golden
  pkg/config/testdata/config-proxy.yaml
  pkg/config/testdata/config-proxy.yaml.golden
  pkg/config/testdata/config-workers.yaml
  pkg/config/testdata/config-workers.yaml.golden
  pkg/util/yamled/doc.go
  pkg/util/yamled/document.go
  pkg/util/yamled/document_test.go
  pkg/util/yamled/path.go
  pkg/util/yamled/path_test.go
  pkg/util/yamled/testcases/append-existing-array.yaml
  pkg/util/yamled/testcases/append-new-array.yaml
  pkg/util/yamled/testcases/document.yaml
  pkg/util/yamled/testcases/fill-complex.yaml
  pkg/util/yamled/testcases/fill-existing-root-key.yaml
  pkg/util/yamled/testcases/fill-into-array.yaml
  pkg/util/yamled/testcases/fill-new-root-key.yaml
  pkg/util/yamled/testcases/fill-two-new-root-keys.yaml
  pkg/util/yamled/testcases/remove-existing-array-item.yaml
  pkg/util/yamled/testcases/remove-existing-root-key.yaml
  pkg/util/yamled/testcases/remove-existing-sub-key.yaml
  pkg/util/yamled/testcases/remove-nonexisting-array-item.yaml
  pkg/util/yamled/testcases/remove-nonexisting-root-key.yaml
  pkg/util/yamled/testcases/set-existing-array-item.yaml
  pkg/util/yamled/testcases/set-existing-root-key.yaml
  pkg/util/yamled/testcases/set-new-array-item.yaml
  pkg/util/yamled/testcases/set-new-deep-sub-key.yaml
  pkg/util/yamled/testcases/set-new-far-array-item.yaml
  pkg/util/yamled/testcases/set-new-root-key.yaml
  pkg/util/yamled/testcases/set-new-sub-key.yaml
  pkg/util/yamled/util.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#410 Document how to migrate to the new API and changes made in the API
  docs/README.md
  docs/api_migration.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#411 Add note about load balancers on Packet and OpenStack and update the Hetzner quickstart
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#412 Implement the 'config print' command
  pkg/cmd/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#415 Extend 'config print' command with additional options
  pkg/cmd/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#414 Automatic LB provision for Hetzner
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/etc_gobetween.tpl
  examples/terraform/hetzner/gobetween.sh
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#422 Update README to the release v0.6.0
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#424 Fix metrics-server for all providers
  pkg/templates/metricsserver/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#426 Prepare for the release v0.6.1
  CHANGELOG.md
  README.md
  docs/quickstart-aws.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#430 [Cherry-pick] Prepare for the release v0.6.1 (#426)
  CHANGELOG.md
  README.md
  docs/quickstart-aws.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#439 Fix JSON tag for Name field
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#443 CentOS fixes
  pkg/certificate/ca.go
  pkg/installer/installation/kubeconfig.go
  pkg/installer/installation/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#440 Update documentation for the release v0.6.2
  CHANGELOG.md
  README.md
  docs/quickstart-aws.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#448 Fix hetzner typo
  docs/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#433 Add deprecation note to the old API
  pkg/config/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#432 Add weave-net as an alternative CNI plugin
  Gopkg.lock
  Makefile
  README.md
  config.yaml.dist
  docs/quickstart-aws.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/defaults.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/installer/installation/cni.go
  pkg/installer/installation/install.go
  pkg/task/task.go
  pkg/templates/canal/canal.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/weave/helper.go
  pkg/templates/weave/weave-net.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#431 Improve aws terraform configurations
  examples/terraform/aws-private/main.tf
  examples/terraform/aws-private/output.tf
  examples/terraform/aws-private/variables.tf
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#452 Upgrade weave-net
  pkg/templates/weave/weave-net.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#450 Delete worker nodes using dynamic client and add an option to remove Kubernetes packages when resetting the cluster
  Makefile
  pkg/cmd/reset.go
  pkg/installer/installation/reset.go
  pkg/installer/installer.go
  pkg/templates/machinecontroller/helper.go
  pkg/upgrader/upgrade/upgrade_machine_deployments.go
  pkg/util/context.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#453 Unify terraform configs
  examples/terraform/aws-private/README.md
  examples/terraform/aws-private/output.tf
  examples/terraform/aws-private/variables.tf
  examples/terraform/aws/README.md
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/main.tf
  examples/terraform/digitalocean/output.tf
  examples/terraform/digitalocean/variables.tf
  examples/terraform/gce/README.md
  examples/terraform/gce/main.tf
  examples/terraform/gce/output.tf
  examples/terraform/gce/variables.tf
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  examples/terraform/openstack/README.md
  examples/terraform/openstack/main.tf
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
  examples/terraform/packet/README.md
  examples/terraform/packet/main.tf
  examples/terraform/packet/output.tf
  examples/terraform/packet/variables.tf
  test/e2e/conformance_test.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#454 Additional machinecontroller fields in terraform config
  examples/terraform/aws-private/output.tf
  examples/terraform/aws/output.tf
  examples/terraform/gce/output.tf
  examples/terraform/openstack/output.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/machines.go
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#464 Update docs for new CloudProviderSpec sturctures location
  docs/adding_provider_support.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#465 Prepare for the release v0.7.0
  CHANGELOG.md
  README.md
  docs/quickstart-aws.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#467 Fix GoReleaser deprecation warning
  .goreleaser.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#428 vsphere support
  docs/quickstart-vsphere.md
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/etc_gobetween.tpl
  examples/terraform/vsphere/gobetween.sh
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/terraform/config.go
  pkg/util/credentials/credentials.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#468 Update docs for v0.8.0
  CHANGELOG.md
  README.md
  docs/environment_variables.md
  docs/frequently_asked_questions.md
  docs/quickstart-aws.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
  docs/quickstart-vsphere.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
