Repository kubermatic/kubeone, pull requests merged in 2019-09, with the labels that each got.

#642 Add support for custom OS in E2E tests for AWS
  test/e2e/conformance_test.go
  test/e2e/main_test.go
  test/e2e/os.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#607 Set hostname for GCE instances in Terraform scripts
  examples/terraform/gce/output.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#647 Fix GCE E2E cluster provisioning
  hack/run-ci-e2e-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#650 Fix proxy-env for pre-requisite scripts
  pkg/installer/installation/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#651 Make login user of bastion host configurable
  examples/ansible/kubeone/roles/kubeone_config/defaults/main.yml
  examples/terraform/aws-private/README.md
  examples/terraform/aws-private/output.tf
  examples/terraform/aws-private/variables.tf
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/defaults.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/cmd/config.go
  pkg/ssh/connection.go
  pkg/ssh/connector.go
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#657 Pass proxy environment to machine-controller.
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#660 Avoid curl via sudo, proper binary install.
  pkg/installer/installation/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#664 Add operating system environment variables to E2E tests script
  hack/run-ci-e2e-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#665 Make E2E tests pick right username
  .golangci.yml
  test/e2e/conformance_test.go
  test/e2e/os.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#667 Update default admission controllers for 1.16
  pkg/kubeflags/data.go
  pkg/kubeflags/flags.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#663 Idempotent install
  pkg/installer/installation/controlplane.go
  pkg/installer/installation/install.go
  pkg/installer/installation/kubeadm_leader.go
  pkg/installer/installation/prerequisites.go
  pkg/installer/installation/reset.go
  pkg/installer/installer.go
  pkg/state/context.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/upgrader/upgrader.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#668 Reference new KubeOne channel on k8s Slack
  .github/ISSUE_TEMPLATE/support-request.md
  CONTRIBUTING.md
  README.md
  docs/adding_provider_support.md
  docs/frequently_asked_questions.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#670 New top-level API SystemPackages
  .golangci.yml
  go.mod
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/defaults.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/installer/installation/prerequisites.go
  pkg/templates/kubeadm/kubeadm.go
  pkg/templates/kubeadm/kubeadmv1beta2.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#675 Update machine-controller to v1.5.6
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#677 Apply MachineDeployment labels on the Node object
  pkg/templates/machinecontroller/machines.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#679 Only show Retrying task message if there are retries left
  pkg/task/task.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#678 Support adding Taints on the worker nodes
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/templates/machinecontroller/machines.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#683 Verify machine-controller CRDs before deleting workers
  .golangci.yml
  pkg/installer/installation/reset.go
  pkg/templates/machinecontroller/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#686 Add missing fields to workers Terraform integration
  pkg/templates/machinecontroller/cloudprovider_specs.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#685 Implement OpenStack E2E tests
  hack/run-ci-e2e-test.sh
  test/e2e/conformance_test.go
  test/e2e/kubeone.go
  test/e2e/provisioner/provisioner.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#687 Add proxy env to /etc/environment
  pkg/installer/installation/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#688 Fix /etc/environment creation.
  pkg/installer/installation/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#689 Add ShortNames and AdditionalPrinterColumns for Cluster-API CRDs
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#684 Add changelog for v0.10.0 and update docs in preparation for v0.10.0 release
  CHANGELOG.md
  README.md
  docs/quickstart-aws.md
  docs/quickstart-azure.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
  docs/quickstart-vsphere.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#690 Postpone the v0.10.0 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
