Repository kubermatic/kubeone, pull requests merged in 2019-06, with the labels that each got.

#477 Fix outdated config in docs
  docs/quickstart-openstack.md
  docs/quickstart-vsphere.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#469 Azure support
  README.md
  docs/environment_variables.md
  docs/frequently_asked_questions.md
  docs/quickstart-azure.md
  examples/terraform/azure/README.md
  examples/terraform/azure/main.tf
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/validation/validation.go
  pkg/installer/installation/prerequisites.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/templates/machinecontroller/deployment.go
  pkg/terraform/config.go
  pkg/util/credentials/credentials.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#479 Repair ability to read terraform output from stdin
  pkg/util/config/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#484 Add sub command for completion and documentation generation
  Gopkg.lock
  Gopkg.toml
  README.md
  pkg/cmd/packaging.go
  pkg/cmd/root.go
  vendor/github.com/cpuguy83/go-md2man/LICENSE.md
  vendor/github.com/cpuguy83/go-md2man/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/md2man/roff.go
  vendor/github.com/russross/blackfriday/LICENSE.txt
  vendor/github.com/russross/blackfriday/block.go
  vendor/github.com/russross/blackfriday/doc.go
  vendor/github.com/russross/blackfriday/esc.go
  vendor/github.com/russross/blackfriday/html.go
  vendor/github.com/russross/blackfriday/inline.go
  vendor/github.com/russross/blackfriday/markdown.go
  vendor/github.com/russross/blackfriday/node.go
  vendor/github.com/russross/blackfriday/smartypants.go
  vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
  vendor/github.com/shurcooL/sanitized_anchor_name/main.go
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/util.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#483 Initial refactor of E2E tests
  hack/run_ci_e2e_test.sh
  test/e2e/conformance_test.go
  test/e2e/kubeone.go
  test/e2e/kubetest.go
  test/e2e/main_test.go
  test/e2e/provisioner.go
  test/e2e/provisioner/default.go
  test/e2e/provisioner/provisioner.go
  test/e2e/provisioner/terraform.go
  test/e2e/testdata/config_aws_1.13.5.yaml
  test/e2e/testdata/config_aws_1.14.1.yaml
  test/e2e/testdata/config_do_1.13.5.yaml
  test/e2e/testdata/config_do_1.14.1.yaml
  test/e2e/testdata/config_hetzner_1.13.5.yaml
  test/e2e/testdata/config_hetzner_1.14.1.yaml
  test/e2e/testutil/testutil.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#482 Fix Azure documentation
  docs/quickstart-azure.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#488 e2e: retry terraform apply on failure
  test/e2e/provisioner/terraform.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#490 Upgrade machinecontroller to v1.2.0
  Gopkg.lock
  Gopkg.toml
  pkg/cmd/config.go
  pkg/templates/machinecontroller/deployment.go
  vendor/sigs.k8s.io/cluster-api/logos/LICENSE.md
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/cluster_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machine_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineclass_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machinedeployment_types.go
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/machineset_types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#491 Force gobetween.sh to exit on error
  examples/terraform/hetzner/gobetween.sh
  examples/terraform/openstack/gobetween.sh
  examples/terraform/packet/gobetween.sh
  examples/terraform/vsphere/gobetween.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#493 Document the KubeOne release process
  docs/release_process.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#494 Make gobetween.sh universal across different OS
  examples/terraform/hetzner/gobetween.sh
  examples/terraform/openstack/gobetween.sh
  examples/terraform/packet/gobetween.sh
  examples/terraform/vsphere/gobetween.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#496 Update machinecontroller to 1.2.1 and use proxy for kubelets
  pkg/installer/installation/prerequisites.go
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#498 Small fixes in gobetween.sh
  examples/terraform/hetzner/gobetween.sh
  examples/terraform/openstack/gobetween.sh
  examples/terraform/packet/gobetween.sh
  examples/terraform/vsphere/gobetween.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#495 Allow to automatically read terraform state from directory
  pkg/cmd/install.go
  pkg/cmd/kubeconfig.go
  pkg/cmd/reset.go
  pkg/cmd/root.go
  pkg/cmd/shared.go
  pkg/cmd/upgrade.go
  pkg/util/config/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#466 Convert terraform example files to be v0.12 compatible
  README.md
  docs/quickstart-aws.md
  docs/quickstart-azure.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
  docs/quickstart-vsphere.md
  examples/terraform/aws-private/main.tf
  examples/terraform/aws-private/output.tf
  examples/terraform/aws-private/variables.tf
  examples/terraform/aws-private/versions.tf
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  examples/terraform/aws/versions.tf
  examples/terraform/azure/main.tf
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  examples/terraform/azure/versions.tf
  examples/terraform/digitalocean/main.tf
  examples/terraform/digitalocean/output.tf
  examples/terraform/digitalocean/variables.tf
  examples/terraform/digitalocean/versions.tf
  examples/terraform/gce/main.tf
  examples/terraform/gce/output.tf
  examples/terraform/gce/variables.tf
  examples/terraform/gce/versions.tf
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  examples/terraform/hetzner/versions.tf
  examples/terraform/openstack/main.tf
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
  examples/terraform/openstack/versions.tf
  examples/terraform/packet/main.tf
  examples/terraform/packet/output.tf
  examples/terraform/packet/variables.tf
  examples/terraform/packet/versions.tf
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere/versions.tf
  hack/run_ci_e2e_test.sh
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#489 Add E2E tests for Packet and GCE. Drop 1.13 tests and use 1.14.3 instead of 1.14.1
  docs/quickstart-gce.md
  hack/run_ci_e2e_test.sh
  test/e2e/conformance_test.go
  test/e2e/provisioner/default.go
  test/e2e/provisioner/provisioner.go
  test/e2e/provisioner/terraform.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#500 Terraform 0.12 additions
  examples/terraform/aws-private/output.tf
  examples/terraform/aws/output.tf
  examples/terraform/azure/output.tf
  examples/terraform/digitalocean/output.tf
  examples/terraform/gce/output.tf
  examples/terraform/hetzner/etc_gobetween.tpl
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/openstack/etc_gobetween.tpl
  examples/terraform/openstack/main.tf
  examples/terraform/openstack/output.tf
  examples/terraform/packet/etc_gobetween.tpl
  examples/terraform/packet/main.tf
  examples/terraform/vsphere/etc_gobetween.tpl
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/outputs.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#503 [BREAKING]: terraform outputs directly unmarshaled to kubeone API strucures
  examples/terraform/aws-private/output.tf
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/azure/output.tf
  examples/terraform/digitalocean/output.tf
  examples/terraform/gce/output.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/openstack/output.tf
  examples/terraform/packet/main.tf
  examples/terraform/packet/output.tf
  examples/terraform/vsphere/outputs.tf
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#507 Fix load balancer reference in vSphere Terraform example
  examples/terraform/vsphere/main.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#506 Make E2E tests version-agnostic
  hack/run_ci_e2e_test.sh
  test/e2e/conformance_test.go
  test/e2e/main_test.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#509 Document gobetween loadbalancer
  docs/example-loadbalancer.md
  examples/terraform/hetzner/README.md
  examples/terraform/openstack/README.md
  examples/terraform/packet/README.md
  examples/terraform/vsphere/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#510 Document SSH requirements
  docs/ssh.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#508 Make reset a bit more robust
  pkg/installer/installation/reset.go
  pkg/templates/machinecontroller/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#511 Fix packet terraform
  examples/terraform/packet/main.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#512 Force docker start in ubuntu
  pkg/installer/installation/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#513 Fix openstack terraform rendered_lb_config issue
  examples/terraform/openstack/main.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#517 Security update for docker
  pkg/installer/installation/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#516 Upgrade digitalocean CCM to v0.1.15
  pkg/templates/externalccm/digitalocean.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#518 Add vsphere to the documented provider list of kubeone config print
  pkg/cmd/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#514 Add CII Best Practices badge to README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#519 Remove optional section from terraform vsphere quickstart guide
  docs/quickstart-vsphere.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#521 Fix Packet E2E failures
  hack/run_ci_e2e_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
