Repository kubermatic/kubeone, pull requests merged in 2019-11, with the labels that each got.

#725 configure-cloud-routes = false on AWS
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#732 Update GCE docs to configure clusters as regional
  docs/quickstart-gce.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#731 e2e image
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
  hack/run-ci-e2e-test.sh
  test/e2e/kubetest.go
  test/e2e/main_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#734 Implement components health checks and the status command
  .golangci.yml
  go.mod
  go.sum
  pkg/clusterstatus/apiserverstatus/apiserverstatus.go
  pkg/clusterstatus/clusterstatus.go
  pkg/clusterstatus/etcdstatus/etcdstatus.go
  pkg/clusterstatus/preflightstatus/preflightstatus.go
  pkg/cmd/root.go
  pkg/cmd/status.go
  pkg/httptunnel/httptunnel.go
  pkg/tabwriter/tabwriter.go
  pkg/upgrader/upgrade/preflight_checks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#729 Create AWS subnets in terraform
  examples/terraform/aws-private/README.md
  examples/terraform/aws-private/main.tf
  examples/terraform/aws-private/output.tf
  examples/terraform/aws-private/variables.tf
  examples/terraform/aws-private/versions.tf
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  examples/terraform/aws/versions.tf
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
  hack/run-ci-e2e-test.sh
  pkg/clusterstatus/preflightstatus/preflightstatus.go
  pkg/installer/installation/prerequisites.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  test/e2e/conformance_test.go
  test/e2e/kubeone.go
  test/e2e/kubetest.go
  test/e2e/main_test.go
  test/e2e/provisioner/default.go
  test/e2e/provisioner/terraform.go
  test/e2e/testutil/exec.go
  test/e2e/testutil/exec_test.go
  test/e2e/testutil/testutil.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#736 Bump machine controller version to v1.8.0
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#737 Fix vSphere credentials secret
  pkg/credentials/credentials.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#676 Add build options to the Makefile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#741 Add changelog for the v0.11.0-beta.0 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#744 GO111MODULE=on go get in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS
