Repository kubermatic/kubeone, pull requests merged in 2019-10, with the labels that each got.

#692 Force non-interactive mode for dpkg via apt-get.
  pkg/installer/installation/prerequisites.go
  pkg/upgrader/upgrade/kubernetes_binaries.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#693 Inline DEBIAN_FRONTEND environment variable
  pkg/installer/installation/prerequisites.go
  pkg/upgrader/upgrade/kubernetes_binaries.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#596 Add support for Hetzner Private Networking
  CHANGELOG.md
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#694 Add release date to the changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#695 NodePorts security group on AWS with public IPs
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#696 Properly handle credentials if cloud provider is none
  pkg/credentials/credentials.go
  pkg/credentials/secret.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#699 Bump default Kubernetes version to v1.16.1
  docs/quickstart-aws.md
  docs/quickstart-azure.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
  docs/quickstart-vsphere.md
  pkg/cmd/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#702 Update machine-controller to v1.5.8
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#703 pkg/cmd: Fix typo in help text of flag --tfjson
  pkg/cmd/root.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#698 Allow configuring proxy settings from terraform
  examples/terraform/aws-private/output.tf
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#704 Node local DNS cache
  go.mod
  go.sum
  pkg/installer/installation/install.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/nodelocaldns/nodelocaldns.go
  pkg/upgrader/upgrade/upgrade.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#705 docs: Update quickstarts
  docs/quickstart-aws.md
  docs/quickstart-azure.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
  docs/quickstart-vsphere.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#708 Fix determine hostname for upgrades
  pkg/upgrader/upgrade/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#709 docs: enable multizone for GCE clusters
  docs/quickstart-gce.md
  examples/terraform/gce/output.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#711 Update E2E runner script to work with GCP
  hack/run-ci-e2e-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#713 Switch golangci-linter to whitelist mode
  .golangci.yml
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/scheme/scheme.go
  pkg/apis/kubeone/validation/validation.go
  pkg/cmd/config.go
  pkg/credentials/credentials.go
  pkg/installer/installation/reset.go
  pkg/ssh/connection.go
  pkg/templates/machinecontroller/webhook.go
  pkg/upgrader/upgrade/kubernetes_binaries.go
  pkg/upgrader/upgrade/util.go
  pkg/yamled/document_test.go
  test/e2e/conformance_test.go
  test/e2e/kubetest.go
  test/e2e/main_test.go
  test/e2e/testutil/testutil.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#712 Upgrade controller-runtime to v0.3.0
  .wwhrd.yml
  Makefile
  go.mod
  go.sum
  pkg/certificate/certificate.go
  pkg/certificate/pki.go
  pkg/installer/installation/install.go
  pkg/kubeconfig/kubeconfig.go
  pkg/templates/canal/canal.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/externalccm/packet.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/helper.go
  pkg/templates/machinecontroller/webhook.go
  pkg/templates/nodelocaldns/nodelocaldns.go
  pkg/upgrader/upgrade/preflight_checks.go
  pkg/upgrader/upgrade/upgrade.go
  pkg/upgrader/upgrade/upgrade_machine_deployments.go
  pkg/upgrader/upgrade/util.go
  test/e2e/main_test.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#714 Divert kube-api access via SSH tunnel
  .golangci.yml
  Makefile
  examples/terraform/aws-private/main.tf
  pkg/apis/kubeone/helpers.go
  pkg/cmd/kubeconfig.go
  pkg/installer/installation/kubeconfig.go
  pkg/kubeconfig/kubeconfig.go
  pkg/ssh/connection.go
  pkg/ssh/connector.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#718 Update Canal CNI to v3.10
  pkg/templates/canal/canal.go
  pkg/templates/canal/crd.go
  pkg/templates/canal/daemonset.go
  pkg/templates/canal/prerequisites.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#720 Update metrics-server to v0.3.6
  pkg/templates/metricsserver/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#723 Hetzner CCM has no need for HostNetwork
  pkg/templates/externalccm/hetzner.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#724 vSphere credentials format that CCM would read
  docs/quickstart-vsphere.md
  pkg/credentials/credentials.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#726 Update Hetzner CCM to v1.5.0
  pkg/templates/externalccm/hetzner.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#722 Update DigitalOcean Cloud Controller Manager to v0.1.21
  pkg/templates/externalccm/digitalocean.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#727 Fix kubeone reset
  pkg/installer/installation/reset.go
  pkg/templates/externalccm/ccm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS
