Repository kubermatic/kubeone, pull requests merged in 2020-02, with the labels that each got.

#781 Add the KubeOne Addons proposal
  docs/proposals/20200205-addons.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#783 ARM64 support
  pkg/scripts/os.go
  pkg/templates/canal/canal.go
  pkg/templates/metricsserver/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#784 Use upstream metrics-server image
  pkg/templates/metricsserver/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#782 Implement Addons
  .golangci.yml
  go.mod
  go.sum
  pkg/addons/addons.go
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/defaults.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/cmd/install.go
  pkg/cmd/reset.go
  pkg/cmd/upgrade.go
  pkg/installer/installation/install.go
  pkg/installer/installer.go
  pkg/state/context.go
  pkg/upgrader/upgrade/upgrade.go
  pkg/upgrader/upgrader.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#785 Add addons docs
  docs/addons.md
  docs/proposals/20200205-addons.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#789 docs(README.md): Update "Downloading a binary from GitHub Releases" section
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#790 Allow declaration of leader instance
  examples/terraform/aws/output.tf
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/defaults.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/validation/validation.go
  pkg/installer/installation/kubeadm_leader.go
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#791 Fix apt proxy configuration on ubunt/debian
  pkg/scripts/os.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#794 Manual cluster recovery documentation
  docs/manual-cluster-repair.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#797 Upgrade k8s.io libs to v0.16.4
  go.mod
  go.sum
  pkg/templates/machinecontroller/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#796 Proxy docs
  .golangci.yml
  docs/proxy.md
  pkg/apis/kubeone/v1alpha1/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#800 Fix quickstart docs regarding scaling
  docs/quickstart-aws.md
  docs/quickstart-azure.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
  docs/quickstart-vsphere.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#801 Fix inconsistencies in the quickstart docs
  docs/quickstart-aws.md
  docs/quickstart-azure.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-vsphere.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#802 Enable Strict mode to decode KubeOne API
  pkg/apis/kubeone/scheme/scheme.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#804 Fix links in the addons docs
  docs/addons.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#806 Fix AWS shared credentials
  pkg/credentials/credentials.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#803 KubeOne Reconciliation (apply) proposal
  docs/proposals/20200224-apply.md
  docs/proposals/apply-flowchart.drawio
  docs/proposals/apply-flowchart.svg
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#811 Update github.com/pkg/errors
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
