Repository kubermatic/kubeone, pull requests merged in 2020-03, with the labels that each got.

#815 Update docs for the v0.11.0 release
  CHANGELOG.md
  docs/README.md
  docs/environment_variables.md
  docs/quickstart-aws.md
  docs/quickstart-azure.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
  docs/quickstart-vsphere.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#817 Fix broken link in the documentation index
  docs/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#819 Fix IsLeader parsing from terraform
  examples/terraform/aws/output.tf
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#820 OpenStack external CCM
  examples/terraform/openstack/main.tf
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
  hack/run-ci-e2e-test.sh
  pkg/apis/kubeone/helpers.go
  pkg/clusterstatus/etcdstatus/etcdstatus.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/externalccm/openstack.go
  pkg/templates/externalccm/packet.go
  test/e2e/conformance_test.go
  test/e2e/kubeone.go
  test/e2e/main_test.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#823 Add new Untaint API Field to avoid default master taint
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/cmd/config.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/terraform/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#824 Verify are machine-controller CRDs Established before creating MachineDeployments
  pkg/templates/machinecontroller/helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#825 Document sshd config options requirements
  docs/ssh.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#827 fix doc link for addons
  docs/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#826 Fix openstack e2e tests image selection
  examples/terraform/openstack/main.tf
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
  hack/run-ci-e2e-test.sh
  test/e2e/conformance_test.go
  test/e2e/main_test.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#832 NodeSelector for machine-controller and its webhook
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#808 Update machine-controller to v1.11.1
  examples/terraform/aws/output.tf
  examples/terraform/azure/output.tf
  examples/terraform/gce/output.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/openstack/output.tf
  examples/terraform/packet/output.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
  go.mod
  go.sum
  pkg/cmd/root.go
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/helper.go
  pkg/templates/machinecontroller/machines.go
  pkg/terraform/config.go
  pkg/upgrader/upgrade/upgrade_machine_deployments.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#831 Allow node resources in examples/terraform/vsphere to be changed by variables
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#837 Add the ability to enable PodPresets
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/features/activate.go
  pkg/features/podpresets.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#842 Add Kubernetes 1.18 E2E binaries
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#845 Add configuration examples for PodPresets (reopened)
  pkg/cmd/config.go
  pkg/features/podpresets.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
