Repository kubermatic/kubeone, pull requests merged in 2020-09, with the labels that each got.

#1086 Update machine-controller to v1.17.1
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1088 Add changelog for the v1.0.2 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1090 Mention kubeadm components bug in the changelog for v1.0 releases
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1092 Update release process document
  docs/release_process.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1094 Add KubeletConfiguration to kubeadm configs
  pkg/templates/kubeadm/kubeadmv1beta1.go
  pkg/templates/kubeadm/kubeadmv1beta2.go
  pkg/templates/kubeadm/kubelet.go
  pkg/templates/yaml.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1095 Update CentOS and Flatcar AMIs used for E2E tests
  test/e2e/os.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1096 Dynamically determine AMI for E2E tests. Support for CentOS7 in E2E tests
  .golangci.yml
  test/e2e/conformance_test.go
  test/e2e/os.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1098 Explicitly restart Kubelet on upgrade for Ubuntu
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1100 Update kubernetes-cni to v0.8.7
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCoreOS-force.golden
  pkg/scripts/testdata/TestKubeadmCoreOS-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICoreOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1101 New v1beta1 .ContainerRuntime field
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/conversion.go
  pkg/apis/kubeone/v1alpha1/conversion_test.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1102 hetzner ubuntu-20.04
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  examples/terraform/hetzner/versions.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1103 Add the Cluster Autoscaler addon
  addons/cluster-autoscaler/README.md
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1106 Update e2e image
  .prow.yaml
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1105 Update machinecontroller to v1.17.2
  examples/terraform/hetzner/output.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/templates/machinecontroller/deployment.go
  pkg/terraform/v1beta1/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1108 Merge CloudProvider structs instead of overriding them when cloud provider is defined via Terraform
  pkg/terraform/v1beta1/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1109 Add the CSIMigration and CSIMigrationComplete fields to the API
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/cmd/config.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/feature, lgtm, release-note, size/L

#1111 Use CentOS7 Docker repo for both CentOS 7 and 8
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1114 Update machine-controller to v1.18.0
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1120 Add changelog for the v1.0.3 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1117 add info for apply about machine deployment
  pkg/cmd/apply.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1099 Don't stop Kubelet when upgrading Kubeadm on Flatcar
  pkg/scripts/os.go
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICoreOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1123 Add hostnames to the terraform vSphere example
  examples/terraform/vsphere/outputs.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1124 Fix hostnames for vSphere terraform
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/outputs.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
