Repository kubermatic/kubeone, pull requests merged in 2020-12, with the labels that each got.

#1179 fix dns-resolution for minio
  addons/backups-restic/backups-restic.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1183 use a single shared ssh connection for proxying individual tcp connec…
  pkg/cmd/proxy.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1191 Fix wrong legacy docker version on RPM systems
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1190 Safeguard against sudden and dramatic cluster reconfigurations
  pkg/apis/kubeone/helpers.go
  pkg/cmd/apply.go
  pkg/state/cluster.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1202 image-loader: Update Calico to v3.16.5
  hack/image-loader.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1203 Package upgrades
  go.mod
  go.sum
  pkg/addons/manifest.go
  pkg/apis/kubeone/validation/validation.go
  pkg/cmd/apply.go
  pkg/cmd/version.go
  pkg/kubeflags/flags.go
  pkg/scripts/render.go
  pkg/state/cluster.go
  pkg/tasks/preflight_checks.go
  pkg/tasks/preflight_checks_test.go
  pkg/tasks/probes.go
  pkg/templates/admissionconfig/admissionconfig.go
  pkg/templates/kubeadm/kubeadm.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  test/e2e/kubetest.go
  test/e2e/main_test.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
