Repository kubermatic/kubeone, pull requests merged in 2020-06, with the labels that each got.

#917 Use v1beta1 API in E2E tests
  pkg/apis/kubeone/v1beta1/helpers.go
  pkg/terraform/v1beta1/config.go
  test/e2e/conformance_test.go
  test/e2e/kubeone.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#919 Move CI jobs to .prow.yaml
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#921 fix urls to new doc for hetzner example
  examples/terraform/hetzner/README.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#920 Add support for the PodNodeSelector admission controller
  hack/boilerplate/boilerplate.py
  pkg/apis/apiserver/v1/types.go
  pkg/apis/apiserver/v1/zz_generated.deepcopy.go
  pkg/apis/apiserver/v1alpha1/types.go
  pkg/apis/apiserver/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/configupload/configuration.go
  pkg/features/activate.go
  pkg/features/podnodeselector.go
  pkg/features/podpresets.go
  pkg/features/psp.go
  pkg/scripts/configs.go
  pkg/scripts/kubeadm.go
  pkg/scripts/testdata/TestKubeadmReset-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmReset-verbose.golden
  pkg/tasks/prerequisites.go
  pkg/templates/admissionconfig/admissionconfig.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#922 Small updates to the README
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#923 Bump Go and k8s versions in the kubeone-e2e image
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#925 Add support for Kubernetes 1.16.11, 1.17.7, 1.18.4 releases
  pkg/scripts/funcs.go
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCoreOS-force.golden
  pkg/scripts/testdata/TestKubeadmCoreOS-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestRemoveBinariesCentOS.golden
  pkg/scripts/testdata/TestRemoveBinariesDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICoreOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#927 Add changelog for the v1.0.0-alpha.5 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#924 Bump Go and k8s versions in .prow.yaml
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#929 Fix CNI URL for CoreOS/Flatcar
  CHANGELOG.md
  pkg/scripts/funcs.go
  pkg/scripts/os.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmCoreOS-force.golden
  pkg/scripts/testdata/TestKubeadmCoreOS-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICoreOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#930 Add changelog for the v1.0.0-alpha.6 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#932 Fixed link in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#933 Use the proper package revision on CentOS and reintroduce the kubernetes-cni package
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#936 Stop copying admin.conf to $HOME
  pkg/addons/addons.go
  pkg/runner/runner.go
  pkg/scripts/configs.go
  pkg/scripts/configs_test.go
  pkg/scripts/node.go
  pkg/scripts/testdata/TestDrainNode.golden
  pkg/scripts/testdata/TestKubernetesAdminConfig.golden
  pkg/scripts/testdata/TestUncordonNode.golden
  pkg/tasks/kubeconfig.go
  pkg/tasks/tasks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#937 Update machine-controller to v1.14.3
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#938 Add changelog for the v1.0.0-alpha.7 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
