Repository kubermatic/kubeone, pull requests merged in 2020-05, with the labels that each got.

#887 Access etcd using gRPC API
  Makefile
  go.mod
  go.sum
  pkg/addons/manifest_test.go
  pkg/clusterstatus/apiserverstatus/apiserverstatus.go
  pkg/clusterstatus/clusterstatus.go
  pkg/clusterstatus/etcdstatus/etcdstatus.go
  pkg/clusterstatus/preflightstatus/preflightstatus.go
  pkg/cmd/shared.go
  pkg/cmd/status.go
  pkg/config/migrate_test.go
  pkg/ssh/connection.go
  pkg/ssh/connector.go
  pkg/ssh/sshtunnel/httptunnel.go
  pkg/state/context.go
  pkg/tasks/kubeconfig.go
  pkg/tasks/preflight_checks.go
  pkg/tasks/tasks.go
  pkg/testhelper/helper.go
  test/e2e/kubeone.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#891 Fix folder usage in vSphere example
  docs/quickstart-vsphere.md
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#889 Add KubeOneCluster v1beta1 API
  hack/update-codegen.sh
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta1/doc.go
  pkg/apis/kubeone/v1beta1/register.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/v1beta1/zz_generated.defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#892 Add changelog for the v1.0.0-alpha.1 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#893 Fix gobetween.sh on centos8
  Makefile
  examples/terraform/hetzner/gobetween.sh
  examples/terraform/openstack/gobetween.sh
  examples/terraform/packet/gobetween.sh
  examples/terraform/vsphere/gobetween.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#895 Fixed Flatcar/CoreOS for kubernetes v1.18
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCoreOS-simple.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#896 Bind docker-ce-cli to the same version as docker-ce
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#899 upgrade machine-controller to v1.14.0
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#900 Add changelog for the v1.0.0-alpha.2 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#902 Hold the docker-ce-cli package
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestRemoveBinariesCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#903 CentOS: update repo and lock configs before upgrade
  pkg/scripts/os.go
  pkg/scripts/os_test.go
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/tasks/kubernetes_binaries.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#904 Fix CoreOS install and upgrade scripts
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCoreOS-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCoreOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#905 Add changelog for the v1.0.0-alpha.3 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#906 Changelog: Add CoreOS issues to known issues
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#897 Rearrange linter settings
  .golangci.yml
  pkg/apis/kubeone/helpers.go
  pkg/clusterstatus/apiserverstatus/apiserverstatus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#908 Fix Flatcar/CoreOS kubelet unit
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCoreOS-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCoreOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#907 [release/v0.11] Bind the docker-ce-cli package, update machine-controller, and fix CoreOS scripts
  pkg/addons/manifest_test.go
  pkg/config/migrate_test.go
  pkg/installer/installation/kubeconfig.go
  pkg/scripts/os.go
  pkg/templates/machinecontroller/deployment.go
  test/e2e/kubeone.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#910 [release/v0.11] Add changelog for the v0.11.2 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#911 Add changelog for the v0.11.2 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#909 CoreOS: Add empty ExecStart to the kubelet service file
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmCoreOS-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCoreOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#912 Add changelog for the v1.0.0-alpha.4 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#913 Update Kubernetes Versions Compatibility matrix
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#890 [docs] Point main docs to the docs.kubermatic.com site
  README.md
  addons/README.md
  docs/README.md
  docs/addons.md
  docs/api_migration.md
  docs/environment_variables.md
  docs/example-loadbalancer.md
  docs/frequently_asked_questions.md
  docs/manual-cluster-repair.md
  docs/project_structure.md
  docs/proxy.md
  docs/quickstart-aws.md
  docs/quickstart-azure.md
  docs/quickstart-digitalocean.md
  docs/quickstart-gce.md
  docs/quickstart-hetzner.md
  docs/quickstart-openstack.md
  docs/quickstart-packet.md
  docs/quickstart-vsphere.md
  docs/ssh.md
  docs/upgrading_cluster.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL
