Repository kubermatic/kubeone, pull requests merged in 2020-10, with the labels that each got.

#1126 Use our internal GOPROXY for module downloading
  .prow.yaml
  Makefile
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1127 Status logging
  pkg/addons/addons.go
  pkg/certificate/ca.go
  pkg/clusterstatus/preflightstatus/preflightstatus.go
  pkg/credentials/secret.go
  pkg/features/activate.go
  pkg/kubeconfig/kubeconfig.go
  pkg/tasks/certs.go
  pkg/tasks/cni.go
  pkg/tasks/controlplane.go
  pkg/tasks/coredns.go
  pkg/tasks/etcd.go
  pkg/tasks/kubeadm_config.go
  pkg/tasks/kubeconfig.go
  pkg/tasks/machine_deployments.go
  pkg/tasks/preflight_checks.go
  pkg/tasks/prerequisites.go
  pkg/tasks/probes.go
  pkg/tasks/reset.go
  pkg/tasks/task.go
  pkg/tasks/upgrade_follower.go
  pkg/tasks/upgrade_leader.go
  pkg/tasks/upgrade_static_workers.go
  pkg/tasks/util.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/machinecontroller/helper.go
  pkg/templates/nodelocaldns/nodelocaldns.go
  test/e2e/conformance_test.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#1128 Create a dedicated vSphere CCM secret
  pkg/credentials/credentials.go
  pkg/credentials/secret.go
  pkg/templates/nodelocaldns/nodelocaldns.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1130 Enable disk.enableUUID for vSphere control plane instances
  examples/terraform/vsphere/main.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1132 Skip subPath NodeConformance test on Flatcar
  .golangci.yml
  test/e2e/conformance_test.go
  test/e2e/kubetest.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1134 Use KubeletConfiguration Go type instead of a YAML template
  go.mod
  go.sum
  pkg/templates/kubeadm/kubeadmv1beta1.go
  pkg/templates/kubeadm/kubeadmv1beta2.go
  pkg/templates/kubeadm/kubelet.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1135 Update flannel to 0.13
  pkg/templates/canal/canal.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1139 Add the changelog for the v1.0.4 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1141 Update machine-controller to v1.19.0
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1143 Add the changelog for the v1.0.5 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1145 Implement the OverwriteRegistry functionality
  addons/backups-restic/backups-restic.yaml
  addons/calico-vxlan/calico-vxlan.yaml
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/templates/canal/canal.go
  pkg/templates/canal/daemonset.go
  pkg/templates/canal/deployment.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/externalccm/openstack.go
  pkg/templates/externalccm/packet.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/webhook.go
  pkg/templates/metricsserver/deployment.go
  pkg/templates/nodelocaldns/nodelocaldns.go
  pkg/templates/weave/weave-net.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1150 Update generated API docs
  docs/api_reference/v1beta1.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1148 Add the image-loader Bash script
  hack/image-loader.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1151 Include image-loader in the release assets
  .goreleaser.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1152 Add addons to the release archive
  .goreleaser.yml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1147 Add the changelog for the v1.1.0-rc.0 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1153 Upgrade WeaveNet to 2.7.0
  hack/image-loader.sh
  pkg/templates/weave/weave-net.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS
