Repository kubermatic/kubeone, pull requests merged in 2020-11, with the labels that each got.

#1149 Update hcloud-cloud-controller-manager image in hertzner.go
  hack/image-loader.sh
  pkg/templates/externalccm/hetzner.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1154 Generate Docker configuration from a DockerConfig struct
  pkg/scripts/funcs.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCoreOS-force.golden
  pkg/scripts/testdata/TestKubeadmCoreOS-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1156 heredoc
  go.mod
  go.sum
  pkg/cmd/apply.go
  pkg/cmd/config.go
  pkg/cmd/install.go
  pkg/cmd/kubeconfig.go
  pkg/cmd/packaging.go
  pkg/cmd/proxy.go
  pkg/cmd/reset.go
  pkg/cmd/status.go
  pkg/cmd/upgrade.go
  pkg/cmd/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1155 Add support for insecure Docker registries
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/cmd/config.go
  pkg/scripts/funcs.go
  pkg/scripts/os.go
  pkg/scripts/os_test.go
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCoreOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCoreOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1157 Overwrite machine-controller Hyperkube and Kubelet image repositories
  hack/image-loader.sh
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1161 Overwrite pause image on worker nodes
  hack/image-loader.sh
  pkg/scripts/kubeadm.go
  pkg/state/context.go
  pkg/tasks/kubeadm_config.go
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1159 Add vSphere external CCM
  pkg/apis/kubeone/helpers.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/externalccm/vsphere.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#1162 Add the changelog for the v1.1.0 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1165 Add scrape prometheus headless service for nodelocaldns
  pkg/templates/nodelocaldns/nodelocaldns.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1166 Support for the static workers defined in terraform
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  go.sum
  pkg/terraform/v1beta1/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1167 Add amzn2 image to aws terraform example
  examples/terraform/aws/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1170 Add the ImageConfiguration API
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/metricsserver/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1171 ImageConfiguration -> AssetConfiguration
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/metricsserver/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1172 Fix dangling newline
  pkg/tasks/probes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1173 Add support for Amazon Linux 2 and refactor the AssetConfiguration API
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/scripts/funcs.go
  pkg/scripts/kubeadm.go
  pkg/scripts/os.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmInit-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmInit-verbose.golden
  pkg/scripts/testdata/TestKubeadmJoin-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmJoin-verbose.golden
  pkg/tasks/kubernetes_binaries.go
  pkg/tasks/prerequisites.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/metricsserver/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1163 Update calico to v3.16.5
  pkg/templates/canal/canal.go
  pkg/templates/canal/daemonset.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M

#1174 Feature machine deployment annotations
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/templates/machinecontroller/machines.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/M

#1175 Improve Amazon Linux 2 support and ensure apply command works
  .golangci.yml
  pkg/scripts/os.go
  pkg/scripts/os_test.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestRemoveBinariesAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/tasks/probes.go
  pkg/tasks/reset.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1176 Fix remove binaries script for Amazon Linux and Flatcar
  pkg/scripts/os.go
  pkg/scripts/testdata/TestRemoveBinariesAmazonLinux.golden
  pkg/scripts/testdata/TestRemoveBinariesCoreOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1177 Add the changelog for v1.2.0-alpha.0
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
