Repository kubermatic/kubeone, pull requests merged in 2021-05, with the labels that each got.

#1336 Update machine-controller to v1.28.0
  go.mod
  go.sum
  hack/image-loader.sh
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1334 kubeone list-images subcommand
  go.mod
  go.sum
  hack/image-loader.sh
  pkg/cmd/config-images.go
  pkg/cmd/config.go
  pkg/cmd/version.go
  pkg/state/context.go
  pkg/templates/canal/canal.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/externalccm/openstack.go
  pkg/templates/externalccm/packet.go
  pkg/templates/externalccm/vsphere.go
  pkg/templates/images/images.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/helper.go
  pkg/templates/machinecontroller/webhook.go
  pkg/templates/metricsserver/deployment.go
  pkg/templates/nodelocaldns/nodelocaldns.go
  pkg/templates/weave/weave-net.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1338 re-sort import statements
  .gimps.yaml
  pkg/apis/kubeone/config/migrate_test.go
  pkg/apis/kubeone/v1alpha1/conversion_test.go
  pkg/cmd/config-images.go
  pkg/kubeconfig/kubeconfig.go
  pkg/ssh/sshiofs/fs.go
  pkg/state/cluster.go
  pkg/templates/externalccm/vsphere.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1341 ensure consistent package aliases
  .gimps.yaml
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/scheme/scheme.go
  pkg/features/psp.go
  pkg/templates/canal/deployment.go
  pkg/templates/machinecontroller/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1339 General Amazon Linux 2 support
  examples/terraform/aws/variables.tf
  pkg/scripts/os.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/os_flatcar.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestRemoveBinariesAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/templates/images/images.go
  test/e2e/eksd.go
  test/e2e/os.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1251 Fix missing confirmation for reset
  pkg/cmd/apply.go
  pkg/cmd/reset.go
  pkg/cmd/shared.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-action-required, size/M

#1346 fix typo
  examples/terraform/gce/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1358 Use latest available (wildcard) docker and containerd version
  pkg/scripts/funcs.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1361 Add worker_deploy_ssh_key Terraform variable to the AWS configs
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M
