Repository kubermatic/kubeone, pull requests merged in 2021-04, with the labels that each got.

#1304 Disable repo_gpgcheck for the Kubernetes yum repo
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1300 Automate certificates renew
  .prow.yaml
  pkg/cmd/apply.go
  pkg/state/cluster.go
  pkg/state/cluster_test.go
  pkg/tasks/certs.go
  pkg/tasks/certs_test.go
  pkg/tasks/preflight_checks.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1305 Remove e2e build tag
  .prow.yaml
  hack/run-ci-e2e-test.sh
  test/e2e/conformance_test.go
  test/e2e/main_test.go
  test/e2e/upgrade_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1306 [Azure] Added 30 second delay in output so that publicIP for Azure VM is available
  examples/terraform/azure/main.tf
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1311 Add Kubernetes 1.21 binaries to the kubeone-e2e image
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1312 Add Kubernetes 1.21 presubmits
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1310 Use spot instances for E2E on AWS
  .prow.yaml
  examples/terraform/aws/README.md
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1241 Add support for Encryption Providers
  docs/api_reference/v1beta1.en.md
  docs/proposals/20210112-encryption-roviders.md
  go.mod
  go.sum
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/apply.go
  pkg/cmd/config.go
  pkg/features/activate.go
  pkg/features/encryption_providers.go
  pkg/scripts/configs.go
  pkg/scripts/kubeadm.go
  pkg/scripts/node.go
  pkg/scripts/testdata/TestKubeadmReset-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmReset-verbose.golden
  pkg/state/cluster.go
  pkg/state/context.go
  pkg/tasks/encryption_providers.go
  pkg/tasks/nodes.go
  pkg/tasks/prerequisites.go
  pkg/tasks/probes.go
  pkg/tasks/task.go
  pkg/tasks/tasks.go
  pkg/templates/encryptionproviders/encryption_providers.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1318 Remove CCM/CSI migration fields from the example manifest
  pkg/cmd/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1319 Add simple unit test for config print command
  pkg/cmd/config_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1314 Format .prow.yaml with YQ
  .prow.yaml
  Makefile
  hack/run-ci-e2e-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1321 New KubeOne logo
  docs/img/kubeone-logo-text.png
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1322 New KubeOne logo
  docs/img/kubeone-logo-text.png
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1320 Add support for KMS mounts in kubeapi
  docs/proposals/20210112-encryption-roviders.md
  pkg/cmd/apply.go
  pkg/state/cluster.go
  pkg/state/context.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1328 Fix OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1324 SSH FS
  go.mod
  go.sum
  pkg/configupload/configuration.go
  pkg/etcdutil/etcd.go
  pkg/kubeconfig/kubeconfig.go
  pkg/runner/runner.go
  pkg/scripts/ca.go
  pkg/scripts/configs.go
  pkg/scripts/kubeadm.go
  pkg/scripts/testdata/TestCopyPKIHome-.-subdir-test.golden
  pkg/scripts/testdata/TestCopyPKIHome-test-dir1.golden
  pkg/scripts/testdata/TestKubeadmCert-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmCert-verbose.golden
  pkg/scripts/testdata/TestKubeadmReset-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmReset-verbose.golden
  pkg/scripts/testdata/TestSaveAuditPolicyConfig-kubeone1.golden
  pkg/scripts/testdata/TestSaveAuditPolicyConfig-kubeone2.golden
  pkg/ssh/connection.go
  pkg/ssh/sshiofs/file.go
  pkg/ssh/sshiofs/fs.go
  pkg/ssh/sshiofs/types.go
  pkg/tasks/certs.go
  pkg/tasks/encryption_providers.go
  pkg/tasks/tasks.go
  pkg/tasks/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1329 Fix AWS config for terraform 0.15
  examples/terraform/aws/main.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1331 Fix missing ClusterRole rule for cluster autoscaler
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1330 Unexport bunch of functions from pkg/tasks
  pkg/tasks/encryption_providers.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1335 Ignore preexisting static manifests kubeadm preflight error
  pkg/scripts/kubeadm.go
  pkg/scripts/testdata/TestKubeadmInit-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmInit-verbose.golden
  pkg/scripts/testdata/TestKubeadmJoin-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmJoin-verbose.golden
  pkg/templates/kubeadm/v1beta2/kubeadm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1316 Root CA bundle
  docs/api_reference/v1beta1.en.md
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/archive/targz.go
  pkg/certificate/ca.go
  pkg/certificate/cabundle/ca-bundle.go
  pkg/certificate/certificate.go
  pkg/cmd/config.go
  pkg/configupload/configuration.go
  pkg/scripts/ca.go
  pkg/scripts/ca_test.go
  pkg/scripts/configs.go
  pkg/scripts/kubeadm.go
  pkg/scripts/testdata/TestCopyPKIHome-.-subdir-test.golden
  pkg/scripts/testdata/TestCopyPKIHome-test-dir1.golden
  pkg/scripts/testdata/TestKubeadmCert-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmCert-verbose.golden
  pkg/scripts/testdata/TestKubeadmInit-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmInit-verbose.golden
  pkg/scripts/testdata/TestKubeadmJoin-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmJoin-verbose.golden
  pkg/scripts/testdata/TestKubeadmJoinWorker-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmJoinWorker-verbose.golden
  pkg/scripts/testdata/TestKubeadmReset-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmReset-verbose.golden
  pkg/scripts/testdata/TestKubeadmUpgradeLeader-v1beta2.golden
  pkg/scripts/testdata/TestSaveAuditPolicyConfig-kubeone1.golden
  pkg/scripts/testdata/TestSaveAuditPolicyConfig-kubeone2.golden
  pkg/scripts/testdata/TestSaveCloudConfig-kubeone1.golden
  pkg/scripts/testdata/TestSaveCloudConfig-kubeone2.golden
  pkg/tasks/certs.go
  pkg/tasks/controlplane.go
  pkg/tasks/nodes.go
  pkg/tasks/prerequisites.go
  pkg/tasks/tasks.go
  pkg/templates/externalccm/openstack.go
  pkg/templates/externalccm/vsphere.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL
