Repository kubermatic/kubeone, pull requests merged in 2021-12, with the labels that each got.

#1642 Addons list
  addons/addons.go
  go.mod
  go.sum
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/addons/helpers.go
  pkg/addons/list.go
  pkg/clusterstatus/clusterstatus.go
  pkg/cmd/addons.go
  pkg/cmd/root.go
  pkg/credentials/credentials.go
  pkg/features/activate.go
  pkg/features/metrics-server.go
  pkg/tabwriter/tabwriter.go
  pkg/tasks/cni.go
  pkg/tasks/tasks.go
  pkg/templates/csi/csi.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/machinecontroller/helper.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes

#1658 Update machine-controller to v1.37.1
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1660 Update API doc for the AssetConfiguration API
  docs/api_reference/v1beta1.en.md
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1661 Update machine-controller to v1.37.2
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1654 [release/v1.3] Update machine-controller to v1.37.2
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1662 Remove PodPresets feature from v1beta2 API
  docs/api_reference/v1beta1.en.md
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/conversion.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1665 refactor: move from io/ioutil to io and os packages
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/config/config.go
  pkg/clusterstatus/apiserverstatus/apiserverstatus.go
  pkg/clusterstatus/etcdstatus/etcdstatus.go
  pkg/configupload/configuration.go
  pkg/credentials/credentials.go
  pkg/ssh/connection.go
  pkg/tasks/kubeconfig.go
  pkg/testhelper/helper.go
  pkg/yamled/document_test.go
  test/e2e/kubeone.go
  test/e2e/testutil/testutil.go
Labels: release-note-none, lgtm, size/M, approved, needs-ok-to-test, dco-signoff: yes

#1666 Add support for OpenStack application credentials and update validation
  .golangci.yml
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1664 OS Script templates improvements
  pkg/apis/kubeone/helpers.go
  pkg/containerruntime/containerd_config.go
  pkg/containerruntime/docker_config.go
  pkg/containerruntime/map.go
  pkg/scripts/funcs.go
  pkg/scripts/os.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/os_flatcar.go
  pkg/scripts/os_test.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcat.golden
  pkg/scripts/testdata/TestMigrateToContainerd-insecureRegistry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/tasks/containerd.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#1671 Fix the overwrite registry functionality
  hack/image-loader.sh
  pkg/cmd/config-images.go
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1668 Addon directory path should be optional when using embedded addons
  pkg/addons/helpers.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/cmd/config.go
  pkg/cmd/shared.go
  test/e2e/kubeone.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1673 Generate configs AFTER installing container-runtime
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: release-note-none, lgtm, size/XL, approved, dco-signoff: yes

#1676 Update the kubeone-e2e image to v0.1.19
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1678 Add jobs for Kubernetes 1.23 and update other jobs as needed
  .prow.yaml
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes

#1681 update cilium to version 1.11
  addons/cni-cilium/cilium.yaml
  pkg/templates/images/images.go
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#1682 Update the build image to include the Go 1.17.5 update
  .prow.yaml
  hack/images/kubeone-e2e/Dockerfile
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1675 Vsphere ccm csi update
  addons/ccm-vsphere/ccm-vsphere.yaml
  addons/csi-vsphere/validatingwebhook.yaml
  addons/csi-vsphere/vsphere-csi-driver.yaml
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1683 Small cilium fixes
  addons/cni-cilium/cilium.yaml
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1677 Remove legacy docker support (kubernetes < 1.17)
  pkg/scripts/funcs.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1686 Allow seccomp profiles in privileged PSP
  pkg/features/psp.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1674 ContainerRuntime mirror registries v1beta2 API
  addons/machinecontroller/machine-controller.yaml
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/helpers_test.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/containerruntime/containerd_config.go
  pkg/containerruntime/containerd_config_test.go
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-docker.io_mirror_registry.golden
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-multi_registry_mirrors.golden
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-override_insecure_registry.golden
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-simple.golden
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes

#1688 Add changelog for the v1.3.3 release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1689 Update to Go 1.17.5 and golang.org/x/net to v0.0.0-20211209124913-491a49abca63
  .prow.yaml
  go.mod
  go.sum
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes

#1690 [release/v1.3] Add changelog for the v1.3.3 release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1692 Fix flatcar AMI filter
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1693 [release/v1.3] Fix flatcar AMI filter
  examples/terraform/aws/main.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1691 Resolve environment variables in addon parameters
  pkg/addons/manifest.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1695 Block IPVS on 1.23 clusters running Canal/Calico CNI
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1696 Deprecate kubeone install and upgrade commands in favor of kubeone apply, and use kubeone apply in E2E tests
  pkg/cmd/install.go
  pkg/cmd/upgrade.go
  test/e2e/kubeone.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1699 Remove the AssetConfiguration API from the v1beta2 API and remove support for Amazon EKS-D clusters
  docs/api_reference/v1beta1.en.md
  docs/api_reference/v1beta2.en.md
  hack/run-ci-e2e-test.sh
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta2/conversion.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  test/e2e/conformance_test.go
  test/e2e/eksd.go
  test/e2e/kubeone.go
  test/e2e/main_test.go
  test/e2e/upgrade_test.go
Labels: lgtm, release-note, size/XL, approved, kind/api-change, dco-signoff: yes

#1698 New KubeletConfig API
  docs/api_reference/v1beta2.en.md
  examples/terraform/aws/output.tf
  go.sum
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/helpers_test.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/templates/images/images.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1703 Automatically determine GCE zone for the initial MachineDeployment
  examples/terraform/gce/main.tf
  examples/terraform/gce/output.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1706 Fix issues when disabling nm-cloud-setup on RHEL
  pkg/scripts/os_centos.go
  pkg/tasks/prerequisites.go
  test/e2e/os.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1702 Add issue templates for Kubernetes support
  .github/ISSUE_TEMPLATE/kubernetes-support.md
  .github/ISSUE_TEMPLATE/update-images.md
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1663 Rebrand Packet to Equinix Metal
  .prow.yaml
  addons/ccm-equinixmetal/ccm-equinixmetal.yaml
  addons/ccm-packet/ccm-packet.yaml
  docs/api_reference/v1beta1.en.md
  docs/api_reference/v1beta2.en.md
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/etc_gobetween.tpl
  examples/terraform/equinixmetal/gobetween.sh
  examples/terraform/equinixmetal/main.tf
  examples/terraform/equinixmetal/output.tf
  examples/terraform/equinixmetal/variables.tf
  examples/terraform/equinixmetal/versions.tf
  go.mod
  go.sum
  hack/run-ci-e2e-test.sh
  pkg/addons/ensure.go
  pkg/addons/helpers.go
  pkg/addons/manifest.go
  pkg/apis/kubeone/config/migrate.go
  pkg/apis/kubeone/config/migrate_test.go
  pkg/apis/kubeone/config/testdata/config-equinix-metal-v1beta1.yaml
  pkg/apis/kubeone/config/testdata/config-equinix-metal-v1beta2.golden
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/conversion.go
  pkg/apis/kubeone/v1beta1/helpers.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/helpers.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/clientutil/create_or_update.go
  pkg/cmd/config.go
  pkg/credentials/credentials.go
  pkg/credentials/secret.go
  pkg/tasks/ccm_csi_migration.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/templates/resources/resources.go
  pkg/terraform/v1beta2/config.go
  test/e2e/conformance_test.go
  test/e2e/provisioner/provisioner.go
  test/e2e/upgrade_test.go
Labels: lgtm, release-note, approved, size/XXL, kind/api-change, dco-signoff: yes
