Repository kubermatic/kubeone, pull requests merged in 2021-06, with the labels that each got.

#1364 Support organizing addons into subdirectories
  pkg/addons/addons.go
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1366 chore: update aws variables to include type of value
  examples/terraform/aws/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1367 add WeirdMachine to OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1362 Docker to containerd automated migration
  go.mod
  go.sum
  pkg/clientutil/crds.go
  pkg/cmd/config-images.go
  pkg/cmd/config.go
  pkg/cmd/migrate.go
  pkg/cmd/root.go
  pkg/scripts/os.go
  pkg/scripts/os_test.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcat.golden
  pkg/scripts/testdata/TestMigrateToContainerd-insecureRegistry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/tasks/containerd.go
  pkg/tasks/containerd_test.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
  pkg/templates/canal/canal.go
  pkg/templates/images/images.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1373 OWNERS file update
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1369 Patch/value types
  examples/terraform/azure/variables.tf
  examples/terraform/digitalocean/variables.tf
  examples/terraform/gce/variables.tf
  examples/terraform/hetzner/variables.tf
  examples/terraform/openstack/variables.tf
  examples/terraform/packet/variables.tf
  examples/terraform/vsphere/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1374 add moath to owners file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1372 [release/v1.2] Fix AWS config for terraform 0.15
  examples/terraform/aws/main.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1368 Upgrade terraform to 1.0.0
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1375 Use updated kubermatic/kubeone-e2e:v0.1.16
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1371 [release/v1.2] Relaxed container runtime versions
  pkg/scripts/funcs.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1376 Terraform configs aligned to terraform 1.0.0
  examples/terraform/aws/versions.tf
  examples/terraform/azure/versions.tf
  examples/terraform/digitalocean/versions.tf
  examples/terraform/gce/versions.tf
  examples/terraform/hetzner/versions.tf
  examples/terraform/openstack/variables.tf
  examples/terraform/openstack/versions.tf
  examples/terraform/packet/versions.tf
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/versions.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1377 Add CHANGELOG for v1.2.2 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1378 [release/v1.2] Add CHANGELOG for v1.2.2 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1380 [release/v1.2] Pass -node-external-cloud-provider to the MC webhook
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1382 Add the changelog for the v1.2.3 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1384 Add links to the PRs to the v1.2.3 changelog
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1386 Remove CNI patching
  pkg/state/context.go
  pkg/tasks/cni.go
  pkg/tasks/tasks.go
  pkg/templates/canal/canal.go
  pkg/templates/canal/daemonset.go
  pkg/templates/externalccm/ccm.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1387 Implement a mechanism for embedding YAML addons into KubeOne binary
  addons/addons.go
  pkg/addons/addons.go
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/tasks/tasks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1389 Use new etcd client module
  go.mod
  go.sum
  pkg/clusterstatus/etcdstatus/etcdstatus.go
  pkg/etcdutil/etcd.go
  pkg/tasks/etcd.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1390 Fix hetzner ssh_port terraform type
  examples/terraform/hetzner/variables.tf
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1392 Replace the NodeLocalDNS template with an addon
  addons/nodelocaldns/nodelocaldns.yaml
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/tasks/tasks.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/nodelocaldns/nodelocaldns.go
  pkg/templates/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1393 Suppress client-go deprecation warnings
  pkg/kubeconfig/kubeconfig.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1399 Increase lint timeout to 5 min
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1396 Replace the DigitalOcean CCM Go template with an embedded addon
  addons/ccm-digitalocean/ccm-digitalocean.yaml
  pkg/addons/ensure.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1398 Ignore NodeLocalDNS when deploying user-provided addons
  pkg/addons/ensure.go
  pkg/tasks/tasks.go
  pkg/templates/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1400 Clean up CI jobs
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1397 Replace the Hetzner CCM Go template with an embedded addon
  addons/ccm-hetzner/ccm-hetzner.yaml
  pkg/addons/ensure.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1401 Replace the Packet CCM Go template with an embedded addon
  addons/ccm-packet/ccm-packet.yaml
  pkg/addons/ensure.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/externalccm/packet.go
  pkg/templates/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1404 Fix subsequent apply failures if CABundle is enabled
  pkg/tasks/certs.go
  pkg/tasks/prerequisites.go
  pkg/tasks/tasks.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1405 Convert canal CNI to an addon
  Makefile
  addons/cni-canal/README.md
  addons/cni-canal/canal.yaml
  examples/terraform/hetzner/output.tf
  go.mod
  go.sum
  hack/tools.go
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/tasks/cni.go
  pkg/templates/canal/canal.go
  pkg/templates/canal/crd.go
  pkg/templates/canal/daemonset.go
  pkg/templates/canal/deployment.go
  pkg/templates/canal/prerequisites.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1406 Use Internal images addons
  addons/ccm-digitalocean/ccm-digitalocean.yaml
  addons/ccm-hetzner/ccm-hetzner.yaml
  addons/ccm-packet/ccm-packet.yaml
  addons/nodelocaldns/nodelocaldns.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1391 Upgrade machine-controller to v1.33.0
  .prow.yaml
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
