Repository kubermatic/kubeone, pull requests merged in 2021-02, with the labels that each got.

#1235 Fix confusing defaults in OpenIDConnect
  pkg/apis/kubeone/v1alpha1/defaults.go
  pkg/apis/kubeone/v1beta1/defaults.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1236 Disallow and deprecate the PodPresets feature
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/types.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/cmd/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1237 Update KubeOne CI jobs
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1239 Update the kubeone-e2e image
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1238 Update machine-controller to v1.25.0
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1240 Add rsync on CentOS and Amazon Linux
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1243 Restart unhealthy API servers when provisioning/upgrading clusters
  pkg/scripts/node.go
  pkg/tasks/nodes.go
  pkg/tasks/tasks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1244 Add the Kubernetes 1.20 jobs
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1245 Use Docker for restarting API server on Flatcar
  pkg/scripts/node.go
  pkg/tasks/nodes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1213 Add encryption providers proposal
  docs/proposals/20210112-encryption-roviders.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1246 fix(docs): fix broken master documentation link
  README.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/S

#1248 Fix credentials in addons
  pkg/addons/addons.go
  pkg/credentials/credentials.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1249 Add the changelog for the v1.2.0-beta.1 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1250 Update README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1253 Improve the installation script
  README.md
  install.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
