Repository kubermatic/kubeone, pull requests merged in 2021-09, with the labels that each got.

#1484 Add support for vSphere CSI plugin
  addons/csi-vsphere/vsphere-csi-driver.yaml
  pkg/addons/ensure.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/cmd/config.go
  pkg/templates/csi/csi.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes

#1485 Check does kubelet.conf exists before trying to join static worker node
  pkg/scripts/kubeadm.go
  pkg/scripts/testdata/TestKubeadmJoinWorker-not-verbose.golden
  pkg/scripts/testdata/TestKubeadmJoinWorker-verbose.golden
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1462 New Addons API
  docs/api_reference/v1beta1.en.md
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1486 Enable Addon api
  addons/README.md
  addons/backups-restic/backups-restic.yaml
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/cmd/config.go
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes

#1487 Add support for vSphere CCM/CSI migration
  addons/csi-vsphere/validatingwebhook.yaml
  addons/csi-vsphere/vsphere-csi-driver.yaml
  pkg/addons/applier.go
  pkg/addons/manifest.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/cmd/migrate.go
  pkg/cmd/reset.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
  pkg/templates/resources/resources.go
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes

#1488 Add default-storage-class optional addon
  addons/default-storage-class/storage-class.yaml
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1489 Use proper versions for vSphere CCM/CPI and update machine-controller to v1.35.2
  pkg/addons/applier.go
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1490 Updated generated API doc
  docs/api_reference/v1beta1.en.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1492 Add changelog for v1.3.0-rc.0 release
  CHANGELOG.md
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1491 Hetzner CSI driver update
  addons/ccm-hetzner/ccm-hetzner.yaml
  addons/csi-hetzner/hcloud-csi.yml
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, release-blocker

#1493 Update v1.3.0-rc.0 changelog
  CHANGELOG.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, release-blocker

#1494 Drain and cordon control plane nodes when doing CSI migration
  CHANGELOG.md
  pkg/cmd/config.go
  pkg/cmd/migrate.go
  pkg/tasks/ccm_csi_migration.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes, release-blocker

#1497 Validate does addons directory exist at the beginning
  pkg/addons/applier.go
  pkg/apis/kubeone/helpers.go
  pkg/cmd/shared.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1499 Fix NPE when migrating to containerd
  pkg/addons/applier.go
  pkg/cmd/install.go
  pkg/cmd/migrate.go
  pkg/cmd/upgrade.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, release-blocker

#1500 Mark vSphere CCM/CSI migration as non-experimental
  CHANGELOG.md
  pkg/cmd/migrate.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1511 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/support-request.md
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1513 Install missing gnupg package on debian
  pkg/scripts/os_debian.go
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, release-blocker

#1517 Default MTU in calico-vxlan addon
  addons/calico-vxlan/README.md
  addons/calico-vxlan/calico-vxlan.yaml
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, release-blocker

#1518 fix indent for caBundle Volume in machine-controller.yaml
  addons/machinecontroller/machine-controller.yaml
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, release-blocker

#1516 Add changelog for the v1.3.0 release
  CHANGELOG.md
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes

#1532 Edit selinux config file only if file exists
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1530 openstack-terraform: open nodeports SG
  examples/terraform/openstack/main.tf
  examples/terraform/openstack/output.tf
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1535 aws-terraform: open nodeports unconditionally
  examples/terraform/aws/main.tf
  examples/terraform/aws/variables.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1529 gce-terraform: Open GCE nodeports
  examples/terraform/gce/main.tf
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1533 hetzner-terraform: add firewall
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  examples/terraform/hetzner/versions.tf
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1528 azure-terraform: allow nodeports
  examples/terraform/azure/main.tf
  examples/terraform/azure/variables.tf
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1531 openstack-addons: improve openstack addons
  addons/ccm-openstack/ccm-openstack.yaml
  addons/csi-openstack-cinder/controllerplugin.yaml
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1537 vsphere-terraform: fix keepalived script
  examples/terraform/vsphere/keepalived.sh
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1534 Update Go to 1.17.1
  .prow.yaml
  go.mod
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeone/v1alpha1/zz_generated.defaults.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/v1beta1/zz_generated.defaults.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1541 Update the kubeone-e2e image to Go 1.17.1
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1542 Update the remaining jobs to Go 1.17.1
  .prow.yaml
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1545 Fix Go build tags
  hack/tools.go
  pkg/apis/apiserver/v1/zz_generated.deepcopy.go
  pkg/apis/apiserver/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubeadm/bootstraptoken/v1/zz_generated.deepcopy.go
  pkg/apis/kubeadm/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeadm/v1beta3/zz_generated.deepcopy.go
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1546 Update controller-runtime to v0.10.1 and Kubernetes dependencies to 1.22.2
  go.mod
  go.sum
  pkg/nodeutils/drain.go
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes

#1544 CCM/CSI migration support for clusters with static worker nodes
  pkg/scripts/ccm_csi_migration.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/common.go
  pkg/tasks/common_test.go
  pkg/tasks/containerd.go
  pkg/tasks/tasks.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1552 Default image in the cluster-autoscaler addon
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes
