Repository kubermatic/kubeone, pull requests merged in 2021-08, with the labels that each got.

#1433 Fix addind second container to machinecontroller webhook deployment
  addons/machinecontroller/machine-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1435 Check if unzip is present on the current system.
  install.sh
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/XS

#1437 Upgrade machine-controller to v1.35.0
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1438 Azure CCM Manifests
  addons/ccm-azure/ccm-azure.yaml
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1441 Update images
  .golangci.yml
  .prow.yaml
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
  pkg/apis/kubeone/v1alpha1/conversion.go
  pkg/features/podnodeselector.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1442 Redirect push-e2e-image job failures to the appropriate channel
  .prow.yaml
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1440 Update machine-controller to v1.35.1
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1445 terraform/vsphere: Inherit firmware settings from the template VM
  examples/terraform/vsphere/main.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1443 Remove upx from the kubeone-e2e image
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1448 Extend restart API server script to handle failing crictl logs
  pkg/scripts/node.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1447 Add Kubernetes 1.22 tests and remove 1.18 tests
  .prow.yaml
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes

#1456 Enable PodSecurity admission controller for 1.22 clusters
  pkg/kubeflags/data.go
  pkg/kubeflags/flags.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1457 Use kubeadm/v1beta3 API for Kubernetes 1.22+ clusters
  pkg/apis/kubeadm/bootstraptoken/doc.go
  pkg/apis/kubeadm/bootstraptoken/v1/types.go
  pkg/apis/kubeadm/bootstraptoken/v1/utils.go
  pkg/apis/kubeadm/bootstraptoken/v1/zz_generated.deepcopy.go
  pkg/apis/kubeadm/v1beta3/types.go
  pkg/apis/kubeadm/v1beta3/zz_generated.deepcopy.go
  pkg/templates/kubeadm/kubeadm.go
  pkg/templates/kubeadm/kubeadmv1beta3.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#1460 Add changelog for v1.3.0-alpha.1 release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1463 Add support for versioned images
  pkg/cmd/config-images.go
  pkg/state/context.go
  pkg/templates/images/images.go
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes

#1465 Automatically deploy CSI plugin and driver for supported providers, and add support for OpenStack Cinder CSI
  addons/ccm-openstack/ccm-openstack.yaml
  addons/csi-openstack-cinder/controllerplugin-rbac.yaml
  addons/csi-openstack-cinder/controllerplugin.yaml
  addons/csi-openstack-cinder/driver.yaml
  addons/csi-openstack-cinder/nodeplugin-rbac.yaml
  addons/csi-openstack-cinder/nodeplugin.yaml
  pkg/tasks/tasks.go
  pkg/templates/csi/csi.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes

#1466 Increase the minimum Kubernetes version to v1.19
  .prow.yaml
  addons/csi-openstack-cinder/driver.yaml
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1473 Remove CSIMigration and CSIMigrationComplete fields from the API
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1alpha1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta1/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1474 Improve kubeone reset output
  pkg/cmd/reset.go
  pkg/tasks/reset.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1472 Implement the CCM/CSI migration
  addons/csi-openstack-cinder/driver.yaml
  addons/machinecontroller/machine-controller.yaml
  pkg/addons/applier.go
  pkg/apis/kubeadm/v1beta1/bootstraptokenstring.go
  pkg/apis/kubeadm/v1beta1/types.go
  pkg/apis/kubeadm/v1beta1/zz_generated.deepcopy.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/helpers_test.go
  pkg/cmd/migrate.go
  pkg/scripts/ccm_csi_migration.go
  pkg/scripts/ccm_csi_migration_test.go
  pkg/scripts/testdata/TestCCMMigrationRegenerateControlPlaneManifests-not-verbose.golden
  pkg/scripts/testdata/TestCCMMigrationRegenerateControlPlaneManifests-verbose.golden
  pkg/scripts/testdata/TestCCMMigrationUpdateKubeletConfig-not-verbose.golden
  pkg/scripts/testdata/TestCCMMigrationUpdateKubeletConfig-verbose.golden
  pkg/state/cluster.go
  pkg/state/context.go
  pkg/state/context_test.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
  pkg/templates/kubeadm/kubeadm.go
  pkg/templates/kubeadm/kubeadmv1beta1.go
  pkg/templates/kubeadm/v1beta1/kubeadm.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#1482 Properly annotate OpenStack PVs on CCM/CSI migration
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/tasks.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1483 Update metrics-server to v0.5.0
  addons/metrics-server/metrics-server.yaml
  pkg/addons/applier.go
  pkg/certificate/certificate.go
  pkg/templates/images/images.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes
