Repository kubermatic/kubeone, pull requests merged in 2021-03, with the labels that each got.

#1252 warn of explicit confirmation for reset
  pkg/cmd/reset.go
  test/e2e/kubeone.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/S

#1264 Add the changelog for the v1.2.0-rc.0 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1266 Add a template for the release cut issue
  .github/ISSUE_TEMPLATE/release.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1267 Update the kubeone-e2e image and build jobs to Go 1.16.1
  .prow.yaml
  .wwhrd.yml
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1268 Update E2E tests to use Go 1.16.1
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1270 Add the changelog for the v1.2.0-rc.1 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1272 Upgrade machinecontroller to v1.27.0
  hack/image-loader.sh
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1274 shfmt
  Makefile
  hack/apidoc-gen.sh
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/run-ci-e2e-test.sh
  hack/update-codegen.sh
  hack/verify-codegen.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1276 Use machinecontroller v1.27.1 to fix issue with flatcar
  hack/image-loader.sh
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1279 Upgrade dependencies
  .golangci.yml
  go.mod
  go.sum
  pkg/clientutil/create_or_update.go
  pkg/features/psp.go
  pkg/tasks/etcd.go
  pkg/templates/canal/canal.go
  pkg/templates/externalccm/digitalocean.go
  pkg/templates/externalccm/hetzner.go
  pkg/templates/externalccm/openstack.go
  pkg/templates/externalccm/packet.go
  pkg/templates/externalccm/vsphere.go
  pkg/templates/machinecontroller/deployment.go
  pkg/templates/machinecontroller/webhook.go
  pkg/templates/metricsserver/deployment.go
  pkg/templates/nodelocaldns/nodelocaldns.go
  pkg/templates/weave/weave-net.go
  test/e2e/conformance_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1282 Install cri-tools on Amazon Linux 2
  pkg/scripts/funcs.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1288 Upgrade machinecontroller to v1.27.4
  go.mod
  go.sum
  hack/image-loader.sh
  pkg/templates/machinecontroller/deployment.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1290 Use admissionregistration v1
  pkg/tasks/machine_deployments.go
  pkg/tasks/reset.go
  pkg/templates/machinecontroller/webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-action-required, size/M

#1292 Add the changelog for the v1.2.1 release
  CHANGELOG.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1291 Unattended upgrades addon
  .golangci.yml
  addons/unattended-upgrades/README.md
  addons/unattended-upgrades/apt.yaml
  addons/unattended-upgrades/fluo.yaml
  addons/unattended-upgrades/kured.yaml
  addons/unattended-upgrades/yum.yaml
  pkg/tasks/nodes.go
  pkg/tasks/tasks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL
