Repository kubermatic/kubeone, pull requests merged in 2022-12, with the labels that each got.

#2524 Use a slightly better pointer package
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/v1beta1/conversion.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/localhelm/helm3.go
  pkg/pointer/pointer.go
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes, docs/none

#2522 Uninstall helm release that was installed by kubeone but is not listed anymore in the Manifest
  pkg/localhelm/helm3.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/provided

#2526 [release/v1.5] Update Go to 1.19.4
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes

#2527 [release/v1.4] Update Go to 1.18.9
  .prow.yaml
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2525 Update Go to 1.19.4
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none, backport-needed

#2528 Add an option for tasks to mutate the State object
  pkg/state/task.go
  pkg/tasks/kubeadm_config.go
  pkg/tasks/tasks.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none, backport-needed

#2530 [release/v1.4] Add an option for tasks to mutate the State object
  pkg/state/task.go
  pkg/tasks/kubeadm_config.go
  pkg/tasks/tasks.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2531 Add tests for the December Kubernetes patch releases
  test/e2e/prow.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none, backport-needed

#2533 [release/v1.4] Add tests for the December Kubernetes patch releases
  .prow.yaml
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2532 [release/v1.5] Add tests for the December Kubernetes patch releases
  test/e2e/prow.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes

#2538 Update Canal/Calico to v3.23.5
  addons/cni-canal/canal.yaml
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/provided

#2539 [release/v1.5] Update Canal/Calico to v3.23.5
  addons/cni-canal/canal.yaml
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes

#2535 Add changelogs for 1.5.4 and 1.4.12
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#2541 Run E2E tests only if relevant files are changed
  test/e2e/helpers.go
  test/e2e/prow.yaml
  test/e2e/tests_definitions.go
  test/generator/main.go
  test/tests.yml
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, dco-signoff: yes, docs/none

#2543 add support for AWS x Cilium x IPv6+IPv4
  .golangci.yml
  addons/ccm-aws/ccm-aws.yaml
  addons/operating-system-manager/webhook.yaml
  examples/terraform/aws-dualstack/README.md
  examples/terraform/aws-dualstack/README.md.in
  examples/terraform/aws-dualstack/cloud_config.yaml
  examples/terraform/aws-dualstack/main.tf
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/etcdutil/etcd.go
  pkg/templates/images/images.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/tbd

#2546 Extend Terraform configs with `control_plane_vm_count` and `os` variables
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/main.tf
  examples/terraform/digitalocean/output.tf
  examples/terraform/digitalocean/variables.tf
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/main.tf
  examples/terraform/equinixmetal/output.tf
  examples/terraform/equinixmetal/variables.tf
  examples/terraform/gce/README.md
  examples/terraform/gce/main.tf
  examples/terraform/gce/variables.tf
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/main.tf
  examples/terraform/nutanix/variables.tf
  examples/terraform/openstack/README.md
  examples/terraform/openstack/main.tf
  examples/terraform/openstack/variables.tf
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/main.tf
  examples/terraform/vmware-cloud-director/variables.tf
  test/e2e/tests_definitions.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#2550 Replace control_plane_replicas with control_plane_vm_count for Hetzner
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/variables.tf
Labels: size/S, lgtm, approved, release-note-action-required, dco-signoff: yes, kind/deprecation, docs/tbd

#2552 Implement an interactive mode for `kubeone init` subcommand
  go.mod
  go.sum
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/cmd/initcmd/generate.go
  pkg/cmd/initcmd/helpers.go
  pkg/cmd/initcmd/init_test.go
  pkg/cmd/initcmd/interactive.go
  pkg/cmd/initcmd/models.go
  pkg/cmd/initcmd/providers.go
  pkg/cmd/initcmd/questions.go
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-canal_with_coredns-pdb.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-canal_with_encryption.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-canal_with_encryption_with_encryption_and_coredns-pdb.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-canal_with_features_and_addons.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-canal_with_features_and_autoscaler.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-canal_with_features_and_backups.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_replacement_with_coredns-pdb.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_replacement_with_encryption.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_replacement_with_encryption_with_encryption_and_coredns-pdb.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_replacement_with_features_and_addons.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_replacement_with_features_and_autoscaler.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_replacement_with_features_and_backups.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_with_coredns-pdb.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_with_encryption.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_with_encryption_with_encryption_and_coredns-pdb.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_with_features_and_addons.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_with_features_and_autoscaler.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-cilium_with_features_and_backups.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_aws.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_azure.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_digitalocean.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_equinixmetal.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_gce.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_hetzner.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_none.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_nutanix.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_openstack.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_vmware-cloud-director.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_vsphere-flatcar.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_on_vsphere.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_with_canal.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_with_cilium.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_with_cilium_replacement.golden
  pkg/cmd/initcmd/testdata/TestGenKubeOneClusterYAML-default_with_external.golden
  pkg/cmd/initcmd/testdata/TestGenTerraformVars-default.golden
  pkg/cmd/initcmd/testdata/TestGenTerraformVars-one_variable.golden
  pkg/cmd/initcmd/testdata/TestGenTerraformVars-two_variables.golden
  pkg/cmd/initcmd/validators.go
  pkg/tabwriter/tabwriter.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/tbd

#2554 Fix init interactive validation errors
  pkg/cmd/initcmd/generate.go
  pkg/cmd/initcmd/validators.go
Labels: kind/bug, release-note-none, size/S, lgtm, approved, dco-signoff: yes, docs/none

#2555 Fix CentOS 7 AMI filter
  examples/terraform/aws/README.md
  examples/terraform/aws/variables.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/regression, docs/none, backport-needed

#2559 [release/v1.5] Fix CentOS 7 AMI filter
  examples/terraform/aws/README.md
  examples/terraform/aws/variables.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/regression

#2560 Remove leftover `/tmp/k1-etc-environment` file
  pkg/scripts/proxy.go
  pkg/scripts/testdata/TestEnvironmentFile-empty-proxy.golden
  pkg/scripts/testdata/TestEnvironmentFile-http-https-no-proxy.golden
  pkg/scripts/testdata/TestEnvironmentFile-http-https-proxy.golden
  pkg/scripts/testdata/TestEnvironmentFile-http-proxy.golden
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2556 Run kubeadm with increased verbosity unconditionally
  pkg/state/context.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, backport-needed

#2567 Update Kubernetes dependencies to v1.26.0
  go.mod
  go.sum
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
  pkg/cmd/init.go
  pkg/cmd/shared.go
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes, docs/none

#2568 Add initial support for Kubernetes 1.26
  Makefile
  pkg/apis/kubeone/validation/validation.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm_test.go
  pkg/templates/kubernetesconfigs/kubeproxy.go
  test/e2e/helpers.go
  test/e2e/prow.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/provided

#2569 Update AWS images for Kubernetes 1.26
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2570 Update non-Kubernetes Go dependencies
  go.mod
  go.sum
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, dco-signoff: yes, docs/none
