Repository kubermatic/kubeone, pull requests merged in 2022-10, with the labels that each got.

#2394 Allow overriding image repository for CoreDNS
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/helpers_test.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/cmd/config.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/tbd

#2401 Fix path to API docs
  hack/ci/update-docs.sh
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes, docs/none

#2396 kubeone init: generate KubeOneCluster and optional terraform configuration
  .golangci.yml
  Makefile
  examples/embed.go
  pkg/apis/kubeone/v1beta2/helpers.go
  pkg/cmd/init.go
  pkg/cmd/init_test.go
  pkg/cmd/local.go
  pkg/cmd/root.go
  pkg/cmd/shared.go
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-aws.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-azure.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-digitalocean.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-equinixmetal.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-gce.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-hetzner.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-none.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-nutanix.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-openstack.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-vmware-cloud-director.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-vsphere-flatcar.golden
  pkg/cmd/testdata/Test_genKubeOneClusterYAML-vsphere.golden
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes, docs/tbd

#2404 Remove Kubernetes test binaries from kubeone-e2e image
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: lgtm, release-note, size/M, approved, kind/cleanup, dco-signoff: yes, docs/none

#2405 Initial support for Kubernetes 1.25
  .github/ISSUE_TEMPLATE/kubernetes-support.md
  pkg/apis/kubeone/validation/validation.go
  test/e2e/helpers.go
  test/e2e/prow.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/tbd

#2407 Update Kubernetes support issue templates and version marker for the default Kubernetes version
  .github/ISSUE_TEMPLATE/kubernetes-support.md
  .github/ISSUE_TEMPLATE/update-images.md
  Makefile
  pkg/cmd/config.go
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, dco-signoff: yes, docs/none

#2411 [release/v1.4] Add changelog for v1.4.10
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2410 [release/v1.5] Add changelog for v1.5.2
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2409 Add changelogs for October 2022 patch releases
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none

#2392 testv2: Use previous Terraform configs and KubeOne v1.5 in upgrade tests
  test/e2e/prow.yaml
  test/e2e/scenario_upgrade.go
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, kind/failing-test, dco-signoff: yes, docs/none

#2413 Use the new AWS account for the KubeOne E2E tests
  test/e2e/prow.yaml
  test/e2e/tests_definitions.go
Labels: release-note-none, lgtm, size/XL, approved, dco-signoff: yes, kind/chore, docs/none

#2419 Update etcd to 3.5.5 or use the version provided by kubeadm if it's newer
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm_test.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#2415 Use smaller instances for AWS E2E tests
  examples/terraform/aws/README.md
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  test/e2e/testdata/aws.tfvars
  test/e2e/testdata/aws_stable.tfvars
  test/e2e/tests_definitions.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none, backport-needed

#2422 Update Azure CCM to v1.25.3, v1.24.8, v1.23.21, v1.1.24, AzureDisk CSI driver to v1.23.0, and AzureFile CSI driver to v1.22.0
  addons/csi-azuredisk/csi-azuredisk-controller.yaml
  addons/csi-azuredisk/csi-azuredisk-node.yaml
  addons/csi-azuredisk/rbac-csi-azuredisk-controller.yaml
  addons/csi-azuredisk/rbac-csi-azuredisk-node.yaml
  addons/csi-azurefile/rbac-csi-azurefile-controller.yaml
  addons/csi-azurefile/rbac-csi-azurefile-node.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#2423 Revert using spot instances for AWS E2E tests
  test/e2e/testdata/aws.tfvars
  test/e2e/testdata/aws_stable.tfvars
Labels: release-note-none, size/S, lgtm, approved, kind/failing-test, dco-signoff: yes, docs/none

#2426 Update Hetzner CCM to v1.13.2
  addons/ccm-hetzner/ccm-hetzner.yaml
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2424 Migrate AWS EBS CSIDriver and use t3a.medium instances for non-Ubuntu AWS E2E tests
  pkg/addons/ensure.go
  pkg/addons/helpers.go
  test/e2e/testdata/aws_medium.tfvars
  test/e2e/testdata/aws_rhel.tfvars
  test/e2e/testdata/aws_small.tfvars
  test/e2e/testdata/aws_stable_medium.tfvars
  test/e2e/testdata/aws_stable_small.tfvars
  test/e2e/tests_definitions.go
Labels: lgtm, release-note, size/M, approved, kind/cleanup, dco-signoff: yes, docs/none

#2427 Update OpenStack CCM and CSI to v1.25.3, v1.24.5, v1.22.2
  addons/csi-openstack-cinder/snapshot-controller-rbac.yaml
  addons/csi-openstack-cinder/snapshot-controller.yaml
  addons/csi-openstack-cinder/snapshot-crds.yaml
  addons/csi-openstack-cinder/snapshot-webhook-rbac.yaml
  addons/csi-openstack-cinder/snapshot-webhook.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none, backport-needed

#2430 Refactor validation for csiConfig
  .golangci.yml
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, release-note, size/M, approved, kind/api-change, dco-signoff: yes, docs/none, backport-needed
