Repository kubermatic/kubeone, pull requests merged in 2022-11, with the labels that each got.

#2433 Rename generate-internal-groups Make target to update-codegen
  Makefile
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#2428 Helm addons
  docs/proposals/20221021-helm-addons.md
Labels: lgtm, release-note, size/L, approved, kind/design, dco-signoff: yes, docs/none

#2421 Machine Controller Addon: add metrics port 8080
  addons/machinecontroller/deployment-controller.yaml
Labels: size/XS, lgtm, release-note, approved, kind/cleanup, needs-ok-to-test, dco-signoff: yes, docs/none

#2434 Use context.WithTimeout in the E2E tests
  test/e2e/helpers.go
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#2429 Update vSphere CCM to v1.25.0, v1.24.2 v1.23.2 and CSI driver to v2.7.0
  addons/ccm-vsphere/ccm-vsphere.yaml
  addons/csi-vsphere/csi-snapshot-validatingwebhook.yaml
  addons/csi-vsphere/snapshot-controller-rbac.yaml
  addons/csi-vsphere/snapshot-controller.yaml
  addons/csi-vsphere/validatingwebhook.yaml
  addons/csi-vsphere/vsphere-csi-driver.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#2436 [release/v1.5] Use previous stable Terraform configs for upgrade tests
  test/e2e/prow.yaml
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore

#2437 [release/v1.5] Use the new AWS account for the KubeOne E2E tests
  test/e2e/prow.yaml
  test/e2e/tests_definitions.go
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes, kind/chore

#2438 [release/v1.4] Use the new AWS account for the KubeOne E2E tests
  .prow.yaml
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes, kind/chore

#2444 [release/v1.4] Update etcd to 3.5.5 or use the version provided by kubeadm if it's newer
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm_test.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2445 [release/v1.5] Update OpenStack CCM and CSI to v1.24.5 and v1.22.2
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes

#2448 Allow disabling IPv6 for Hubble UI
  addons/cni-cilium/README.md
  addons/cni-cilium/cilium.yaml
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none, backport-needed

#2450 [release/v1.5] Use smaller instances for AWS E2E tests and rename `generate-internal-groups` to `update-codegen`
  Makefile
  examples/terraform/aws/README.md
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  test/e2e/testdata/aws_medium.tfvars
  test/e2e/testdata/aws_rhel.tfvars
  test/e2e/testdata/aws_small.tfvars
  test/e2e/testdata/aws_stable_medium.tfvars
  test/e2e/testdata/aws_stable_small.tfvars
  test/e2e/tests_definitions.go
Labels: lgtm, release-note, size/L, approved, kind/cleanup, dco-signoff: yes

#2461 Update Golang to 1.19.3 (part 1)
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  hack/images/kubeone-e2e/Dockerfile
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#2462 [release/v1.5] Update Golang to 1.19.3
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore

#2463 Move the kubeone-e2e image to Quay
  .prow/postsubmits.yaml
  hack/images/kubeone-e2e/release.sh
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#2464 [release/v1.5] Move the kubeone-e2e image to Quay
  .prow/postsubmits.yaml
  hack/images/kubeone-e2e/release.sh
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore

#2465 [release/v1.4] Update Golang to v1.18.8 and use quay.io/kubermatic/kubeone-e2e image
  .prow.yaml
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
  test/e2e/testutil/testutil.go
  test/e2e/upgrade_test.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore

#2466 Use November's Kubernetes patch releases in the CI
  test/e2e/prow.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none

#2469 [release/v1.4] Add changelog for v1.4.11
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2467 Add changelogs for v1.5.3 and v1.4.11
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  hack/generate-changelog.sh
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#2468 [release/v1.5] Add changelog for v1.5.3
  CHANGELOG/CHANGELOG-1.5.md
  hack/generate-changelog.sh
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes

#2473 Update Nutanix CSI to v2.6.1 and use `helm template` for generating manifests
  addons/csi-nutanix/README.md
  addons/csi-nutanix/csi-driver.yaml
  addons/csi-nutanix/generate-values-csi-snapshot
  addons/csi-nutanix/generate-values-csi-storage
  addons/csi-nutanix/ntnx-csi-controller-deployment.yaml
  addons/csi-nutanix/ntnx-csi-node-ds.yaml
  addons/csi-nutanix/ntnx-csi-rbac.yaml
  addons/csi-nutanix/ntnx-secret.yaml
  addons/csi-nutanix/nutanix-csi-snapshot.yaml
  addons/csi-nutanix/nutanix-csi-storage.yaml
  addons/csi-nutanix/nutanix-webhook-certs.yaml
  addons/csi-nutanix/service-prometheus-csi.yaml
  addons/csi-nutanix/snapshot-controller-deployment.yaml
  addons/csi-nutanix/snapshot-controller-rbac.yaml
  addons/csi-nutanix/validating-deployment.yaml
  addons/csi-nutanix/validating-rbac.yaml
  addons/csi-nutanix/validating-webhook.yaml
  addons/csi-nutanix/volumesnapshotclasses.yaml
  addons/csi-nutanix/volumesnapshotcontents.yaml
  addons/csi-nutanix/volumesnapshots.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none

#2425 Update Equinix Metal CCM to v3.5.0
  addons/ccm-equinixmetal/ccm-equinixmetal.yaml
  pkg/templates/images/images.go
  test/e2e/tests_definitions.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#2478 Update Cilium to v1.12.3
  addons/cni-cilium/cilium.yaml
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2476 Add cluster-autoscaler v1.25.0
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2479 Update the issue template for updating images
  .github/ISSUE_TEMPLATE/update-images.md
Labels: kind/feature, release-note-none, size/S, lgtm, approved, dco-signoff: yes, docs/none

#2477 Update NodeLocalDNS to v1.22.13
  addons/nodelocaldns/nodelocaldns.yaml
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2481 Increase the minimum Kubernetes version to 1.23
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/kubeflags/flags.go
  pkg/state/context_test.go
  pkg/templates/images/images.go
  pkg/templates/kubeadm/v1beta3/kubeadm_test.go
  test/e2e/prow.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: lgtm, release-note, approved, size/XXL, kind/api-change, dco-signoff: yes, kind/deprecation, docs/provided

#2414 add dualstack support for AWS+Ubuntu+{Canal,Cilium}
  addons/calico-vxlan/calico-vxlan.yaml
  addons/cni-canal/canal.yaml
  addons/cni-cilium/cilium.yaml
  addons/machinecontroller/deployment-controller.yaml
  docs/api_reference/v1beta2.en.md
  examples/terraform/aws-dualstack/README.md
  examples/terraform/aws-dualstack/README.md.in
  examples/terraform/aws-dualstack/main.tf
  examples/terraform/aws-dualstack/output.tf
  examples/terraform/aws-dualstack/variables.tf
  examples/terraform/aws-dualstack/versions.tf
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/terraform/v1beta2/config.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/tbd

#2483 Fix NPE in probes
  pkg/tasks/probes.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2500 [release/v1.4] Update etcd to 3.5.6 and enable compact hash checks
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm_test.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#2501 Use `registry.k8s.io` instead of `k8s.gcr.io` for Kubernetes upstream images
  addons/csi-vmware-cloud-director/csi-controller.yaml
  addons/csi-vmware-cloud-director/csi-node.yaml
  hack/image-loader.sh
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/helpers_test.go
  pkg/cmd/config.go
  pkg/containerruntime/containerd_config_test.go
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-multi_registry_mirrors.golden
  pkg/scripts/kubeadm.go
  pkg/scripts/os_test.go
  pkg/tasks/kubeadm_config.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  test/e2e/cloudprovider.go
Labels: kind/feature, lgtm, size/L, approved, release-note-action-required, kind/api-change, dco-signoff: yes, docs/tbd

#2505 [release/v1.5] Use `registry.k8s.io` instead of `k8s.gcr.io` for Kubernetes upstream images
  addons/csi-vmware-cloud-director/csi-controller.yaml
  addons/csi-vmware-cloud-director/csi-node.yaml
  hack/image-loader.sh
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/helpers_test.go
  pkg/cmd/config.go
  pkg/containerruntime/containerd_config_test.go
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-multi_registry_mirrors.golden
  pkg/scripts/kubeadm.go
  pkg/scripts/os_test.go
  pkg/tasks/kubeadm_config.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  test/e2e/cloudprovider.go
Labels: kind/feature, lgtm, size/L, approved, release-note-action-required, kind/api-change, dco-signoff: yes

#2506 image-loader: fix an issue with mirroring the CoreDNS image
  hack/image-loader.sh
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, dco-signoff: yes, docs/none

#2509 image-loader: properly handle k8s versions that use registry.k8s.io
  hack/image-loader.sh
Labels: kind/bug, release-note-none, size/S, lgtm, approved, dco-signoff: yes, docs/none

#2508 [release/v1.4] Use `registry.k8s.io` instead of `k8s.gcr.io` for Kubernetes upstream images
  hack/image-loader.sh
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/helpers_test.go
  pkg/cmd/config.go
  pkg/containerruntime/containerd_config_test.go
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-multi_registry_mirrors.golden
  pkg/scripts/kubeadm.go
  pkg/scripts/os_test.go
  pkg/tasks/kubeadm_config.go
  pkg/templates/images/images.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/feature, lgtm, size/L, approved, release-note-action-required, kind/api-change, dco-signoff: yes

#2498 Automated helm deploys (A.K.A. helm addons)
  Makefile
  docs/api_reference/v1beta2.en.md
  go.mod
  go.sum
  hack/apidoc-gen/main.go
  hack/update-codegen.sh
  pkg/addons/ensure.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/kubeconfig/kubeconfig.go
  pkg/localhelm/helm3.go
  pkg/tasks/cni.go
  pkg/tasks/tasks.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/tbd

#2514 Update Developer Certificate of Origin
  DCO
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#2515 Fix helm deploy
  pkg/localhelm/helm3.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none
