Repository kubermatic/kubeone, pull requests merged in 2022-06, with the labels that each got.

#2075 Add MaxPods to KubeletConfig
  docs/api_reference/v1beta2.en.md
  examples/terraform/aws/output.tf
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/terraform/v1beta2/config.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2077 [release/v1.4] Replace MachineAnnotations with NodeAnnotations and add MachineObjectAnnotations
  docs/api_reference/v1beta2.en.md
  examples/terraform/aws/output.tf
  examples/terraform/nutanix/output.tf
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/templates/machinecontroller/machines.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2080 [release/v1.4] Add MaxPods to KubeletConfig and update machine-controller to v1.43.3
  docs/api_reference/v1beta2.en.md
  examples/terraform/aws/output.tf
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/templates/images/images.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/terraform/v1beta2/config.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2065 Generated E2E upgrade scenario
  Makefile
  go.mod
  testv2/e2e/helpers.go
  testv2/e2e/kubeone.go
  testv2/e2e/prow.yaml
  testv2/e2e/scenario_conformance.go
  testv2/e2e/scenario_install.go
  testv2/e2e/scenario_upgrade.go
  testv2/e2e/tests_test.go
  testv2/generator/main.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2081 Update Terraform integration for Azure with new fields
  examples/terraform/azure/output.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/terraform/v1beta1/config.go
  pkg/terraform/v1beta2/update.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2084 Update Azure osDiskSKU and dataDiskSKU example values
  examples/terraform/azure/output.tf
Labels: kind/feature, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#2085 [release/v1.4] Update Terraform integration for Azure with new fields
  examples/terraform/azure/output.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/terraform/v1beta1/config.go
  pkg/terraform/v1beta2/config.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2082 Migrate AzureDisk CSIDriver to set fsGroupPolicy
  addons/csi-azuredisk/csi-azuredisk-driver.yaml
  pkg/addons/ensure.go
  pkg/addons/helpers.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2068 Generated E2E conformance scenario
  go.mod
  go.sum
  test/e2e/testutil/exec.go
  test/e2e/testutil/exec_test.go
  testv2/e2e/helpers.go
  testv2/e2e/kubeone.go
  testv2/e2e/prow.yaml
  testv2/e2e/scenario_conformance.go
  testv2/e2e/scenario_install.go
  testv2/e2e/scenario_upgrade.go
  testv2/e2e/sonobuoy.go
  testv2/e2e/tests_test.go
  testv2/tests.yml
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes

#2059 Integration for VMware Cloud Director
  .golangci.yml
  README.md
  docs/api_reference/v1beta2.en.md
  examples/terraform/vcloud-director/main.tf
  examples/terraform/vcloud-director/output.tf
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/main.tf
  examples/terraform/vmware-cloud-director/output.tf
  examples/terraform/vmware-cloud-director/variables.tf
  examples/terraform/vmware-cloud-director/versions.tf
  go.mod
  go.sum
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/helpers.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/credentials/credentials.go
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/templates/machinecontroller/machines.go
  pkg/terraform/v1beta2/config.go
  pkg/terraform/v1beta2/update.go
  test/e2e/cloudprovider/cloudprovider.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes

#2089 Set rp_filter=0 for Cilium clusters
  pkg/scripts/funcs.go
  pkg/scripts/os.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/os_flatcar.go
  pkg/scripts/os_test.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#2093 Fix reference in README.md
  README.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes

#2097 Introduce new variable for specifying custom operating system profile
  examples/terraform/aws/README.md
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  examples/terraform/azure/README.md
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/output.tf
  examples/terraform/digitalocean/variables.tf
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/output.tf
  examples/terraform/equinixmetal/variables.tf
  examples/terraform/equinixmetal/versions.tf
  examples/terraform/gce/README.md
  examples/terraform/gce/output.tf
  examples/terraform/gce/variables.tf
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/main.tf
  examples/terraform/nutanix/output.tf
  examples/terraform/nutanix/variables.tf
  examples/terraform/nutanix/versions.tf
  examples/terraform/openstack/README.md
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/output.tf
  examples/terraform/vmware-cloud-director/variables.tf
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/outputs.tf
  examples/terraform/vsphere_flatcar/variables.tf
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, sig/osm

#2091 Download given kubeone version and use to provision the cluster
  .golangci.yml
  go.sum
  testv2/e2e/helpers.go
  testv2/e2e/kubeone.go
  testv2/e2e/scenario_conformance.go
  testv2/e2e/scenario_install.go
  testv2/e2e/scenario_upgrade.go
  testv2/e2e/sonobuoy.go
  testv2/e2e/terraform.go
  testv2/e2e/tests_definitions.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2103 Canal: disable preserveUnknownFields
  addons/cni-canal/canal.yaml
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2106 Disable node IPAM in Azure CCM
  addons/ccm-azure/ccm-azure.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2107 [release/v1.4] Disable node IPAM in Azure CCM
  addons/ccm-azure/ccm-azure.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2108 [release/v1.4] Set rp_filter=0 on all interfaces when Cilium is used
  pkg/scripts/funcs.go
  pkg/scripts/os.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/os_flatcar.go
  pkg/scripts/os_test.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#2111 Regenerate the terraform READMEs for each provider
  examples/terraform/aws/README.md
  examples/terraform/azure/README.md
  examples/terraform/digitalocean/README.md
  examples/terraform/equinixmetal/README.md
  examples/terraform/gce/README.md
  examples/terraform/hetzner/README.md
  examples/terraform/nutanix/README.md
  examples/terraform/openstack/README.md
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere_flatcar/README.md
Labels: release-note-none, lgtm, size/XL, approved, kind/documentation, dco-signoff: yes

#2115 Fix terraform consistent variables for machine deployment replicas
  examples/terraform/digitalocean/output.tf
  examples/terraform/digitalocean/variables.tf
  examples/terraform/equinixmetal/output.tf
  examples/terraform/equinixmetal/variables.tf
  examples/terraform/gce/output.tf
  examples/terraform/gce/variables.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere_flatcar/outputs.tf
  examples/terraform/vsphere_flatcar/variables.tf
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#2117 Automate generating terraform configs README files
  examples/terraform/aws/README.md.in
  examples/terraform/azure/README.md
  examples/terraform/azure/README.md.in
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/README.md.in
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/README.md.in
  examples/terraform/gce/README.md
  examples/terraform/gce/README.md.in
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/README.md.in
  examples/terraform/nutanix/README.md.in
  examples/terraform/openstack/README.md
  examples/terraform/openstack/README.md.in
  examples/terraform/vmware-cloud-director/README.md.in
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/README.md.in
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/README.md.in
  hack/update-codegen.sh
Labels: lgtm, release-note, size/L, approved, kind/documentation, dco-signoff: yes

#2112 Use --max-pods flag instead of kubelet config file
  pkg/tasks/common.go
  pkg/tasks/kubeadm_env.go
  pkg/tasks/upgrade_follower.go
  pkg/tasks/upgrade_leader.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2120 Add sonobuoy to the e2e image
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
Labels: release-note-none, size/S, lgtm, approved, kind/failing-test, dco-signoff: yes

#2122 Use kubeone-e2e:v0.1.23 is some postsubmits
  .prow/postsubmits.yaml
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/regression

#2095 Launch new generated E2E
  .prow/generated.yaml
  examples/terraform/azure/README.md
  examples/terraform/azure/main.tf
  examples/terraform/azure/versions.tf
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere/versions.tf
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/outputs.tf
  examples/terraform/vsphere_flatcar/variables.tf
  examples/terraform/vsphere_flatcar/versions.tf
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/runner/runner.go
  testv2/README.md
  testv2/e2e/helpers.go
  testv2/e2e/kubeone.go
  testv2/e2e/prow.yaml
  testv2/e2e/scenario_conformance.go
  testv2/e2e/scenario_install.go
  testv2/e2e/scenario_upgrade.go
  testv2/e2e/sonobuoy.go
  testv2/e2e/terraform.go
  testv2/e2e/testdata/containerd_calico.yaml
  testv2/e2e/testdata/containerd_simple.yaml
  testv2/e2e/testdata/containerd_weave.yaml
  testv2/e2e/testdata/docker_calico.yaml
  testv2/e2e/testdata/docker_simple.yaml
  testv2/e2e/testdata/docker_weave.yaml
  testv2/e2e/testdata/openstack_vars.tfvars
  testv2/e2e/testdata/vsphere_default.tfvars
  testv2/e2e/testdata/vsphere_flatcar.tfvars
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/go-test-e2e.sh
  testv2/tests.yml
Labels: kind/feature, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#2126 Update OSM to v0.5.0
  addons/operating-system-manager/cloud-init-settings.yaml
  addons/operating-system-manager/crd-operating-system-config.yaml
  addons/operating-system-manager/crd-operating-system-profile.yaml
  addons/operating-system-manager/rbac-controller.yaml
  go.mod
  go.sum
  pkg/templates/images/images.go
  testv2/e2e/prow.yaml
  testv2/e2e/testdata/operating_system_manager.yaml
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, sig/osm

#2127 Remove redundant CRD `clusters.cluster.k8s.io` for machine-controller
  addons/machinecontroller/crd-cluster.yaml
  addons/machinecontroller/rbac-controller.yaml
  pkg/templates/machinecontroller/helper.go
Labels: release-note-none, size/S, lgtm, approved, kind/cleanup, dco-signoff: yes

#2124 Add vsphere anit-affinity rule to terraform example
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/main.tf
  examples/terraform/vsphere_flatcar/variables.tf
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes
