Repository kubermatic/kubeone, pull requests merged in 2022-03, with the labels that each got.

#1876 Build and upload GOCACHE for arm64
  .prow.yaml
Labels: kind/feature, release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1877 Add APIVersion and Kind to manifest generated by config dump
  pkg/cmd/config-dump.go
Labels: kind/bug, release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1875 Build KubeOne container image
  .prow.yaml
  Dockerfile
  hack/ci/download-gocache.sh
  hack/ci/push-image.sh
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#1879 Run docker login when pushing images
  .prow.yaml
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1880 Update secret name for backup-restic addon to backup-restic-s3-credentials
  .gitignore
  addons/backups-restic/README.md
  addons/backups-restic/backups-restic.yaml
  go.mod
  go.sum
  pkg/kubeconfig/kubeconfig.go
  pkg/tasks/cni.go
Labels: lgtm, size/L, approved, kind/cleanup, release-note-action-required, dco-signoff: yes

#1884 Use a pointer to KubeOneCluster in AssetConfig defaulting
  pkg/apis/kubeone/helpers.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#1887 Approve pending CSRs when upgrading nodes
  pkg/tasks/upgrade_follower.go
  pkg/tasks/upgrade_leader.go
  pkg/tasks/upgrade_static_workers.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#1882 Error handling refactoring
  pkg/addons/applier.go
  pkg/addons/helpers.go
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/v1beta1/helpers.go
  pkg/apis/kubeone/v1beta2/helpers.go
  pkg/clusterstatus/etcdstatus/etcdstatus.go
  pkg/cmd/addons.go
  pkg/cmd/apply.go
  pkg/cmd/config-dump.go
  pkg/cmd/config-images.go
  pkg/cmd/config.go
  pkg/cmd/install.go
  pkg/cmd/kubeconfig.go
  pkg/cmd/root.go
  pkg/cmd/shared.go
  pkg/cmd/status.go
  pkg/cmd/upgrade.go
  pkg/cmd/version.go
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
  pkg/etcdutil/etcd.go
  pkg/fail/errors.go
  pkg/fail/exitcodes.go
  pkg/fail/helpers.go
  pkg/kubeconfig/kubeconfig.go
  pkg/ssh/connection.go
  pkg/ssh/connector.go
  pkg/ssh/sshtunnel/etcd.go
  pkg/state/context.go
  pkg/tasks/probes.go
  pkg/terraform/v1beta1/config.go
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes

#1894 Fix CSR approving issue for existing nodes with already approved and GCed CSRs
  pkg/tasks/certs.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#1898 Even more error handling with new error types
  pkg/fail/helpers.go
  pkg/nodeutils/drain.go
  pkg/scripts/ccm_csi_migration.go
  pkg/scripts/configs.go
  pkg/scripts/kubeadm.go
  pkg/scripts/node.go
  pkg/scripts/os.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/os_flatcar.go
  pkg/scripts/proxy.go
  pkg/state/task.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/certs.go
  pkg/tasks/cni.go
  pkg/tasks/common.go
  pkg/tasks/containerd.go
  pkg/tasks/controlplane.go
  pkg/tasks/coredns.go
  pkg/tasks/encryption_providers.go
  pkg/tasks/etcd.go
  pkg/tasks/kubeadm_config.go
  pkg/tasks/kubeadm_upgrade.go
  pkg/tasks/kubeconfig.go
  pkg/tasks/kubernetes_binaries.go
  pkg/tasks/machine_deployments.go
  pkg/tasks/nodes.go
  pkg/tasks/preflight_checks.go
  pkg/tasks/preflight_checks_test.go
  pkg/tasks/prerequisites.go
  pkg/tasks/probes.go
  pkg/tasks/reset.go
  pkg/tasks/static_wokers.go
  pkg/tasks/task.go
  pkg/tasks/tasks.go
  pkg/tasks/upgrade_follower.go
  pkg/tasks/upgrade_leader.go
  pkg/tasks/upgrade_static_workers.go
  pkg/tasks/util.go
Labels: kind/feature, release-note-none, lgtm, size/XL, approved, dco-signoff: yes

#1900 Ensure old machine-controller MutatingWebhookConfiguration is deleted
  pkg/templates/machinecontroller/helper.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#1904 Mount /usr/share/ca-certificates to the OpenStack CCM pod
  addons/ccm-openstack/ccm-openstack.yaml
  examples/terraform/openstack/gobetween.sh
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#1907 Enable the etcd corruption checks for etcd v3.5
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes
