Repository kubermatic/kubeone, pull requests merged in 2022-04, with the labels that each got.

#1915 Add changelog for the v1.4.1 release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#1918 [release/v1.4] Add (re-)rendering container runtime config to flatcar upgrades
  CHANGELOG.md
  pkg/scripts/os_flatcar.go
  pkg/scripts/os_test.go
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlFlatcar.golden
  pkg/tasks/kubernetes_binaries.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#1921 Update the release date and add Flatcar change
  CHANGELOG.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes

#1923 Use Infof instead of Info for correct logging format
  pkg/tasks/certs.go
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#1906 PDB Objects for all addons Deployments
  addons/ccm-azure/poddisruptionbudget.yaml
  addons/ccm-digitalocean/poddisruptionbudget.yaml
  addons/ccm-equinixmetal/poddisruptionbudget.yaml
  addons/ccm-hetzner/poddisruptionbudget.yaml
  addons/cluster-autoscaler/poddisruptionbudget.yaml
  addons/cni-cilium/poddisruptionbudgets.yaml
  addons/csi-azuredisk/csi-azuredisk-controller.yaml
  addons/csi-azuredisk/csi-snapshot-controller.yaml
  addons/csi-azuredisk/poddisruptionbudgets.yaml
  addons/csi-azurefile/csi-azurefile-controller.yaml
  addons/csi-azurefile/csi-snapshot-controller.yaml
  addons/csi-azurefile/poddisruptionbudgets.yaml
  addons/csi-digitalocean/poddisruptionbudgets.yaml
  addons/csi-nutanix/poddisruptionbudget.yaml
  addons/csi-vsphere/poddisruptionbudgets.yaml
  addons/csi-vsphere/validatingwebhook.yaml
  addons/csi-vsphere/vsphere-csi-driver.yaml
  addons/machinecontroller/deployment-controller.yaml
  addons/machinecontroller/poddisruptionbudgets.yaml
  addons/machinecontroller/webhook.yaml
  addons/metrics-server/poddisruptionbudget.yaml
  addons/operating-system-manager/deployment-controller.yaml
  addons/operating-system-manager/poddisruptionbudgets.yaml
  addons/operating-system-manager/webhook.yaml
  addons/unattended-upgrades/fluo.yaml
  addons/unattended-upgrades/poddisruptionbudget.yaml
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#1925 Add .Params.RequestsCPU reading to cni-canal addon
  addons/cni-canal/canal.yaml
  pkg/addons/manifest.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#1903 Update OSM to v0.4.2
  addons/operating-system-manager/crd-operating-system-config.yaml
  addons/operating-system-manager/crd-operating-system-profile.yaml
  addons/operating-system-manager/webhook.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#1927 Show the "Ensure MachineDeployments" message only when provisioning a cluster for the first time
  pkg/cmd/apply.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#1929 Add changelog for the v1.3.4 release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#1934 [release/v1.3] Add changelog for the v1.3.4 release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#1930 Fixes containerd upgrade on deb based distros
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#1932 Fix the flaky TestFillTwoNewRootKeys unit test
  pkg/yamled/document_test.go
  pkg/yamled/testcases/fill-two-new-root-keys.yaml
Labels: release-note-none, size/S, lgtm, approved, kind/cleanup, kind/failing-test, dco-signoff: yes

#1924 Update machine-controller to v1.46.0
  .prow.yaml
  examples/terraform/aws/README.md
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  go.mod
  go.sum
  pkg/templates/images/images.go
  pkg/templates/machinecontroller/cloudprovider_specs.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#1896 Domain is not required when using application credentials
  .golangci.yml
  pkg/credentials/credentials.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#1938 [release/v1.4] Domain is not required when using application credentials
  .golangci.yml
  pkg/credentials/credentials.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes

#1941 Escape docker/containerd versions to avoid wildcard matching
  pkg/scripts/funcs.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#1939 Avoid creating and validating MC credentials when MC is disabled
  .golangci.yml
  go.mod
  go.sum
  pkg/addons/applier.go
  pkg/cmd/shared.go
  pkg/credentials/secret.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#1944 Restart kubelet after containerd
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/tasks/preflight_checks.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#1942 Allow having no OIDC GroupsPrefix
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/features/oidc.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#1949 install.sh: Get latest version sorted by semver
  install.sh
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#1950 Don't ignore clientset error when resetting cluster
  pkg/cmd/reset.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#1951 Use etcd v3.5.3 for Kubernetes 1.22+
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#1978 Move ProwJobs to .prow directory
  .prow.yaml
  .prow/1.20.yaml
  .prow/1.21.yaml
  .prow/1.22.yaml
  .prow/1.23.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
Labels: release-note-none, lgtm, approved, size/XXL, kind/cleanup, dco-signoff: yes

#1980 Make upgrade tests optional
  .prow/1.20.yaml
  .prow/1.21.yaml
  .prow/1.22.yaml
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes

#1979 Upgrade machine-controller to v1.47.0
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, kind/cleanup, dco-signoff: yes

#1982 Upgrade machine-controller to v1.43.1
  pkg/templates/images/images.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#1986 Bump flannel image to v0.15.1
  pkg/templates/images/images.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#1994 Add changelog for v1.4.2 release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#1996 Add CHANGELOG for v1.4.2 release
  CHANGELOG.md
  hack/generate-changelog.sh
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#1999 [release/v1.3] Add changelog for v1.3.5 release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2001 Update machine-controller to v1.43.2
  pkg/templates/images/images.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2000 Add changelog for release v1.4.2
  CHANGELOG.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes

#2003 Refactor changelog for release v1.4.2
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2004 [release/v1.4.2] Changelog for release v1.4.2
  CHANGELOG.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes

#2002 Replace issue forms with templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes

#2009 Update the KubeOne build image to Go 1.18.1 and remove Kubernetes 1.20 jobs and binaries
  .prow/1.20.yaml
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: kind/feature, release-note-none, lgtm, size/L, approved, dco-signoff: yes
