Repository kubermatic/kubeone, pull requests merged in 2022-01, with the labels that each got.

#1713 update cluster-autoscaler addon to match upstream example
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: release-note-none, size/S, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#1715 Add changelog for the v1.4.0-beta.0 release
  CHANGELOG.md
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1712 Remove centos from GCE Terraform example
  examples/terraform/gce/variables.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1717 Add support for different credentials for machine-controller and CCM
  addons/ccm-digitalocean/ccm-digitalocean.yaml
  addons/ccm-equinixmetal/ccm-equinixmetal.yaml
  addons/ccm-hetzner/ccm-hetzner.yaml
  addons/csi-hetzner/hcloud-csi.yml
  pkg/addons/applier.go
  pkg/cmd/apply.go
  pkg/cmd/install.go
  pkg/cmd/migrate.go
  pkg/cmd/shared.go
  pkg/cmd/upgrade.go
  pkg/credentials/credentials.go
  pkg/credentials/secret.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1718 Remove cloud-provider-credentials Secret and prefix credentials Secret created by KubeOne
  addons/ccm-digitalocean/ccm-digitalocean.yaml
  addons/ccm-hetzner/ccm-hetzner.yaml
  addons/csi-hetzner/hcloud-csi.yml
  pkg/credentials/secret.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1723 Add Terraform configs for Nutanix
  examples/terraform/equinixmetal/README.md
  examples/terraform/hetzner/README.md
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/cloud-config.tftpl
  examples/terraform/nutanix/etc_gobetween.tpl
  examples/terraform/nutanix/gobetween.sh
  examples/terraform/nutanix/main.tf
  examples/terraform/nutanix/output.tf
  examples/terraform/nutanix/variables.tf
  examples/terraform/nutanix/versions.tf
  examples/terraform/openstack/README.md
  examples/terraform/vsphere/README.md
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes

#1725 Add support and Terraform integration for Nutanix
  docs/api_reference/v1beta2.en.md
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/main.tf
  examples/terraform/nutanix/output.tf
  examples/terraform/nutanix/variables.tf
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/helpers.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/credentials/credentials.go
  pkg/templates/images/images.go
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/terraform/v1beta2/config.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1724 Registry credentials configuration
  addons/machinecontroller/machine-controller.yaml
  docs/api_reference/v1beta2.en.md
  go.mod
  go.sum
  pkg/addons/applier.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/containerruntime/containerd_config.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcat.golden
  pkg/scripts/testdata/TestMigrateToContainerd-insecureRegistry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1733 Add the Nutanix CSI driver
  addons/ccm-azure/ccm-azure.yaml
  addons/csi-azuredisk/csi-snapshot-controller.yaml
  addons/csi-azurefile/csi-snapshot-controller.yaml
  addons/csi-nutanix/csi-driver.yaml
  addons/csi-nutanix/ntnx-csi-node-ds.yaml
  addons/csi-nutanix/ntnx-csi-provisioner-sts.yaml
  addons/csi-nutanix/ntnx-csi-rbac.yaml
  addons/csi-nutanix/ntnx-secret.yaml
  addons/csi-nutanix/service-prometheus-csi.yaml
  addons/default-storage-class/storage-class.yaml
  examples/terraform/nutanix/main.tf
  examples/terraform/nutanix/variables.tf
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/credentials/credentials.go
  pkg/scripts/os.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/os_test.go
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes

#1734 Add Nutanix CSI snapshot controller addon
  addons/csi-nutanix/snapshot-controller-rbac.yaml
  addons/csi-nutanix/snapshot-controller-sts.yaml
  addons/csi-nutanix/validating-deployment.yaml
  addons/csi-nutanix/validating-webhook.yaml
  addons/csi-nutanix/volumesnapshotclasses.yaml
  addons/csi-nutanix/volumesnapshotcontents.yaml
  addons/csi-nutanix/volumesnapshots.yaml
  pkg/addons/applier.go
  pkg/apis/kubeone/config/config.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes

#1736 Add changelog for the v1.4.0-beta.1 release
  CHANGELOG.md
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1737 Add template function "required" for addons
  pkg/addons/manifest.go
  pkg/scripts/render.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1738 Add Nutanix as a supported provider to the README
  README.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1739 Source csiConfig from the credentials file if present
  pkg/apis/kubeone/config/config.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1743 Fix containerd migration on non-flatcar OS
  pkg/scripts/os.go
  pkg/scripts/os_test.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcar.golden
  pkg/scripts/testdata/TestMigrateToContainerd-insecureRegistry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-simple.golden
  pkg/tasks/containerd.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1745 Fetch containerd auth config from the credentials file
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/config/config_test.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1747 Update logo and add a dark theme logo
  README.md
  docs/img/kubeone-logo-text-dark.png
  docs/img/kubeone-logo-text.png
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1746 Force static manifests render on upgrade
  pkg/scripts/kubeadm.go
  pkg/scripts/kubeadm_test.go
  pkg/scripts/os.go
  pkg/scripts/proxy.go
  pkg/scripts/proxy_test.go
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmUpgrade-leader.golden
  pkg/scripts/testdata/TestKubeadmUpgrade-v1beta2.golden
  pkg/scripts/testdata/TestKubeadmUpgradeLeader-v1beta2.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcar.golden
  pkg/scripts/testdata/TestMigrateToContainerd-insecureRegistry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-simple.golden
  pkg/scripts/testdata/TestTestDaemonsProxy.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/tasks/kubeadm_upgrade.go
  pkg/tasks/prerequisites.go
  pkg/tasks/upgrade_follower.go
  pkg/tasks/upgrade_leader.go
  pkg/tasks/upgrade_static_workers.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1751 Update images in order to support Kubernetes 1.23
  addons/csi-azuredisk/csi-azuredisk-controller.yaml
  addons/csi-azuredisk/csi-azuredisk-node.yaml
  addons/csi-azurefile/csi-azurefile-controller.yaml
  addons/csi-azurefile/csi-azurefile-node.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1754 Add DigitalOcean CSI driver
  addons/csi-digitalocean/crds.yaml
  addons/csi-digitalocean/driver.yaml
  addons/csi-digitalocean/snapshot-controller.yaml
  addons/csi-digitalocean/snapshot-validation-webhook.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#1753 Update DigitalOcean and Hetzner CCMs
  addons/ccm-digitalocean/ccm-digitalocean.yaml
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1755 Add all images to the update images issue template
  .github/ISSUE_TEMPLATE/update-images.md
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1750 Generate and approve CSRs for conntrol-plane and static workers nodes
  .prow.yaml
  pkg/scripts/render.go
  pkg/tasks/certs.go
  pkg/tasks/controlplane.go
  pkg/tasks/prerequisites.go
  pkg/tasks/probes.go
  pkg/tasks/static_wokers.go
  pkg/tasks/tasks.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1756 Ensure unattended-upgrades in dpkg is active
  addons/unattended-upgrades/apt.yaml
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1758 Small CSR tweaks
  pkg/tasks/certs.go
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1644 feat: add container logs max size to the kubeone API
  docs/api_reference/v1beta1.en.md
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/containerruntime/docker_config.go
  pkg/containerruntime/docker_config_test.go
  pkg/scripts/os_test.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1748 Addon for operating system manager
  .golangci.yml
  addons/machinecontroller/cloud-init-settings.yaml
  addons/machinecontroller/crd-cluster.yaml
  addons/machinecontroller/crd-machine-deployment.yaml
  addons/machinecontroller/crd-machine-set.yaml
  addons/machinecontroller/crd-machine.yaml
  addons/machinecontroller/deployment-controller.yaml
  addons/machinecontroller/machine-controller.yaml
  addons/machinecontroller/rbac-controller.yaml
  addons/machinecontroller/rbac-webhook.yaml
  addons/machinecontroller/webhook.yaml
  addons/operating-system-manager/crd-operating-system-config.yaml
  addons/operating-system-manager/crd-operating-system-profile.yaml
  addons/operating-system-manager/deployment-controller.yaml
  addons/operating-system-manager/rbac-controller.yaml
  addons/operating-system-manager/rbac-webhook.yaml
  addons/operating-system-manager/webhook.yaml
  go.mod
  go.sum
  pkg/addons/applier.go
  pkg/apis/kubeone/helpers.go
  pkg/cmd/apply.go
  pkg/credentials/credentials.go
  pkg/credentials/secret.go
  pkg/tasks/tasks.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/machinecontroller/helper.go
  pkg/templates/operatingsystemmanager/helper.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#1759 Support for container log max files in logging config
  docs/api_reference/v1beta2.en.md
  hack/update-apidocs.sh
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/cmd/config.go
  pkg/containerruntime/consts.go
  pkg/containerruntime/docker_config.go
  pkg/containerruntime/docker_config_test.go
  pkg/scripts/os_test.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1761 Propagate logging config to machines
  pkg/templates/machinecontroller/machines.go
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1762 Add placement_group to Hetzner terraform
  examples/terraform/hetzner/main.tf
Labels: release-note-none, size/S, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#1752 replace hubble static certs with CronJob generation
  addons/cni-cilium/cilium.yaml
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#1765 Add changelog for the v1.4.0-rc.0 release
  CHANGELOG.md
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes
