Repository kubermatic/kubeone, pull requests merged in 2022-08, with the labels that each got.

#2211 Add changelog for the v1.5.0-beta.0 release and split existing CHANGELOGs into multiple files
  CHANGELOG.md
  CHANGELOG/CHANGELOG-0.x.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/README.md
Labels: release-note-none, lgtm, approved, size/XXL, kind/documentation, dco-signoff: yes

#2214 Rollout pods if credentials are changed
  CHANGELOG/CHANGELOG-1.5.md
  addons/ccm-digitalocean/ccm-digitalocean.yaml
  addons/ccm-equinixmetal/ccm-equinixmetal.yaml
  addons/ccm-hetzner/ccm-hetzner.yaml
  addons/ccm-openstack/ccm-openstack.yaml
  addons/ccm-vsphere/ccm-vsphere.yaml
  addons/csi-digitalocean/driver.yaml
  addons/csi-gcp-compute-persistent/controller.yaml
  addons/csi-hetzner/hcloud-csi.yml
  addons/csi-nutanix/ntnx-csi-controller-deployment.yaml
  addons/csi-nutanix/ntnx-csi-node-ds.yaml
  addons/csi-vsphere/validatingwebhook.yaml
  addons/csi-vsphere/vsphere-csi-driver.yaml
  addons/machinecontroller/deployment-controller.yaml
  addons/machinecontroller/webhook.yaml
  addons/operating-system-manager/deployment-controller.yaml
  addons/operating-system-manager/webhook.yaml
  pkg/addons/applier.go
  pkg/certificate/cabundle/ca-bundle.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#2216 [release/v1.4] Rollout pods if credentials are changed
  .golangci.yml
  addons/ccm-digitalocean/ccm-digitalocean.yaml
  addons/ccm-equinixmetal/ccm-equinixmetal.yaml
  addons/ccm-hetzner/ccm-hetzner.yaml
  addons/ccm-openstack/ccm-openstack.yaml
  addons/ccm-vsphere/ccm-vsphere.yaml
  addons/csi-digitalocean/driver.yaml
  addons/csi-gcp-compute-persistent/controller.yaml
  addons/csi-hetzner/hcloud-csi.yml
  addons/csi-nutanix/ntnx-csi-node-ds.yaml
  addons/csi-nutanix/ntnx-csi-provisioner-sts.yaml
  addons/csi-vsphere/validatingwebhook.yaml
  addons/csi-vsphere/vsphere-csi-driver.yaml
  addons/machinecontroller/deployment-controller.yaml
  addons/machinecontroller/webhook.yaml
  addons/operating-system-manager/deployment-controller.yaml
  addons/operating-system-manager/webhook.yaml
  pkg/addons/applier.go
  pkg/certificate/cabundle/ca-bundle.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#2217 Add default VolumeSnapshotClass for OpenStack Cinder CSI
  CHANGELOG/CHANGELOG-1.5.md
  addons/default-storage-class/storage-class.yaml
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes

#2218 [release/v1.4] Add missing snapshot controller and webhook for OpenStack Cinder CSI
  .golangci.yml
  addons/csi-openstack-cinder/controllerplugin-rbac.yaml
  addons/csi-openstack-cinder/controllerplugin.yaml
  addons/csi-openstack-cinder/nodeplugin.yaml
  addons/csi-openstack-cinder/snapshot-controller-rbac.yaml
  addons/csi-openstack-cinder/snapshot-controller.yaml
  addons/csi-openstack-cinder/snapshot-crds.yaml
  addons/csi-openstack-cinder/snapshot-webhook.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/addons/applier.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2220 Update Cilium to v1.12.0
  addons/cni-cilium/cilium.yaml
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes

#2224 Add Cilium 1.12.0 update to the changelog
  CHANGELOG/CHANGELOG-1.5.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes

#2228 [release/v1.4] Update containerd to v1.5
  pkg/scripts/funcs.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2230 [release/v1.4] Add changelog for v1.4.6
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2229 Add changelog for v1.4.6
  CHANGELOG/CHANGELOG-1.4.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2225 Update kubeone-e2e image to Go 1.19.0
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
Labels: kind/feature, release-note-none, size/S, lgtm, approved, dco-signoff: yes

#2226 Update Go to 1.19.0
  .prow/1.21.yaml
  .prow/1.22.yaml
  .prow/1.23.yaml
  .prow/1.24.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  CHANGELOG/CHANGELOG-1.5.md
  Dockerfile
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
  testv2/e2e/helpers.go
  testv2/e2e/prow.yaml
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes

#2231 Lower exponential backoff times
  pkg/tasks/task.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2234 Add lower exponential backoff times change to the changelog and update v1.5.0-beta.0 release date to 2022-08-04
  CHANGELOG/CHANGELOG-1.5.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes

#2212 Testing CSI/CCM migration
  Makefile
  pkg/apis/kubeone/helpers.go
  pkg/state/context.go
  pkg/state/context_test.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/probes.go
  testv2/e2e/helpers.go
  testv2/e2e/kubeone.go
  testv2/e2e/prow.yaml
  testv2/e2e/scenario_conformance.go
  testv2/e2e/scenario_install.go
  testv2/e2e/scenario_migrate_csi_ccm.go
  testv2/e2e/scenario_upgrade.go
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/tests.yml
Labels: lgtm, release-note, approved, size/XXL, kind/cleanup, dco-signoff: yes

#2237 testv2: Add additional test scenarios
  examples/terraform/equinixmetal/variables.tf
  testv2/e2e/prow.yaml
  testv2/e2e/testdata/legacy_machine_controller_containerd.yaml
  testv2/e2e/testdata/legacy_machine_controller_containerd_external.yaml
  testv2/e2e/testdata/legacy_machine_controller_docker.yaml
  testv2/e2e/testdata/legacy_machine_controller_docker_external.yaml
  testv2/e2e/testdata/openstack_centos.tfvars
  testv2/e2e/testdata/openstack_flatcar.tfvars
  testv2/e2e/testdata/openstack_rhel.tfvars
  testv2/e2e/testdata/openstack_rockylinux.tfvars
  testv2/e2e/testdata/openstack_ubuntu.tfvars
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/tests.yml
Labels: kind/feature, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#2258 Mark `install` and `upgrade` subcommands deprecated
  pkg/cmd/install.go
  pkg/cmd/upgrade.go
Labels: size/S, lgtm, approved, kind/cleanup, release-note-action-required, dco-signoff: yes, kind/deprecation

#2259 Unified PR template update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes

#2177 testv2: Port cloud provider tests
  testv2/e2e/cloudprovider.go
  testv2/e2e/helpers.go
  testv2/e2e/scenario_conformance.go
  testv2/e2e/scenario_install.go
  testv2/e2e/scenario_migrate_csi_ccm.go
  testv2/e2e/scenario_upgrade.go
  testv2/e2e/tests_definitions.go
Labels: kind/feature, release-note-none, lgtm, size/L, approved, dco-signoff: yes

#2260 testv2: Replace nginx with echoserver
  testv2/e2e/cloudprovider.go
Labels: release-note-none, size/S, lgtm, approved, kind/cleanup, dco-signoff: yes

#2261 testv2/upgrade: Wait for nodes to become ready before upgrading
  testv2/e2e/scenario_upgrade.go
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes

#2264 Rollback to CentOS 7 in Terraform configs for AWS
  examples/terraform/aws/README.md
  examples/terraform/aws/variables.tf
  testv2/e2e/tests_definitions.go
Labels: size/S, lgtm, release-note, approved, kind/cleanup, dco-signoff: yes

#2263 testv2: Fix mode name for Sonobuoy conformance tests
  testv2/e2e/sonobuoy.go
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#2266 Extend Terraform configs for Azure with more operating systems
  examples/terraform/azure/README.md
  examples/terraform/azure/main.tf
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2267 Fix rocky linux OS detection
  pkg/tasks/util.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2269 Remove hcloud-volumes StorageClass from csi-hcloud addon
  addons/csi-hetzner/hcloud-csi.yml
  testv2/e2e/testdata/legacy_machine_controller_containerd.yaml
  testv2/e2e/testdata/legacy_machine_controller_containerd_external.yaml
  testv2/e2e/testdata/legacy_machine_controller_docker.yaml
  testv2/e2e/testdata/legacy_machine_controller_docker_external.yaml
Labels: kind/bug, lgtm, size/M, approved, release-note-action-required, dco-signoff: yes

#2276 Make provisioningUtility configurable in Terraform configs for AWS
  examples/terraform/aws/README.md
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  testv2/e2e/prow.yaml
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/tests.yml
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, dco-signoff: yes

#2279 testv2: Rollout MachineDeployments on upgrade
  testv2/e2e/cloudprovider.go
  testv2/e2e/helpers.go
  testv2/e2e/kubeone.go
  testv2/e2e/scenario_upgrade.go
  testv2/e2e/sonobuoy.go
Labels: kind/bug, release-note-none, lgtm, size/M, approved, dco-signoff: yes

#2282 Enable nf_conntrack module by default
  pkg/scripts/funcs.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.23.9.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#2285 Remove defaulting for provisioning utility in AWS configs
  examples/terraform/aws/README.md
  examples/terraform/aws/variables.tf
  testv2/e2e/tests_definitions.go
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-action-required, dco-signoff: yes

#2286 [release/v1.4] Remove defaulting for provisioning utility in AWS configs
  examples/terraform/aws/output.tf
Labels: size/XS, lgtm, release-note, approved, kind/cleanup, dco-signoff: yes

#2284 Add changelog for v1.4.7
  CHANGELOG/CHANGELOG-1.4.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2288 OSM: Add missing RBAC for updating secrets in cloud-init-settings namespace
  addons/operating-system-manager/rbac-controller.yaml
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#2287 VCD: Fix for worker machine disk size
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/output.tf
  examples/terraform/vmware-cloud-director/variables.tf
Labels: kind/bug, release-note-none, size/S, lgtm, approved, dco-signoff: yes

#2289 testv2: Extend logic for rolling-out MachineDeployments
  testv2/e2e/helpers.go
  testv2/e2e/scenario_upgrade.go
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, dco-signoff: yes

#2291 testv2: Add E2E tests for non-Ubuntu operating systems on Azure
  testv2/e2e/prow.yaml
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, kind/cleanup, dco-signoff: yes

#2290 Add safeguards for master node-role and cloud-init provisioningUtility
  pkg/tasks/probes.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2292 Move vmware csi driver to vmware-system-csi namespace
  addons/csi-vsphere/csi-snapshot-validatingwebhook.yaml
  addons/csi-vsphere/poddisruptionbudgets.yaml
  addons/csi-vsphere/snapshot-controller-rbac.yaml
  addons/csi-vsphere/snapshot-controller.yaml
  addons/csi-vsphere/validatingwebhook.yaml
  addons/csi-vsphere/vsphere-csi-driver.yaml
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2293 testv2/upgrade: Fix MachineDeployment updating and rolling out
  testv2/e2e/scenario_upgrade.go
Labels: kind/bug, release-note-none, size/S, lgtm, approved, dco-signoff: yes

#2294 testv2: Clean PVCs when cleaning up the cloud provider tests
  testv2/e2e/cloudprovider.go
Labels: kind/bug, release-note-none, lgtm, size/M, approved, dco-signoff: yes

#2298 Add Plan block for the control plane VMs to the example Terraform configs for Azure
  examples/terraform/azure/README.md
  examples/terraform/azure/main.tf
  examples/terraform/azure/variables.tf
  testv2/go-test-e2e.sh
Labels: kind/bug, release-note-none, lgtm, size/L, approved, dco-signoff: yes

#2299 Mount /etc/pki to the OpenStack CCM container and minor test fixes
  addons/ccm-openstack/ccm-openstack.yaml
  examples/terraform/openstack/output.tf
  testv2/e2e/testdata/openstack_centos.tfvars
  testv2/e2e/testdata/openstack_flatcar.tfvars
  testv2/e2e/testdata/openstack_rhel.tfvars
  testv2/e2e/testdata/openstack_rockylinux.tfvars
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2301 Set iptables backend to NFT for Canal and Calico VXLAN on Flatcar clusters
  addons/calico-vxlan/calico-vxlan.yaml
  addons/cni-canal/canal.yaml
  pkg/addons/applier.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#2302 Fix Flatcar: mkdir /opt/bin before untar anything in it
  pkg/scripts/os_flatcar.go
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2303 [release/v1.4] Mount /etc/pki to the OpenStack CCM container
  addons/ccm-openstack/ccm-openstack.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2304 Build stable KubeOne binary instead of downloading it from GitHub
  testv2/e2e/helpers.go
  testv2/e2e/prow.yaml
  testv2/e2e/scenario_install.go
  testv2/e2e/scenario_upgrade.go
Labels: release-note-none, lgtm, approved, size/XXL, kind/cleanup, dco-signoff: yes

#2305 [release/v1.4] Fix Flatcar: mkdir /opt/bin before untar anything in it
  pkg/scripts/os_flatcar.go
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2306 Extend Terraform configs for Azure to automatically subscribe to RHSM
  examples/terraform/azure/README.md
  examples/terraform/azure/cloud-config.tftpl
  examples/terraform/azure/main.tf
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  testv2/e2e/prow.yaml
  testv2/e2e/tests_definitions.go
  testv2/go-test-e2e.sh
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#2308 Mount /etc/pki to the Azure CCM container
  addons/ccm-azure/ccm-azure.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2311 Update OSM to v1.0.0 and MC to v1.54.0
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes

#2312 Add changelog for the v1.5.0-rc.0 release
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes

#2314 Refresh links used in KubeOne CLI and docs
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.5.md
  README.md
  addons/calico-vxlan/README.md
  docs/proposals/20200224-apply.md
  docs/release_process.md
  examples/terraform/aws/README.md
  examples/terraform/aws/README.md.in
  examples/terraform/azure/README.md
  examples/terraform/azure/README.md.in
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/README.md.in
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/README.md.in
  examples/terraform/gce/README.md
  examples/terraform/gce/README.md.in
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/README.md.in
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/README.md.in
  examples/terraform/openstack/README.md
  examples/terraform/openstack/README.md.in
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/README.md.in
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/README.md.in
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/README.md.in
  pkg/cmd/config.go
  pkg/cmd/migrate.go
  pkg/tasks/machine_deployments.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes

#2315 [release/v1.5] Point docs.kubermatic.com links to the v1.5 docs
  .github/ISSUE_TEMPLATE/kubernetes-support.md
  README.md
  addons/README.md
  addons/calico-vxlan/README.md
  addons/cluster-autoscaler/README.md
  docs/README.md
  examples/terraform/aws/README.md
  examples/terraform/aws/README.md.in
  examples/terraform/azure/README.md
  examples/terraform/azure/README.md.in
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/README.md.in
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/README.md.in
  examples/terraform/gce/README.md
  examples/terraform/gce/README.md.in
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/README.md.in
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/README.md.in
  examples/terraform/openstack/README.md
  examples/terraform/openstack/README.md.in
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/README.md.in
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/README.md.in
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/README.md.in
  pkg/cmd/config.go
  pkg/cmd/migrate.go
  pkg/tasks/machine_deployments.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes

#2316 Add Calico VXLAN known issue to the 1.5.0-rc.0 changelog
  CHANGELOG/CHANGELOG-1.5.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes

#2326 CCM/CSI migration: merge steps for manifests and kubelet config updates
  pkg/scripts/ccm_csi_migration.go
  pkg/scripts/ccm_csi_migration_test.go
  pkg/scripts/testdata/TestCCMMigrationRegenerateControlPlaneConfigs-not-verbose.golden
  pkg/scripts/testdata/TestCCMMigrationRegenerateControlPlaneConfigs-verbose.golden
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/tasks.go
Labels: kind/bug, lgtm, release-note, size/L, approved, priority/critical-urgent, dco-signoff: yes, release-blocker

#2328 Add the KubeOne stacked logo
  docs/img/kubeone-stacked.svg
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes

#2329 testv2: Fix waitMachinesHasNodes, increase timeouts, and label nodes to skip eviction
  testv2/e2e/helpers.go
  testv2/e2e/scenario_migrate_csi_ccm.go
  testv2/e2e/scenario_upgrade.go
Labels: kind/bug, release-note-none, lgtm, size/M, approved, dco-signoff: yes

#2331 Mount /usr/share/ca-certificates in the Azure CCM, update Flatcar to 3227.2.1, enforce NFT backend, and improve Terraform configs
  addons/ccm-azure/ccm-azure.yaml
  examples/terraform/azure/README.md
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  pkg/addons/applier.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2333 [release/v1.4] Update machine-controller to v1.43.7
  pkg/templates/images/images.go
Labels: kind/bug, size/XS, lgtm, approved, release-note-action-required, dco-signoff: yes

#2337 [release/v1.5] Bring the release/v1.5 branch in-sync with the master branch
  CHANGELOG/CHANGELOG-1.4.md
  addons/ccm-azure/ccm-azure.yaml
  docs/img/kubeone-stacked.svg
  examples/terraform/azure/README.md
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  pkg/addons/applier.go
  pkg/scripts/ccm_csi_migration.go
  pkg/scripts/ccm_csi_migration_test.go
  pkg/scripts/testdata/TestCCMMigrationRegenerateControlPlaneConfigs-not-verbose.golden
  pkg/scripts/testdata/TestCCMMigrationRegenerateControlPlaneConfigs-verbose.golden
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/tasks.go
  testv2/e2e/helpers.go
  testv2/e2e/scenario_migrate_csi_ccm.go
  testv2/e2e/scenario_upgrade.go
Labels: lgtm, release-note, size/L, approved, kind/cleanup, dco-signoff: yes

#2335 Add changelog for the v1.4.8 release
  CHANGELOG/CHANGELOG-1.4.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2334 [release/v1.4] Cherry-pick Canal/Calico iptables backend and Azure CCM changes
  .golangci.yml
  addons/calico-vxlan/calico-vxlan.yaml
  addons/ccm-azure/ccm-azure.yaml
  addons/cni-canal/canal.yaml
  pkg/addons/applier.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2336 [release/v1.4] Cherry-pick changelogs for v1.4.7 and v1.4.8
  CHANGELOG.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes

#2327 Ensure vsphere-csi-driver is removed in kube-system namespace
  addons/csi-vsphere-ks/validatingwebhook.yaml
  addons/csi-vsphere-ks/vsphere-csi-driver.yaml
  pkg/addons/ensure.go
  pkg/addons/helpers.go
  pkg/templates/resources/resources.go
Labels: kind/bug, release-note-none, lgtm, size/XL, approved, dco-signoff: yes, release-blocker

#2313 Add the changelog for the v1.5.0 release
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, lgtm, size/L, approved, kind/documentation, dco-signoff: yes
