Repository kubermatic/kubeone, pull requests merged in 2022-09, with the labels that each got.

#2338 Update golangci to 1.49.0
  .golangci.yml
  .prow/verify.yaml
  testv2/e2e/cloudprovider.go
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes

#2344 Initialize OperatingSystemManager in KubeOneCluster regardless if MachineController enabled or not
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/tasks/probes.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2347 Handle OS signals in testv2
  .golangci.yml
  test/e2e/testutil/exec.go
  testv2/e2e/helpers.go
  testv2/e2e/kubeone.go
  testv2/e2e/scenario_conformance.go
  testv2/e2e/scenario_install.go
  testv2/e2e/scenario_migrate_csi_ccm.go
  testv2/e2e/scenario_upgrade.go
  testv2/e2e/sonobuoy.go
  testv2/e2e/terraform.go
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/go-test-e2e.sh
Labels: kind/bug, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#2349 Initialize OperatingSystemManager even if v1beta1 API is used
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/credentials/secret.go
  pkg/tasks/tasks.go
  pkg/templates/operatingsystemmanager/helper.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2351 Add kind/chore to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes

#2354 Hard-disable OSM when v1beta1 is used
  pkg/apis/kubeone/config/config.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2353 Upgrade kubernetes CNI package to v1.1.1
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2355 install.sh: change VERSION regex to match only stable releases
  install.sh
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2358 [release/v1.4] Update kubernetes-cni to 1.1.1
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#2356 New NodeLocalDNS API field
  addons/machinecontroller/deployment-controller.yaml
  addons/operating-system-manager/deployment-controller.yaml
  docs/api_reference/v1beta2.en.md
  pkg/addons/ensure.go
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/templates/kubernetesconfigs/kubelet.go
Labels: kind/feature, lgtm, release-note, size/L, approved, kind/api-change, dco-signoff: yes

#2359 Upgrade to cilium v1.12.2
  addons/cni-cilium/cilium.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#2364 Delete CoreDNS PodDistruptionBudget if the feature is disabled
  pkg/addons/ensure.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2369 Remove old E2E tests in favor of new tests
  .prow/1.22.yaml
  .prow/1.23.yaml
  .prow/1.24.yaml
  .prow/generated.yaml
  Makefile
  test/README.md
  test/e2e/cloudprovider.go
  test/e2e/cloudprovider/cloudprovider.go
  test/e2e/conformance_test.go
  test/e2e/flag.go
  test/e2e/flag_test.go
  test/e2e/helpers.go
  test/e2e/kubeone.go
  test/e2e/kubetest.go
  test/e2e/main_test.go
  test/e2e/os.go
  test/e2e/provisioner/default.go
  test/e2e/provisioner/provisioner.go
  test/e2e/provisioner/terraform.go
  test/e2e/prow.yaml
  test/e2e/scenario_conformance.go
  test/e2e/scenario_install.go
  test/e2e/scenario_migrate_csi_ccm.go
  test/e2e/scenario_upgrade.go
  test/e2e/sonobuoy.go
  test/e2e/terraform.go
  test/e2e/testdata/containerd_calico.yaml
  test/e2e/testdata/containerd_cilium.yaml
  test/e2e/testdata/containerd_simple.yaml
  test/e2e/testdata/containerd_simple_external.yaml
  test/e2e/testdata/containerd_weave.yaml
  test/e2e/testdata/docker_calico.yaml
  test/e2e/testdata/docker_cilium.yaml
  test/e2e/testdata/docker_simple.yaml
  test/e2e/testdata/docker_simple_external.yaml
  test/e2e/testdata/docker_weave.yaml
  test/e2e/testdata/kube_proxy_ipvs.yaml
  test/e2e/testdata/legacy_machine_controller_containerd.yaml
  test/e2e/testdata/legacy_machine_controller_containerd_external.yaml
  test/e2e/testdata/legacy_machine_controller_docker.yaml
  test/e2e/testdata/legacy_machine_controller_docker_external.yaml
  test/e2e/testdata/openstack_centos.tfvars
  test/e2e/testdata/openstack_flatcar.tfvars
  test/e2e/testdata/openstack_rhel.tfvars
  test/e2e/testdata/openstack_rockylinux.tfvars
  test/e2e/testdata/openstack_ubuntu.tfvars
  test/e2e/testdata/s3_backend.tf
  test/e2e/testdata/vsphere.tfvars
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/e2e/testutil/testutil.go
  test/e2e/upgrade_test.go
  test/generator/main.go
  test/go-test-e2e.sh
  test/testexec/exec.go
  test/testexec/exec_test.go
  test/tests.yml
  testv2/e2e/kubeone.go
Labels: kind/feature, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes

#2366 Use vmware-system-csi namespace when generating certs for the vSphere CSI webhooks
  pkg/addons/applier.go
  pkg/templates/resources/resources.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2367 Support for Ubuntu 22.04
  .github/ISSUE_TEMPLATE/bug-report.md
  .prow/verify.yaml
  examples/terraform/aws/README.md
  examples/terraform/aws/variables.tf
  examples/terraform/azure/README.md
  examples/terraform/azure/variables.tf
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/variables.tf
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/variables.tf
  examples/terraform/gce/README.md
  examples/terraform/gce/variables.tf
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/variables.tf
  examples/terraform/openstack/README.md
  examples/terraform/openstack/variables.tf
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/variables.tf
  go.mod
  go.sum
  pkg/templates/images/images.go
  test/e2e/testdata/openstack_ubuntu.tfvars
Labels: kind/feature, lgtm, size/XL, approved, release-note-action-required, dco-signoff: yes, docs/none

#2378 Add changelog for 1.5.1 and 1.4.9 patch releases
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#2380 [release/v1.4] Add changelog for v1.4.9 patch release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#2379 [release/v1.5] Add changelog for v1.5.1 and remove changelogs for non-1.5 releases
  CHANGELOG/CHANGELOG-0.x.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/README.md
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#2382 Containerd 1.6
  go.mod
  go.sum
  pkg/scripts/funcs.go
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#2387 Upgrade to OSM v1.1.1
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2390 Update x/crypto to fix issues with authenticating over SSH
  go.mod
  go.sum
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2388 [release/v1.5] Update containerd to 1.6
  go.mod
  go.sum
  pkg/scripts/funcs.go
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#2391 SSH host public keys verification
  docs/api_reference/v1beta2.en.md
  examples/terraform/aws/README.md
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  examples/terraform/azure/README.md
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/output.tf
  examples/terraform/digitalocean/variables.tf
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/output.tf
  examples/terraform/equinixmetal/variables.tf
  examples/terraform/gce/README.md
  examples/terraform/gce/output.tf
  examples/terraform/gce/variables.tf
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/output.tf
  examples/terraform/nutanix/variables.tf
  examples/terraform/openstack/README.md
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/output.tf
  examples/terraform/vmware-cloud-director/variables.tf
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/outputs.tf
  examples/terraform/vsphere_flatcar/variables.tf
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/ssh/connection.go
  pkg/ssh/connector.go
  pkg/terraform/v1beta2/config.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none
