Repository kubermatic/kubeone, pull requests merged in 2022-02, with the labels that each got.

#1766 Add machine-controller update to the changelog
  CHANGELOG.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1797 Update Canal and Calico VXLAN to v3.22.0
  addons/calico-vxlan/calico-vxlan.yaml
  addons/cni-canal/canal.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes

#1767 Change baseurl to vault.centos.org for CentOS 8
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  pkg/scripts/os_centos.go
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1800 Update the changelog for the v1.4.0-rc.0 release
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1810 Control Plan Count Variable `control_plane_vm_count` addition to variables.tf for AWS
  examples/terraform/aws/main.tf
  examples/terraform/aws/variables.tf
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1808 Use semver constraints on Kubernetes version for upper and lower bounds
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1813 fix: Select correct CSR to approve
  pkg/tasks/certs.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1816 Update terraform provider version for openstack to 1.47.0
  examples/terraform/openstack/variables.tf
  examples/terraform/openstack/versions.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1821 Include darwin/arm64 builds in release artifacts
  .goreleaser.yml
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1820 Update DigitalOcean CSI to v4.0.0
  addons/csi-digitalocean/crds.yaml
  addons/csi-digitalocean/driver.yaml
  addons/csi-digitalocean/snapshot-controller.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes

#1818 Increase version lower bound to Kubernetes 1.20
  .prow.yaml
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1824 fix: Restore missing addons deploy after containerd migration
  pkg/tasks/tasks.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1815 AWS: install csi driver if k8s >1.23 even if cloud.external=false
  pkg/addons/ensure.go
  pkg/apis/kubeone/validation/validation.go
  pkg/semverutil/helper.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1826 Allow docker as container-runtime up to k8s v1.24
  addons/cni-cilium/cilium.yaml
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/cmd/config.go
  pkg/tasks/probes.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1830 fix: use yaml.UnmarshalStrict for registriesAuth from credentials file
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/config/config_test.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1832 Add @ahmedwaleedmalik as OWNER
  OWNERS
Labels: size/XS, release-note-none, lgtm, approved, ¯\_(ツ)_/¯, dco-signoff: yes

#1831 Install CSI drivers for k8s 1.23 un-conditionally
  pkg/addons/ensure.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes

#1835 Add changelog for the v1.4.0-rc.1 release
  CHANGELOG.md
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes

#1839 Update the 1.4.0-rc.1 changelog
  CHANGELOG.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1840 Don't upgrade MachineDeployments when refreshing resources
  pkg/tasks/tasks.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1844 fix: centos periodic
  examples/terraform/aws/README.md
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  test/e2e/os.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1846 Fix minor issues in Terraform configs for vSphere/Flatcar
  examples/terraform/vsphere_flatcar/main.tf
  examples/terraform/vsphere_flatcar/variables.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1851 docs: update default image for hetzner and openstack
  examples/terraform/hetzner/README.md
  examples/terraform/openstack/README.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1843 Update URLs to docs
  addons/cluster-autoscaler/README.md
  pkg/cmd/config.go
  pkg/cmd/migrate.go
  pkg/tasks/machine_deployments.go
  pkg/tasks/tasks.go
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1845 Provide correct path to the vSphere CSI webhook certs
  pkg/addons/manifest.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes

#1852 Improve CCM/CSI migration warning for OpenStack
  examples/terraform/openstack/output.tf
  pkg/cmd/migrate.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#1853 Fix the default-storage-class addon
  addons/default-storage-class/storage-class.yaml
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1855 Fix Terraform configs for AWS
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1856 e2e: allow amzn2 for worker nodes
  test/e2e/os.go
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes

#1825 Add changelog for the v1.4.0 release
  CHANGELOG.md
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes

#1849 Expand path to SSH private key file
  pkg/ssh/connection.go
  pkg/ssh/connector.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes

#1860 config: Unmarshal to versioned KubeOneCluster
  pkg/cmd/config.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes

#1871 Fix missing CRDs for cinder csi
  addons/csi-openstack-cinder/snapshot-crds.yaml
Labels: kind/bug, lgtm, release-note, size/XL, approved, dco-signoff: yes

#1873 Add a script for generating the changelog
  hack/changelog.tpl
  hack/generate-changelog.sh
Labels: release-note-none, lgtm, size/L, approved, kind/documentation, dco-signoff: yes
