Repository kubermatic/kubeone, pull requests merged in 2022-07, with the labels that each got.

#2128 [release/v1.4] Use --max-pods flag instead of kubelet config file
  pkg/tasks/common.go
  pkg/tasks/kubeadm_env.go
  pkg/tasks/upgrade_follower.go
  pkg/tasks/upgrade_leader.go
  pkg/tasks/upgrade_static_workers.go
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#2130 Add new HostConfig.Labels API to manage custom labels on the static Nodes
  docs/api_reference/v1beta2.en.md
  examples/terraform/aws/README.md
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/tasks/nodes.go
  pkg/tasks/tasks.go
  pkg/terraform/v1beta2/config.go
Labels: kind/feature, lgtm, release-note, size/L, approved, kind/api-change, dco-signoff: yes

#2132 Use kubeone dedicated vSphere template for e2e tests
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/main.tf
  examples/terraform/vsphere_flatcar/variables.tf
  testv2/e2e/testdata/vsphere_default.tfvars
  testv2/e2e/testdata/vsphere_flatcar.tfvars
Labels: release-note-none, lgtm, size/M, approved, kind/flake, dco-signoff: yes

#2138 Make KubeletConfiguration and KubeProxyConfiguration to be readable again on the older kubernetes versions
  pkg/templates/kubeadm/v1beta2/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubernetesconfigs/kubelet.go
  pkg/templates/kubernetesconfigs/kubeproxy.go
  pkg/templates/kubernetesconfigs/util.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes

#2125 Kubeone local
  pkg/addons/applier.go
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/certificate/ca.go
  pkg/clusterstatus/apiserverstatus/apiserverstatus.go
  pkg/clusterstatus/etcdstatus/etcdstatus.go
  pkg/cmd/apply.go
  pkg/cmd/install.go
  pkg/cmd/local.go
  pkg/cmd/proxy.go
  pkg/cmd/root.go
  pkg/cmd/shared.go
  pkg/configupload/configuration.go
  pkg/etcdutil/etcd.go
  pkg/executor/executorfs/file.go
  pkg/executor/executorfs/fs.go
  pkg/executor/interface.go
  pkg/executor/local.go
  pkg/kubeconfig/kubeconfig.go
  pkg/runner/runner.go
  pkg/scripts/node.go
  pkg/ssh/connection.go
  pkg/ssh/connector.go
  pkg/ssh/sshiofs/file.go
  pkg/state/context.go
  pkg/state/task.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/certs.go
  pkg/tasks/common.go
  pkg/tasks/containerd.go
  pkg/tasks/controlplane.go
  pkg/tasks/encryption_providers.go
  pkg/tasks/kubeadm_config.go
  pkg/tasks/nodes.go
  pkg/tasks/prerequisites.go
  pkg/tasks/probes.go
  pkg/tasks/reset.go
  pkg/tasks/static_wokers.go
  pkg/tasks/upgrade_follower.go
  pkg/tasks/upgrade_leader.go
  pkg/tasks/upgrade_static_workers.go
  pkg/tasks/util.go
  pkg/tunnel/etcdtunnel.go
  pkg/tunnel/httptunnel.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes

#2139 Add dedicated error type (and error code) for exec adapter
  pkg/executor/local.go
  pkg/fail/errors.go
  pkg/fail/exitcodes.go
  pkg/runner/runner.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2137 Add GCP Compute Persistent Disk CSI driver
  addons/csi-gcp-compute-persistent/cluster_setup.yaml
  addons/csi-gcp-compute-persistent/controller.yaml
  addons/csi-gcp-compute-persistent/crds.yaml
  addons/csi-gcp-compute-persistent/csidriver.yaml
  addons/csi-gcp-compute-persistent/node.yaml
  addons/csi-gcp-compute-persistent/rbac-snapshot-controller.yaml
  addons/csi-gcp-compute-persistent/snapshot-controller.yaml
  addons/csi-gcp-compute-persistent/snapshot-webhook.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/credentials/credentials.go
  pkg/credentials/secret.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes

#2140 Fix KubeOne failing to restart RHEL VMs
  pkg/tasks/prerequisites.go
  testv2/e2e/tests_definitions.go
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/regression

#2142 Migrate GCE standard StorageClass to set proper volumeBindingMode
  pkg/addons/ensure.go
  pkg/addons/helpers.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2141 [release/v1.4] Add GCP Compute Persistent Disk CSI driver
  .golangci.yml
  addons/csi-gcp-compute-persistent/cluster_setup.yaml
  addons/csi-gcp-compute-persistent/controller.yaml
  addons/csi-gcp-compute-persistent/crds.yaml
  addons/csi-gcp-compute-persistent/csidriver.yaml
  addons/csi-gcp-compute-persistent/node.yaml
  addons/csi-gcp-compute-persistent/rbac-snapshot-controller.yaml
  addons/csi-gcp-compute-persistent/snapshot-controller.yaml
  addons/csi-gcp-compute-persistent/snapshot-webhook.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/addons/helpers.go
  pkg/credentials/credentials.go
  pkg/credentials/secret.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes

#2143 E2E terraform configs refactoring
  examples/terraform/aws/README.md
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  examples/terraform/azure/README.md
  examples/terraform/azure/main.tf
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/main.tf
  examples/terraform/digitalocean/output.tf
  examples/terraform/digitalocean/variables.tf
  examples/terraform/gce/README.md
  examples/terraform/gce/main.tf
  examples/terraform/gce/output.tf
  examples/terraform/gce/variables.tf
  examples/terraform/gce/versions.tf
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/hetzner/variables.tf
  testv2/e2e/prow.yaml
  testv2/e2e/testdata/containerd_cilium.yaml
  testv2/e2e/testdata/docker_cilium.yaml
  testv2/e2e/testdata/kube_proxy_ipvs.yaml
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, kind/cleanup, dco-signoff: yes

#2144 Schedule GCP CSI driver on control plane nodes
  addons/csi-gcp-compute-persistent/controller.yaml
  addons/csi-gcp-compute-persistent/snapshot-controller.yaml
  addons/csi-gcp-compute-persistent/snapshot-webhook.yaml
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, dco-signoff: yes

#2147 Add changelog for v1.4.5
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2146 Enable GCE generated E2E tests
  testv2/e2e/prow.yaml
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/go-test-e2e.sh
  testv2/tests.yml
Labels: release-note-none, lgtm, size/L, approved, kind/failing-test, dco-signoff: yes

#2154 Prevent NPE on ssh connection close
  pkg/ssh/connection.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2022 Secrets CSI driver
  .gitignore
  addons/csi-vault-secret-provider/README.md
  addons/csi-vault-secret-provider/generate-values
  addons/csi-vault-secret-provider/manifest.yaml
  addons/secrets-store-csi-driver/README.md
  addons/secrets-store-csi-driver/generate-values
  addons/secrets-store-csi-driver/manifest.yaml
  docs/api_reference/v1beta2.en.md
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/tasks/tasks.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes

#2156 Document example for node and machine annotations
  examples/terraform/azure/output.tf
  examples/terraform/digitalocean/output.tf
  examples/terraform/equinixmetal/output.tf
  examples/terraform/gce/output.tf
  examples/terraform/hetzner/output.tf
  examples/terraform/openstack/output.tf
  examples/terraform/vmware-cloud-director/output.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere_flatcar/outputs.tf
Labels: release-note-none, lgtm, size/L, approved, kind/documentation, dco-signoff: yes

#2159 Increase default MachineDeployment replicas to 2 for all non-AWS configs
  examples/terraform/azure/README.md
  examples/terraform/azure/variables.tf
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/variables.tf
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/variables.tf
  examples/terraform/gce/README.md
  examples/terraform/gce/variables.tf
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/variables.tf
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/variables.tf
  examples/terraform/openstack/README.md
  examples/terraform/openstack/variables.tf
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/variables.tf
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/variables.tf
Labels: lgtm, release-note, size/M, approved, kind/cleanup, dco-signoff: yes

#2158 Equinix Metal: use Metro instead of facilities
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/main.tf
  examples/terraform/equinixmetal/output.tf
  examples/terraform/equinixmetal/variables.tf
  examples/terraform/equinixmetal/versions.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/terraform/v1beta2/update.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#2155 Hetzner: remove server selector and update label selector to also match kubeone_cluster_name label
  examples/terraform/hetzner/main.tf
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#2161 Adjust regex to be GNU and BSD sed compatible
  install.sh
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2162 Run kubeone proxy after provisioning the cluster
  testv2/e2e/helpers.go
  testv2/e2e/scenario_conformance.go
  testv2/e2e/scenario_install.go
  testv2/e2e/scenario_upgrade.go
Labels: release-note-none, lgtm, size/M, approved, kind/failing-test, dco-signoff: yes

#2166 Update golangci-lint image to v1.47.1
  .prow/verify.yaml
  pkg/cmd/proxy.go
  pkg/tasks/kubeadm_env.go
Labels: release-note-none, size/S, lgtm, approved, kind/cleanup, dco-signoff: yes

#2165 Make CoreDNS deployment configurable, add Pod Anti Affinity and PodDisruptionBudget
  addons/coredns-pdb/poddisruptionbudget.yaml
  docs/api_reference/v1beta2.en.md
  pkg/addons/ensure.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/conversion.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/tasks/coredns.go
  pkg/templates/resources/resources.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2167 default-storage-class: Fix logic for determining if the CSI driver is deployed
  addons/default-storage-class/storage-class.yaml
  pkg/addons/applier.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2163 testv2/upgrade: Open ZIP as RDWR and provide only one version to install
  testv2/e2e/helpers.go
  testv2/e2e/scenario_upgrade.go
Labels: size/XS, release-note-none, lgtm, approved, kind/failing-test, dco-signoff: yes

#2151 Upgrade OpenStack CCM and Cinder CSI for Kubernetes 1.24 and 1.23 clusters
  addons/csi-openstack-cinder/controllerplugin.yaml
  addons/csi-openstack-cinder/nodeplugin.yaml
  pkg/templates/images/images.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2170 Fix invalid resource reference in azure terraform config
  examples/terraform/azure/main.tf
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#2178 Improve kubeone-e2e image
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/bashrc
  hack/images/kubeone-e2e/htoprc
  hack/images/kubeone-e2e/install-kube-tests-binaries.sh
  hack/images/kubeone-e2e/release.sh
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, dco-signoff: yes

#2179 Update to Go 1.18.4
  .prow/1.21.yaml
  .prow/1.22.yaml
  .prow/1.23.yaml
  .prow/1.24.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  testv2/e2e/helpers.go
  testv2/e2e/prow.yaml
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes

#2181 Update Kubernetes versions used in the old E2E tests
  .prow/1.21.yaml
  .prow/1.22.yaml
  .prow/1.23.yaml
  .prow/1.24.yaml
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes

#2171 Update AWS CCM and AWS EBS CSI driver to v1.9.0
  addons/csi-aws-ebs/clusterrole-snapshotter.yaml
  addons/csi-aws-ebs/controller.yaml
  addons/csi-aws-ebs/crd-volumesnapshotclasses.yaml
  addons/csi-aws-ebs/crd-volumesnapshotcontents.yaml
  addons/csi-aws-ebs/crd-volumesnapshots.yaml
  addons/csi-aws-ebs/csi-snapshot-controller.yaml
  addons/csi-aws-ebs/rbac-snapshot-controller.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2182 Update the Nutanix CSI driver to v2.5.1
  addons/csi-nutanix/ntnx-csi-controller-deployment.yaml
  addons/csi-nutanix/ntnx-csi-node-ds.yaml
  addons/csi-nutanix/ntnx-csi-rbac.yaml
  addons/csi-nutanix/snapshot-controller-deployment.yaml
  addons/csi-nutanix/snapshot-controller-rbac.yaml
  addons/csi-nutanix/snapshot-controller-sts.yaml
  addons/csi-nutanix/validating-deployment.yaml
  addons/csi-nutanix/validating-rbac.yaml
  addons/csi-nutanix/validating-webhook.yaml
  addons/csi-nutanix/volumesnapshotclasses.yaml
  addons/csi-nutanix/volumesnapshotcontents.yaml
  addons/csi-nutanix/volumesnapshots.yaml
  pkg/templates/images/images.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, size/XL, approved, kind/documentation, dco-signoff: yes

#2183 fix typos
  CHANGELOG.md
  docs/proposals/20210112-encryption-roviders.md
  examples/terraform/aws/README.md
  examples/terraform/aws/main.tf
  examples/terraform/aws/variables.tf
  examples/terraform/azure/README.md
  examples/terraform/azure/variables.tf
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/variables.tf
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/variables.tf
  examples/terraform/gce/README.md
  examples/terraform/gce/variables.tf
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/variables.tf
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/variables.tf
  examples/terraform/openstack/README.md
  examples/terraform/openstack/variables.tf
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/variables.tf
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/variables.tf
  hack/apidoc-gen/main.go
  hack/image-loader.sh
  pkg/addons/applier.go
  pkg/addons/ensure.go
  pkg/addons/manifest_test.go
  pkg/apis/kubeadm/bootstraptoken/v1/utils.go
  pkg/apis/kubeadm/v1beta2/bootstraptokenstring.go
  pkg/apis/kubeone/config/testdata/config-full-v1beta1.yaml
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/certificate/pki.go
  pkg/cmd/config.go
  pkg/cmd/local.go
  pkg/cmd/proxy.go
  pkg/configupload/configuration.go
  pkg/credentials/credentials.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/prerequisites.go
  pkg/templates/encryptionproviders/encryption_providers.go
  pkg/terraform/v1beta1/config.go
  pkg/terraform/v1beta2/config.go
  test/e2e/kubetest.go
  testv2/README.md
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes

#2174 Update Equinix Metal CCM to v3.4.3
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2176 Update GCP PD CSI driver to v1.7.2
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2169 Update vSphere CCM to v1.24.0 and v1.23.3 and CSI driver to v2.6.0
  addons/csi-vsphere/vsphere-csi-driver.yaml
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes

#2184 Disable --configure-cloud-routes on Azure CCM
  addons/ccm-azure/ccm-azure.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2187 Revert "Upgrade OpenStack CCM and Cinder CSI for Kubernetes 1.24 and 1.23 clusters"
  addons/csi-openstack-cinder/controllerplugin.yaml
  addons/csi-openstack-cinder/nodeplugin.yaml
  pkg/templates/images/images.go
Labels: kind/bug, release-note-none, lgtm, size/M, approved, dco-signoff: yes, kind/regression

#2152 Lower disk size for vSphere generated e2e tests
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/main.tf
  examples/terraform/vsphere_flatcar/outputs.tf
  examples/terraform/vsphere_flatcar/variables.tf
  testv2/e2e/prow.yaml
  testv2/e2e/testdata/vsphere.tfvars
  testv2/e2e/testdata/vsphere_default.tfvars
  testv2/e2e/testdata/vsphere_flatcar.tfvars
  testv2/e2e/tests_definitions.go
Labels: release-note-none, lgtm, size/L, approved, kind/flake, dco-signoff: yes

#2173 Update DigitalOcean CSI driver to v4.2.0
  addons/csi-digitalocean/crds.yaml
  addons/csi-digitalocean/driver.yaml
  addons/csi-digitalocean/rbac-snapshot-webhook.yaml
  addons/csi-digitalocean/snapshot-controller.yaml
  addons/csi-digitalocean/snapshot-validation-webhook.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2172 Update Azure CCM, AzureDisk CSI driver to v1.21.0, and AzureFile CSI driver to v1.20.0
  addons/csi-azuredisk/csi-azuredisk-driver.yaml
  addons/csi-azuredisk/rbac-csi-azuredisk-node.yaml
  addons/csi-azurefile/csi-azurefile-driver.yaml
  addons/csi-azurefile/csi-azurefile-node.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes

#2189 [release/v1.4] Update Canal and Calico VXLAN to v3.22.4
  addons/calico-vxlan/calico-vxlan.yaml
  addons/cni-canal/canal.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2191 [release/v1.4] Revert "Update Calico VXLAN addon to v3.22.4"
  addons/calico-vxlan/calico-vxlan.yaml
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes, kind/regression

#2188 Update Canal and Calico VXLAN to v3.23.3
  addons/calico-vxlan/calico-vxlan.yaml
  addons/cni-canal/canal.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes

#2193 [release/v1.43] Update machine-controller to v1.43.4
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2194 Reverted practice of automatically setting cloudProvider.external for some providers
  pkg/apis/kubeone/v1beta2/defaults.go
  testv2/e2e/prow.yaml
  testv2/e2e/testdata/containerd_simple_external.yaml
  testv2/e2e/testdata/docker_simple_external.yaml
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/tests.yml
Labels: kind/bug, lgtm, release-note, approved, size/XXL, dco-signoff: yes

#2195 Update OpenStack CCM and Cinder CSI for Kubernetes 1.24 and 1.23 clusters
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2186 [release/v1.4] Upgrade OpenStack CCM and Cinder CSI for Kubernetes 1.23 clusters
  pkg/templates/images/images.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2157 Enable OperatingSystemManager by default for managing userdata for machines
  README.md
  addons/operating-system-manager/README.md
  addons/operating-system-manager/rbac-webhook.yaml
  docs/api_reference/v1beta2.en.md
  examples/terraform/aws/output.tf
  go.mod
  go.sum
  pkg/addons/ensure.go
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/local.go
  pkg/credentials/secret.go
  pkg/templates/images/images.go
  testv2/e2e/prow.yaml
  testv2/e2e/testdata/legacy_machine_controller_userdata.yaml
  testv2/e2e/tests_definitions.go
  testv2/e2e/tests_test.go
  testv2/tests.yml
Labels: kind/feature, lgtm, size/L, approved, release-note-action-required, dco-signoff: yes

#2196 Openstack: Tenant ID/Name is not required with application credentials
  .golangci.yml
  pkg/credentials/credentials.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2198 Let OSM default the OSProfiles in AWS terraform config
  examples/terraform/aws/README.md
  examples/terraform/aws/main.tf
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2201 [release/v1.4] Openstack: Tenant ID/Name is not required with application credentials
  .golangci.yml
  pkg/credentials/credentials.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes

#2199 Force regenerating CSRs for Kubelet serving certificates after CCM is deployed
  pkg/scripts/ccm_csi_migration.go
  pkg/scripts/node.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/certs.go
  pkg/tasks/tasks.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2204 [release/v1.4] Force regenerating CSRs after CCM is deployed
  pkg/scripts/ccm_csi_migration.go
  pkg/scripts/node.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/certs.go
  pkg/tasks/tasks.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes

#2205 Fix tolerations for metrics-server
  addons/metrics-server/metrics-server.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2200 Disable Node IPAM in Hetzner CCM
  addons/ccm-hetzner/ccm-hetzner.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes

#2067 Add CSI snapshot controller and webhook to Cinder CSI
  addons/csi-digitalocean/snapshot-validation-webhook.yaml
  addons/csi-nutanix/validating-webhook.yaml
  addons/csi-openstack-cinder/snapshot-controller-rbac.yaml
  addons/csi-openstack-cinder/snapshot-controller.yaml
  addons/csi-openstack-cinder/snapshot-webhook.yaml
  addons/csi-vsphere/csi-snapshot-validatingwebhook.yaml
  addons/csi-vsphere/validatingwebhook.yaml
  addons/operating-system-manager/webhook.yaml
  pkg/addons/applier.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes
