Repository kubermatic/kubeone, pull requests merged in 2023-02, with the labels that each got.

#2640 Update OSM to v1.2.0 and Machine Controller to v1.56.0
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#2643 do not assign DynamicClient to state unless error is checked
  pkg/kubeconfig/kubeconfig.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#2647 azure: Fix CCM deployment and ssh reconnects
  addons/ccm-azure/ccm-azure.yaml
  examples/terraform/azure/README.md
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  pkg/cmd/proxy.go
  pkg/credentials/credentials_test.go
  pkg/kubeconfig/kubeconfig.go
  test/e2e/kubeone.go
  test/e2e/tests_definitions.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none, code-freeze-approved

#2649 Update Go to 1.19.6
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none, code-freeze-approved

#2648 Add changelog for v1.6.0
  CHANGELOG/CHANGELOG-1.6.md
Labels: release-note-none, lgtm, size/L, approved, kind/documentation, dco-signoff: yes, docs/none, code-freeze-approved

#2685 Hotfix: Restic backups
  addons/backups-restic/backups-restic.yaml
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#2687 Invoke goreleaser from Makefile
  .goreleaser.yml
  Makefile
  hack/run-ci-release.sh
Labels: kind/bug, release-note-none, size/S, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#2688 Remove the master taint starting with Kubernetes 1.25
  CHANGELOG/CHANGELOG-1.6.md
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta2/defaults.go
Labels: kind/bug, release-note-none, size/S, lgtm, approved, priority/critical-urgent, dco-signoff: yes, release-blocker, docs/none, code-freeze-approved

#2689 Add additional safeguad/validation for the master taint
  CHANGELOG/CHANGELOG-1.6.md
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/tasks/probes.go
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#2693 Remove usage of template_file in aws-dualstack Terraform scripts
  examples/terraform/aws-dualstack/README.md
  examples/terraform/aws-dualstack/cloud_config.yaml.tftpl
  examples/terraform/aws-dualstack/main.tf
  examples/terraform/aws-dualstack/variables.tf
Labels: kind/bug, release-note-none, size/S, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#2697 Require external CCM/CSI on vSphere starting with Kubernetes 1.25
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, size/M, approved, priority/critical-urgent, release-note-action-required, kind/api-change, dco-signoff: yes, release-blocker, docs/tbd, code-freeze-approved

#2699 Make vSphere tests work on the new infrastructure and add additional AWS CCM/CSI migration tests
  test/e2e/prow.yaml
  test/e2e/testdata/vsphere.tfvars
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/go-test-e2e.sh
  test/tests.yml
Labels: release-note-none, lgtm, size/XL, approved, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#2700 Update 1.6 changelog with the latest changes
  CHANGELOG/CHANGELOG-1.6.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none, code-freeze-approved

#2701 [release/v1.6] Update links to docs to v1.6 docs
  CHANGELOG/CHANGELOG-1.6.md
  README.md
  addons/README.md
  addons/calico-vxlan/README.md
  addons/cluster-autoscaler/README.md
  addons/cni-cilium/README.md
  docs/README.md
  docs/proposals/20200224-apply.md
  docs/release_process.md
  examples/terraform/aws-dualstack/README.md
  examples/terraform/aws-dualstack/README.md.in
  examples/terraform/aws/README.md
  examples/terraform/aws/README.md.in
  examples/terraform/azure/README.md
  examples/terraform/azure/README.md.in
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/README.md.in
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/README.md.in
  examples/terraform/gce/README.md
  examples/terraform/gce/README.md.in
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/README.md.in
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/README.md.in
  examples/terraform/openstack/README.md
  examples/terraform/openstack/README.md.in
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/README.md.in
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/README.md.in
  examples/terraform/vsphere_centos/README.md
  examples/terraform/vsphere_centos/README.md.in
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/README.md.in
  pkg/cmd/config.go
  pkg/cmd/migrate.go
  pkg/tasks/machine_deployments.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: release-note-none, lgtm, size/L, approved, kind/documentation, dco-signoff: yes, docs/none, code-freeze-approved

#2702 Fix goreleaser flags in Makefile
  Makefile
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#2706 Use apt/GPG key from `dl.k8s.io`
  pkg/scripts/os_debian.go
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/regression, docs/none

#2707 quote less when logging evictions
  pkg/nodeutils/drain.go
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes, docs/none
