Repository kubermatic/kubeone, pull requests merged in 2023-10, with the labels that each got.

#2927 Fix machinecontroller webhook escaping
  addons/machinecontroller/webhook.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2925 Apply registry override to sandbox (pause) image
  pkg/apis/kubeone/helpers.go
  pkg/containerruntime/containerd_config.go
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-override_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-insecureRegistry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlFlatcar.golden
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#2934 Fix broken CI
  .prow/generated.yaml
  test/e2e/tests_definitions.go
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#2933 Update CRDs for OSM
  addons/operating-system-manager/crd-operating-system-config.yaml
  addons/operating-system-manager/crd-operating-system-profile.yaml
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2936 [release/v1.7] Fix broken CI
  .prow/generated.yaml
  test/e2e/tests_definitions.go
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore, cherry-pick-approved

#2939 Drop containerRuntimeEndpoint field from KubeletConfiguration
  pkg/templates/kubernetesconfigs/kubelet.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2941 Update Go to 1.21.3, direct Go dependencies, and alpine image in the KubeOne image
  .prow/generated.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  .wwhrd.yml
  Dockerfile
  go.mod
  go.sum
  pkg/clientutil/create_or_update.go
  pkg/cmd/shared.go
  pkg/credentials/credentials.go
  pkg/templates/images/images.go
  pkg/templates/kubernetesconfigs/kubeproxy.go
  pkg/terraform/v1beta1/config.go
  pkg/terraform/v1beta2/config.go
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: lgtm, release-note, approved, size/XXL, kind/cleanup, dco-signoff: yes, docs/none

#2942 Update operating-system-manager (OSM) to v1.3.3
  pkg/templates/images/images.go
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes, docs/none

#2945 vcd: don't fail credential validation when only an API token is passed
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none
