Repository kubermatic/kubeone, pull requests merged in 2023-01, with the labels that each got.

#2572 Update Azure CCM, AzureDisk CSI, and AzureFile CSI for Kubernetes 1.26
  addons/csi-azuredisk/csi-azuredisk-controller.yaml
  addons/csi-azurefile/csi-azurefile-controller.yaml
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2573 Forbid Kubernetes 1.26 for OpenStack clusters with in-tree provider
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, size/M, approved, release-note-action-required, kind/api-change, dco-signoff: yes, kind/deprecation, docs/tbd

#2575 Update OSM and MC to latest versions
  addons/operating-system-manager/crd-operating-system-config.yaml
  addons/operating-system-manager/crd-operating-system-profile.yaml
  addons/operating-system-manager/deployment-controller.yaml
  pkg/templates/images/images.go
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#2571 Helm conditional deploy
  go.mod
  pkg/localhelm/helm3.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/tbd

#2576 Update DigitalOcean CCM, GCP CSI driver, and VCD CSI driver (January 2023)
  addons/csi-vmware-cloud-director/csi-controller.yaml
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2580 Update metrics-server, cluster-autoscaler, and NodeLocalDNSCache (January 2023)
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2579 Addons updates
  addons/backups-restic/backups-restic.yaml
  addons/csi-vault-secret-provider/README.md
  addons/secrets-store-csi-driver/README.md
  addons/unattended-upgrades/fluo.yaml
  addons/unattended-upgrades/kured.yaml
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes, kind/chore, docs/none

#2578 Update Hetzner CSI to v2.1.0
  addons/csi-hetzner/hcloud-csi.yml
  pkg/addons/ensure.go
  pkg/addons/helpers.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes, docs/none

#2582 Update Cilium, OpenStack CCM, and Cinder CSI (January 2023)
  addons/cni-cilium/cilium.yaml
  addons/csi-openstack-cinder/controllerplugin.yaml
  addons/csi-openstack-cinder/nodeplugin.yaml
  addons/csi-openstack-cinder/snapshot-controller-rbac.yaml
  addons/csi-openstack-cinder/snapshot-controller.yaml
  addons/csi-openstack-cinder/snapshot-webhook-rbac.yaml
  pkg/apis/kubeone/helpers.go
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#2583 Update terraform provider for VMware Cloud Director
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/main.tf
  examples/terraform/vmware-cloud-director/output.tf
  examples/terraform/vmware-cloud-director/variables.tf
  examples/terraform/vmware-cloud-director/versions.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/terraform/v1beta2/config.go
  pkg/terraform/v1beta2/update.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none, backport-needed

#2584 [release/v1.5] Update terraform provider for VMware Cloud Director
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/main.tf
  examples/terraform/vmware-cloud-director/output.tf
  examples/terraform/vmware-cloud-director/variables.tf
  examples/terraform/vmware-cloud-director/versions.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/terraform/v1beta2/config.go
  pkg/terraform/v1beta2/update.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes

#2586 Fix ca-bundle configuration for machine controller webhook
  addons/machinecontroller/webhook.yaml
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none, backport-needed

#2588 add ca bundle to osm deployment
  addons/operating-system-manager/deployment-controller.yaml
Labels: kind/bug, size/S, lgtm, release-note, approved, ok-to-test, dco-signoff: yes, docs/none

#2590 Update DigitalOcean CSI to v4.5.0
  addons/csi-digitalocean/snapshot-validation-webhook.yaml
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2592 [release/v1.5] Add changelog for v1.5.5
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2591 Add changelogs for v1.5.5 and v1.4.13
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#2593 [release/v1.4] Add changelog for v1.4.13
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes

#2594 Forbid PodSecurityPolicy for Kubernetes 1.25+
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, size/M, approved, release-note-action-required, kind/api-change, dco-signoff: yes, docs/none

#2598 Forbid unsupported IP families
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes, docs/none

#2601 Update containerd to 1.6* on Amazon Linux 2
  pkg/scripts/funcs.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.26.0.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2602 Use main revision for 1.26 upgrade tests
  test/e2e/prow.yaml
  test/e2e/scenario_upgrade.go
  test/e2e/tests_definitions.go
  test/generator/main.go
  test/tests.yml
Labels: release-note-none, lgtm, size/L, approved, kind/failing-test, dco-signoff: yes, docs/none

#2604 Stop applying master taint for 1.26+ clusters
  pkg/apis/kubeone/v1beta1/defaults.go
  pkg/apis/kubeone/v1beta2/defaults.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2606 Update kubernetes-cni to v1.2.0 and cri-tools to v1.26.0
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/templates/images/images.go
  test/e2e/prow.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none

#2608 [release/v1.5] Update kubernetes-cni to v1.2.0 and cri-tools to v1.26.0
  pkg/scripts/os.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/templates/images/images.go
  test/e2e/prow.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none, code-freeze-approved

#2624 Add changelog for v1.5.6
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none, code-freeze-approved

#2626 Actually bind cri-tools version for Ubuntu, CentOS, and Amazon Linux
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.26.0.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestRemoveBinariesAmazonLinux.golden
  pkg/scripts/testdata/TestRemoveBinariesCentOS.golden
  pkg/scripts/testdata/TestRemoveBinariesDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, release-note-none, lgtm, size/L, approved, dco-signoff: yes, docs/none, code-freeze-approved

#2627 [release/v1.5] Actually bind cri-tools version for Ubuntu, CentOS, and Amazon Linux
  CHANGELOG/CHANGELOG-1.5.md
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.23.9.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestRemoveBinariesAmazonLinux.golden
  pkg/scripts/testdata/TestRemoveBinariesCentOS.golden
  pkg/scripts/testdata/TestRemoveBinariesDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, release-note-none, lgtm, size/L, approved, dco-signoff: yes, do-not-merge/code-freeze

#2629 Update release date for v1.5.6
  CHANGELOG/CHANGELOG-1.5.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none, code-freeze-approved
