Repository kubermatic/kubeone, pull requests merged in 2023-03, with the labels that each got.

#2715 Make HelmRelease.RepoURL an optional field
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/validation/validation.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2717 [Release/v1.5] Update OSM to v1.1.3
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore

#2718 [Release/v1.6] Update OSM to v1.2.1
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore

#2722 Update Hetzner CSI to v2.2.0
  addons/csi-hetzner/hcloud-csi.yml
  pkg/templates/images/images.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2733 vCD API logging in Terraform examples
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/main.tf
  examples/terraform/vmware-cloud-director/variables.tf
Labels: kind/feature, size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, docs/none

#2734 vCD Terraform - switch from deprecated metadata to metadata_entry
  examples/terraform/vmware-cloud-director/main.tf
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, needs-ok-to-test, dco-signoff: yes, kind/chore, docs/none

#2740 Add changelogs for v1.6.1 and v1.5.7
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/README.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#2741 [release/v1.5] Add changelog for v1.5.7
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/README.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#2742 [release/v1.6] Add changelog for v1.6.1
  CHANGELOG/CHANGELOG-0.x.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/README.md
Labels: release-note-none, lgtm, approved, size/XXL, kind/documentation, dco-signoff: yes, cherry-pick-approved

#2744 fix: Explicitly start docker in vSphere flatcar
  examples/terraform/vsphere_flatcar/main.tf
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2730 csi-vmware-cloud-director: overwrite clusterId with param
  addons/csi-vmware-cloud-director/vcloud-csi-config.yaml
Labels: kind/feature, size/XS, lgtm, release-note, approved, ok-to-test, dco-signoff: yes, docs/none

#2747 Update VMware Cloud Director CSI driver
  addons/csi-vmware-cloud-director/csi-controller.yaml
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none
