Repository kubermatic/kubeone, pull requests merged in 2023-08, with the labels that each got.

#2840 Update CSI and CCM addons for digitalocean
  addons/csi-digitalocean/driver.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#2843 GCP CSI Driver update to v1.10.1
  addons/csi-gcp-compute-persistent/Kustomization
  addons/csi-gcp-compute-persistent/README.md
  addons/csi-gcp-compute-persistent/cluster_setup.yaml
  addons/csi-gcp-compute-persistent/controller.yaml
  addons/csi-gcp-compute-persistent/csi-gcp-compute-persistent.yaml
  addons/csi-gcp-compute-persistent/node.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#2845 Update images in backups-restic and unattended-upgrades addons
  addons/backups-restic/backups-restic.yaml
  addons/unattended-upgrades/fluo.yaml
  addons/unattended-upgrades/kured.yaml
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#2854 Take into account TEST_TIMEOUT env for internal context timeout
  test/e2e/helpers.go
  test/e2e/scenario_install.go
  test/e2e/scenario_upgrade.go
  test/e2e/tests_test.go
Labels: kind/bug, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, docs/none

#2855 Drop v1.27 constraint for vSphere, since CCM has been updated
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2856 Fix vSphere CCM YAML indentation
  addons/ccm-vsphere/ccm-vsphere.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2858 Fix azure SKU in e2e
  examples/terraform/azure/README.md
  examples/terraform/azure/main.tf
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  pkg/credentials/secret.go
  test/e2e/cloudprovider.go
  test/go-test-e2e.sh
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2859 Update AWS EBS CSI driver to v1.22.0
  addons/csi-aws-ebs/README.md
  addons/csi-aws-ebs/csi-aws-ebs.yaml
  pkg/templates/images/images.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#2860 Update canal (v3.26.1) and cilium (v1.14.1)
  addons/cni-canal/canal.yaml
  addons/cni-cilium/cilium.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none

#2862 remove appendix from Apache LICENSE file
  LICENSE
Labels: release-note-none, size/S, lgtm, approved, kind/cleanup, dco-signoff: yes, docs/none

#2861 Fix openstack CCM
  addons/ccm-openstack/ccm-openstack.yaml
  addons/ccm-openstack/generate-values-ccm
  pkg/addons/ensure.go
  pkg/tasks/task.go
  pkg/tasks/tasks.go
  pkg/templates/images/images.go
  test/e2e/cloudprovider.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#2863 Move vSphere CCM RBAC out of List object to apply resources
  addons/ccm-vsphere/ccm-vsphere.yaml
Labels: kind/bug, release-note-none, lgtm, size/M, approved, dco-signoff: yes, kind/regression, docs/none

#2872 add option to skip local storage for autoscaler addon
  addons/cluster-autoscaler/README.md
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: kind/feature, size/XS, lgtm, release-note, approved, ok-to-test, dco-signoff: yes, docs/tbd

#2874 fix default value for autoscaler addon option
  addons/cluster-autoscaler/README.md
  addons/cluster-autoscaler/cluster-autoscaler.yaml
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes, docs/none

#2605 Refactor OpenStack example terraform boilerplate code
  Makefile
  examples/terraform/azure/variables.tf
  examples/terraform/openstack/bastion.tf
  examples/terraform/openstack/control_plane.tf
  examples/terraform/openstack/network.tf
  examples/terraform/openstack/output.tf
  examples/terraform/openstack/variables.tf
  examples/terraform/openstack/versions.tf
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere_flatcar/main.tf
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, needs-ok-to-test, dco-signoff: yes, docs/none

#2875 Use standard release/v1.6 for all upgrade tests
  test/e2e/kubeone.go
  test/e2e/prow.yaml
  test/e2e/scenario_upgrade.go
Labels: release-note-none, lgtm, size/M, approved, kind/failing-test, dco-signoff: yes, docs/none

#2878 [release/v1.6] Migrate to the community-hosted package repositories (`pkgs.k8s.io`) and to `dl.k8s.io`
  pkg/apis/kubeone/helpers.go
  pkg/scripts/os.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/os_flatcar.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.26.0.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlFlatcar.golden
  test/e2e/prow.yaml
  test/tests.yml
Labels: kind/feature, lgtm, size/XL, approved, release-note-action-required, dco-signoff: yes, cherry-pick-approved
