Repository kubermatic/kubeone, pull requests merged in 2023-12, with the labels that each got.

#2978 Use env to determine cluster name used by OpenStack CCM and CSI, increase memory limits and requests for cluster-autoscaler
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  pkg/tasks/probes.go
Labels: kind/bug, size/S, lgtm, approved, priority/critical-urgent, release-note-action-required, dco-signoff: yes, kind/regression, docs/tbd

#2981 Update backup-restic to etcd 3.5.11 and fix addon documentation
  addons/backups-restic/README.md
  addons/backups-restic/backups-restic.yaml
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/provided

#2972 Migrate AzureDisk CSI Node CRB if subject is csi-azuredisk-node-sa
  pkg/addons/ensure.go
  pkg/addons/helpers.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/regression, docs/provided

#2985 Update golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#2986 [release/v1.6] Update golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#2987 [release/v1.7] Update golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#2988 Update Go to 1.21.5 and machine-controller to v1.58.1
  .prow/generated.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  pkg/templates/images/images.go
  test/e2e/helpers.go
  test/e2e/prow.yaml
  test/e2e/sonobuoy.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none

#2989 [release/v1.7] Update Go to 1.21.5 and machine-controller to v1.57.4
  .prow/generated.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  pkg/templates/images/images.go
  test/e2e/helpers.go
  test/e2e/prow.yaml
  test/e2e/sonobuoy.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, cherry-pick-approved
