Repository kubermatic/kubeone, pull requests merged in 2023-05, with the labels that each got.

#2771 [release/v1.3] Actually bind cri-tools version for Ubuntu, CentOS, and Amazon Linux
  pkg/scripts/os.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestRemoveBinariesAmazonLinux.golden
  pkg/scripts/testdata/TestRemoveBinariesCentOS.golden
  pkg/scripts/testdata/TestRemoveBinariesDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes, cherry-pick-approved

#2772 [release/v1.4] Actually bind cri-tools version for Ubuntu, CentOS, and Amazon Linux
  pkg/scripts/os.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-simple.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-force.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmCentOS-proxy.golden
  pkg/scripts/testdata/TestKubeadmCentOS-simple.golden
  pkg/scripts/testdata/TestKubeadmCentOS-v1.16.1.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmDebian-simple.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry_insecure.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-simple.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestRemoveBinariesAmazonLinux.golden
  pkg/scripts/testdata/TestRemoveBinariesCentOS.golden
  pkg/scripts/testdata/TestRemoveBinariesDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes, cherry-pick-approved

#2779 Add changelog for v1.4.14
  CHANGELOG/CHANGELOG-1.4.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none

#2780 [release/v1.4] Add changelog for v1.4.14
  CHANGELOG.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#2783 Replace kubeone-e2e with build image and update Go to 1.20.4
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/bashrc
  hack/images/kubeone-e2e/htoprc
  hack/images/kubeone-e2e/release.sh
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: lgtm, release-note, approved, size/XXL, kind/cleanup, dco-signoff: yes, kind/deprecation, docs/none

#2785 Bump build image to go-1.20-node-18-6
  .prow/postsubmits.yaml
  .prow/verify.yaml
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: release-note-none, lgtm, approved, size/XXL, kind/cleanup, dco-signoff: yes, docs/none

#2784 Disable CSI driver deploy by API flag
  docs/api_reference/v1beta2.en.md
  pkg/addons/ensure.go
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/tbd

#2787 Explicitly configure TLS cert path for machine-controller webhooks
  addons/machinecontroller/deployment-controller.yaml
  addons/machinecontroller/webhook.yaml
  pkg/templates/images/images.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#2789 Render cloudConfig
  pkg/apis/kubeone/config/config.go
  pkg/cmd/initcmd/questions.go
  pkg/credentials/secret.go
  pkg/credentials/secret_test.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/tbd

#2791 bug: remove duplicate err print
  pkg/cmd/root.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, ok-to-test, dco-signoff: yes, docs/none

#2794 rename vsphere vm anti affinity
  examples/terraform/vsphere/main.tf
  examples/terraform/vsphere_centos/main.tf
  examples/terraform/vsphere_flatcar/main.tf
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none
