Repository kubermatic/kubeone, pull requests merged in 2023-07, with the labels that each got.

#2813 Update NodeLocalDNSCache to 1.22.23 and metrics-server to v0.6.3
  pkg/templates/images/images.go
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2812 Add support for Kubernetes 1.27 and update Go to 1.20.5
  .github/ISSUE_TEMPLATE/kubernetes-support.md
  .golangci.yml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  go.mod
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/containerruntime/containerd_config.go
  pkg/containerruntime/containerd_config_test.go
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-docker.io_mirror_registry.golden
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-multi_registry_mirrors.golden
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-override_insecure_registry.golden
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-simple.golden
  pkg/kubeflags/data.go
  pkg/kubeflags/flags.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcar.golden
  pkg/scripts/testdata/TestMigrateToContainerd-insecureRegistry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlFlatcar.golden
  pkg/tasks/containerd.go
  pkg/tasks/kubeadm_env.go
  pkg/templates/images/images.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  test/e2e/helpers.go
  test/e2e/prow.yaml
  test/e2e/testdata/containerd_calico_external.yaml
  test/e2e/testdata/containerd_cilium_external.yaml
  test/e2e/testdata/kube_proxy_ipvs_external.yaml
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/tbd

#2814 CIS benchmark: give kubelet a list of fine ciphersuites.
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubernetesconfigs/kubelet.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#2815 Fix VPC lookup in AWS dualstack examples
  examples/terraform/aws-dualstack/README.md
  examples/terraform/aws-dualstack/main.tf
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2816 Update Hetzner CCM v1.16.0
  addons/ccm-hetzner/ccm-hetzner.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#2817 Update Nutanix CSI v2.6.3
  addons/csi-nutanix/nutanix-csi-storage.yaml
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#2820 Update AWS CCM and EBS CSI driver to support Kubernetes 1.27
  addons/ccm-aws/README.md
  addons/ccm-aws/ccm-aws.yaml
  addons/ccm-aws/generated-values-ccm
  addons/csi-aws-ebs/README.md
  addons/csi-aws-ebs/clusterrole-attacher.yaml
  addons/csi-aws-ebs/clusterrole-csi-node.yaml
  addons/csi-aws-ebs/clusterrole-provisioner.yaml
  addons/csi-aws-ebs/clusterrole-resizer.yaml
  addons/csi-aws-ebs/clusterrole-snapshotter.yaml
  addons/csi-aws-ebs/clusterrolebinding-attacher.yaml
  addons/csi-aws-ebs/clusterrolebinding-csi-node.yaml
  addons/csi-aws-ebs/clusterrolebinding-provisioner.yaml
  addons/csi-aws-ebs/clusterrolebinding-resizer.yaml
  addons/csi-aws-ebs/clusterrolebinding-snapshotter.yaml
  addons/csi-aws-ebs/controller.yaml
  addons/csi-aws-ebs/csi-aws-ebs.yaml
  addons/csi-aws-ebs/csi-snapshot-controller.yaml
  addons/csi-aws-ebs/csidriver.yaml
  addons/csi-aws-ebs/generated-values-csi
  addons/csi-aws-ebs/node.yaml
  addons/csi-aws-ebs/poddisruptionbudget-controller.yaml
  addons/csi-aws-ebs/serviceaccount-csi-controller.yaml
  addons/csi-aws-ebs/serviceaccount-csi-node.yaml
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none

#2819 Update Openstack CCM & CSI to v1.27.1
  addons/ccm-openstack/README.md
  addons/ccm-openstack/ccm-openstack.yaml
  addons/ccm-openstack/generate-values-ccm
  addons/csi-openstack-cinder/README.md
  addons/csi-openstack-cinder/controllerplugin-rbac.yaml
  addons/csi-openstack-cinder/controllerplugin.yaml
  addons/csi-openstack-cinder/driver.yaml
  addons/csi-openstack-cinder/generate-values-csi
  addons/csi-openstack-cinder/nodeplugin-rbac.yaml
  addons/csi-openstack-cinder/nodeplugin.yaml
  addons/csi-openstack-cinder/openstack-csi-cinder.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#2806 Dual Stack support for vSphere
  addons/ccm-vsphere/ccm-vsphere.yaml
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/README.md.in
  examples/terraform/vsphere/outputs.tf
  examples/terraform/vsphere/variables.tf
  pkg/apis/kubeone/validation/validation.go
  pkg/scripts/funcs.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/os_flatcar.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/tbd

#2823 AWS: Remove cloud config from dualstack example configs
  examples/terraform/aws-dualstack/cloud_config.yaml.tftpl
  examples/terraform/aws-dualstack/main.tf
Labels: release-note-none, size/S, lgtm, approved, kind/cleanup, dco-signoff: yes, docs/none

#2824 Migrate PodSelectors for AWS/OpenStack CCM and CSI
  pkg/addons/ensure.go
  pkg/addons/helpers.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes, kind/regression, docs/none

#2825 Update hetzner CCM to v1.17.1
  addons/ccm-hetzner/README.md
  addons/ccm-hetzner/ccm-hetzner.yaml
  addons/ccm-hetzner/generate-values-ccm.yaml
  pkg/addons/ensure.go
  pkg/addons/helpers.go
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#2826 Update vSphere CCM to v1.27.0 and CSI to v3.0.2
  addons/ccm-vsphere/README.md
  addons/ccm-vsphere/ccm-vsphere.yaml
  addons/ccm-vsphere/generate-values-ccm.yaml
  addons/csi-vsphere/vsphere-csi-driver.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none

#2827 Update VMWare VCD CSI driver to 1.4.0
  addons/csi-vmware-cloud-director/csi-controller.yaml
  addons/csi-vmware-cloud-director/csi-driver.yaml
  addons/csi-vmware-cloud-director/csi-node.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#2828 Rename helm values files to avoid rendering them to kube api
  addons/ccm-hetzner/README.md
  addons/ccm-hetzner/generate-values-ccm
  addons/ccm-vsphere/README.md
  addons/ccm-vsphere/generate-values-ccm
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2830 Update Azure CCM to v1.27.6
  addons/ccm-azure/README.md
  addons/ccm-azure/ccm-azure.yaml
  addons/ccm-azure/generate-values-ccm
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none

#2833 Upgrade machine-controller to v1.57.2
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#2836 chartURL field
  .wwhrd.yml
  docs/api_reference/v1beta2.en.md
  go.mod
  go.sum
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/clientutil/crds.go
  pkg/clientutil/wait_pods.go
  pkg/localhelm/helm3.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/containerd.go
  pkg/tasks/task.go
  pkg/templates/externalccm/ccm.go
  pkg/templates/machinecontroller/helper.go
  pkg/templates/operatingsystemmanager/helper.go
  test/e2e/cloudprovider.go
  test/e2e/helpers.go
Labels: kind/bug, lgtm, release-note, size/XL, approved, dco-signoff: yes, docs/none

#2839 Fix installing helm charts containing CRDs
  pkg/localhelm/helm3.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none
