Repository kubermatic/kubeone, pull requests merged in 2023-04, with the labels that each got.

#2751 API token authentication support for VMware Cloud Director
  addons/csi-vmware-cloud-director/vcloud-basic-auth.yaml
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/README.md.in
  examples/terraform/vmware-cloud-director/versions.tf
  pkg/credentials/credentials.go
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#2753 [release/v1.6] Update machine-controller to v1.56.1
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#2754 [release/v1.5] Update machine-controller to v1.54.6
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#2756 Bump Golang version to 1.20.3
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#2757 Bump kubeone-e2e version
  .prow/postsubmits.yaml
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#2759 Run kubeadm preflight checks before the cluster init
  pkg/tasks/prerequisites.go
  pkg/tasks/tasks.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#2758 [release/v1.6] Bump Golang version to 1.19.8
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, cherry-pick-approved

#2760 [release/v1.5] Bump Golang version to 1.19.8
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  hack/images/kubeone-e2e/Dockerfile
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, cherry-pick-approved

#2761 [release/v1.6] Update OSM to 1.2.2 and machine-controller to 1.56.2
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#2762 Update OSM to 1.2.2 and MC to latest
  go.mod
  go.sum
  hack/images/kubeone-e2e/release.sh
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#2768 Add changelogs for v1.6.2 and v1.5.7
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#2769 [release/v1.6] Add the changelog for v1.6.2
  CHANGELOG/CHANGELOG-1.6.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#2770 [release/v1.5] Add the changelog for v1.5.8
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#2775 Use protokol to gather logs
  .prow/postsubmits.yaml
  hack/images/kubeone-e2e/Dockerfile
  hack/images/kubeone-e2e/release.sh
  pkg/tasks/coredns.go
  test/e2e/helpers.go
  test/e2e/protokol.go
  test/e2e/prow.yaml
  test/e2e/scenario_conformance.go
  test/e2e/scenario_install.go
  test/e2e/scenario_upgrade.go
  test/e2e/tests_definitions.go
  test/go-test-e2e.sh
  test/testexec/exec.go
Labels: kind/feature, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, docs/none

#2774 Update hetzner CCM v1.15.0
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none
