Repository kubermatic/kubeone, pull requests merged in 2024-08, with the labels that each got.

#3325 Update machine-controller to latest commit
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#3326 [release/v1.8] Update calico CNI to fix CPU issues
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3327 Update calico CNI to fix CPU issues
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#3328 Set HttpPutResponseHopLimit to 3 by default for AWS nodes
  examples/terraform/aws/README.md
  examples/terraform/aws/main.tf
  examples/terraform/aws/variables.tf
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3307 Add support for kube-apiserver WebhookAuditLog
  docs/api_reference/v1beta2.en.md
  docs/api_reference/v1beta3.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/types.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/features/activate.go
  pkg/features/webhook_audit_log.go
  pkg/scripts/configs.go
  pkg/scripts/configs_test.go
  pkg/scripts/testdata/TestSaveAuditWebhookConfig-kubeone1.golden
  pkg/scripts/testdata/TestSaveAuditWebhookConfig-kubeone2.golden
  pkg/tasks/prerequisites.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes, docs/tbd

#3324 [release/v1.7] Update machine-controller to 1.57.9
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3323 [release/v1.8] Update machine-controller to 1.59.3
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3334 Validate that IP addresses for ControlPlane and StaticWorkers are different
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, release-note, size/M, approved, kind/api-change, dco-signoff: yes, docs/none

#3339 [release/v1.7] CentOS docker repo being abandoned, replaced with RHEL
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/tasks/prerequisites.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3338 [release/v1.7] Remove CentOS 7 tests
  .prow/generated.yaml
  test/e2e/prow.yaml
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, kind/failing-test, dco-signoff: yes, cherry-pick-approved

#3340 Add changelogs for v1.8.2 and v1.7.5
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#3341 [release/v1.8] Add changelog for v1.8.2
  CHANGELOG/CHANGELOG-1.8.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#3342 [release/v1.7] Add changelog for v1.7.5
  CHANGELOG/CHANGELOG-1.7.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#3348 Add `--prune-images` for upgrade process
  pkg/cmd/apply.go
  pkg/cmd/upgrade.go
  pkg/scripts/node.go
  pkg/state/context.go
  pkg/tasks/nodes.go
  pkg/tasks/tasks.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3349 Delete install and upgrade subcommand
  pkg/cmd/install.go
  pkg/cmd/root.go
  pkg/cmd/upgrade.go
Labels: lgtm, size/L, approved, kind/cleanup, release-note-action-required, dco-signoff: yes, docs/provided

#3350 Update to Go 1.23
  .golangci.yml
  .prow/generated.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  Makefile
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/apis/kubeadm/bootstraptoken/v1/utils.go
  pkg/apis/kubeone/config/config_test.go
  pkg/apis/kubeone/helpers_test.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/clientutil/label_test.go
  pkg/clusterstatus/clusterstatus.go
  pkg/cmd/config_test.go
  pkg/cmd/initcmd/init_test.go
  pkg/containerruntime/containerd_config_test.go
  pkg/credentials/credentials_test.go
  pkg/scripts/ccm_csi_migration_test.go
  pkg/scripts/configs_test.go
  pkg/scripts/kubeadm_test.go
  pkg/scripts/os_test.go
  pkg/scripts/proxy_test.go
  pkg/state/cluster_test.go
  pkg/state/context_test.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/certs_test.go
  pkg/tasks/common_test.go
  pkg/tasks/containerd.go
  pkg/tasks/nodes.go
  pkg/tasks/preflight_checks.go
  pkg/tasks/preflight_checks_test.go
  pkg/tasks/tasks.go
  test/e2e/helpers.go
  test/testexec/exec_test.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes, kind/chore, docs/none

#3352 Add Pod PID Limit in Kubelet Configuration
  docs/api_reference/v1beta2.en.md
  docs/api_reference/v1beta3.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/types.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/feature, lgtm, release-note, size/L, approved, kind/api-change, dco-signoff: yes, docs/provided

#3353 Make upgrade e2e tests to use v1beta2
  test/e2e/testdata/containerd_cilium_external_v1beta2.yaml
  test/e2e/testdata/containerd_simple.yaml
  test/e2e/testdata/containerd_simple_external_v1beta2.yaml
  test/e2e/tests_definitions.go
Labels: release-note-none, lgtm, size/M, approved, kind/failing-test, dco-signoff: yes, docs/none

#3357 Fix typo in test configs
  test/e2e/testdata/containerd_cilium_external_v1beta2.yaml
  test/e2e/testdata/containerd_simple_external_v1beta2.yaml
Labels: size/XS, release-note-none, lgtm, approved, kind/failing-test, dco-signoff: yes, docs/none

#3333 Stop defaulting kube-api endpoint
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/config/migrate.go
  pkg/apis/kubeone/config/migrate_test.go
  pkg/apis/kubeone/config/testdata/TestV1Beta2ToV1Beta3Migration-default_api_endpoint.golden
  pkg/apis/kubeone/config/testdata/TestV1Beta2ToV1Beta3Migration-default_api_endpoint_v1beta2.yaml
  pkg/apis/kubeone/config/testdata/TestV1Beta2ToV1Beta3Migration-default_api_endpoint_with_terraform_output.golden
  pkg/apis/kubeone/config/testdata/TestV1Beta2ToV1Beta3Migration-default_api_endpoint_with_terraform_output.tfoutput.json
  pkg/apis/kubeone/config/testdata/TestV1Beta2ToV1Beta3Migration-default_api_endpoint_with_terraform_output_v1beta2.yaml
  pkg/apis/kubeone/v1beta3/defaults.go
  pkg/cmd/config.go
  pkg/terraform/v1beta2/config.go
Labels: lgtm, release-note, size/L, approved, kind/api-change, dco-signoff: yes, docs/none

#3360 Add panic in joinSubnets function
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubeadm/v1beta4/kubeadm.go
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, dco-signoff: yes, docs/none

#3361 Migrate PVC .status.allocatedResourceStatus after upgrade to v1.31
  pkg/tasks/migrations.go
  pkg/tasks/tasks.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3364 Support Kubernetes 1.31: Update Cluster Autoscaler, AWS CCM, AWS CSI
  addons/csi-aws-ebs/aws-csi.yaml
  pkg/templates/images/images.go
Labels: kind/feature, release-note-none, lgtm, size/L, approved, dco-signoff: yes, docs/none

#3365 Support Kubernetes 1.31: Update azure and digital ocean
  addons/csi-azuredisk/csi-azuredisk.yaml
  addons/csi-azurefile/ccm-azurefile.yaml
  pkg/templates/images/images.go
Labels: kind/feature, release-note-none, lgtm, size/L, approved, dco-signoff: yes, docs/none
