Repository kubermatic/kubeone, pull requests merged in 2024-11, with the labels that each got.

#3457 fix(typo): fix typo for machine controller
  pkg/templates/machinecontroller/machines.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#3458 Fix some of bugs discovered in the KubeOne 1.9 testing phase
  addons/cni-cilium/cilium.yaml
  addons/csi-external-snapshotter/webhook.yaml
  examples/terraform/gce/README.md
  examples/terraform/gce/variables.tf
  pkg/addons/applier.go
  test/e2e/helpers.go
Labels: kind/bug, release-note-none, lgtm, size/M, approved, dco-signoff: yes, docs/none

#3461 Fix wrong infrastructure name for openstack_rockylinux_stable
  .prow/generated.yaml
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#3462 terraform: Use gen1-based Ubuntu 24.04 image on Azure
  examples/terraform/azure/README.md
  examples/terraform/azure/variables.tf
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#3463 Undeprecate KubeOneCluster v1beta2 API
  pkg/apis/kubeone/config/config.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#3466 Update links to point to the v1.9 docs
  CHANGELOG/CHANGELOG-1.8.md
  README.md
  addons/README.md
  addons/calico-vxlan/README.md
  addons/cluster-autoscaler/README.md
  addons/cni-cilium/README.md
  docs/README.md
  docs/proposals/20200224-apply.md
  docs/release_process.md
  examples/terraform/aws-dualstack/README.md
  examples/terraform/aws-dualstack/README.md.in
  examples/terraform/aws/README.md
  examples/terraform/aws/README.md.in
  examples/terraform/azure/README.md
  examples/terraform/azure/README.md.in
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/README.md.in
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/README.md.in
  examples/terraform/gce/README.md
  examples/terraform/gce/README.md.in
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/README.md.in
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/README.md.in
  examples/terraform/openstack/README.md
  examples/terraform/openstack/README.md.in
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/README.md.in
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/README.md.in
  examples/terraform/vsphere_centos/README.md
  examples/terraform/vsphere_centos/README.md.in
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/README.md.in
  pkg/cmd/example-manifest.tmpl.yaml
  pkg/cmd/migrate.go
  pkg/tasks/machine_deployments.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: release-note-none, lgtm, size/L, approved, kind/documentation, dco-signoff: yes, docs/none

#3468 Update vmware-vcloud-director Terraform module to 3.14.0
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/versions.tf
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3469 goreleaser: replace --rm-dist flag with --clean
  Makefile
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/chore, docs/none

#3464 Add changelog for v1.9.0
  CHANGELOG/CHANGELOG-1.9.md
  CHANGELOG/README.md
Labels: release-note-none, lgtm, size/L, approved, kind/documentation, dco-signoff: yes, docs/none

#3471 feat(shell-completion): support fish
  pkg/cmd/packaging.go
Labels: kind/feature, size/S, lgtm, release-note, approved, needs-ok-to-test, dco-signoff: yes, docs/tbd
