Repository kubermatic/kubeone, pull requests merged in 2024-06, with the labels that each got.

#3190 add wait feature in helm
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/localhelm/helm3.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3209 Kubernetes 1.30 support
  .github/ISSUE_TEMPLATE/kubernetes-support.md
  .prow/generated.yaml
  Makefile
  pkg/apis/kubeone/validation/validation.go
  pkg/templates/images/images.go
  test/README.md
  test/e2e/scenario_upgrade.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/provided

#3213 Upgrade to latest MC image
  .prow/generated.yaml
  addons/machinecontroller/deployment-controller.yaml
  addons/machinecontroller/webhook.yaml
  go.mod
  go.sum
  pkg/templates/images/images.go
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3214 Update images to support Kubernetes 1.30
  addons/backups-restic/backups-restic.yaml
  addons/ccm-azure/Kustomization
  addons/ccm-digitalocean/Kustomization
  addons/ccm-hetzner/README.md
  addons/ccm-openstack/Kustomization
  addons/ccm-openstack/README.md
  addons/ccm-openstack/ccm-openstack.yaml
  addons/ccm-vsphere/README.md
  addons/ccm-vsphere/ccm-vsphere.yaml
  addons/cni-cilium/Kustomization
  addons/cni-cilium/cilium.yaml
  addons/csi-aws-ebs/README.md
  addons/csi-aws-ebs/aws-csi.yaml
  addons/csi-aws-ebs/snapshot-crds.yaml
  addons/csi-azuredisk/Kustomization
  addons/csi-azuredisk/csi-azuredisk.yaml
  addons/csi-azurefile/README.md
  addons/csi-azurefile/ccm-azurefile.yaml
  addons/csi-digitalocean/Kustomization
  addons/csi-external-snapshotter/controller-rbac.yaml
  addons/csi-external-snapshotter/controller.yaml
  addons/csi-external-snapshotter/crds.yaml
  addons/csi-external-snapshotter/webhook-rbac.yaml
  addons/csi-external-snapshotter/webhook.yaml
  addons/csi-gcp-compute-persistent/Kustomization
  addons/csi-gcp-compute-persistent/README.md
  addons/csi-hetzner/README.md
  addons/csi-hetzner/hcloud-csi.yml
  addons/csi-openstack-cinder/README.md
  addons/csi-openstack-cinder/openstack-csi-cinder.yaml
  addons/csi-vmware-cloud-director/Kustomization
  addons/csi-vsphere/1-vsphere-csi-driver.yaml
  addons/csi-vsphere/2-validatingwebhook.yaml
  addons/metrics-server/README.md
  pkg/templates/images/images.go
Labels: kind/feature, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, docs/none

#3216 update canal to v3.28.0
  addons/cni-canal/Kustomization
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, needs-ok-to-test, dco-signoff: yes, docs/none

#3232 bump GCP CCM to 30.x, using staging images
  addons/ccm-gcp/Kustomization
  addons/ccm-gcp/ccm-gcp.yaml
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#3233 Install apparmor-utils to include apparmor_parser on Hetzner Baremetal Ubuntu Servers
  pkg/scripts/os_debian.go
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3234 Improve the Kubernetes 1.30 support
  .github/ISSUE_TEMPLATE/kubernetes-support.md
  .github/ISSUE_TEMPLATE/update-images.md
  pkg/scripts/kubeadm.go
  pkg/scripts/kubeadm_test.go
  pkg/scripts/os_flatcar.go
  pkg/scripts/os_test.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmUpgrade-leader.golden
  pkg/scripts/testdata/TestKubeadmUpgrade-v1beta2.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/templates/images/images.go
  pkg/templates/kubeadm/kubeadm.go
  pkg/templates/kubeadm/kubeadmv1beta3.go
  test/e2e/testdata/aws_medium.tfvars
Labels: kind/bug, lgtm, release-note, size/L, approved, kind/cleanup, dco-signoff: yes, docs/none

#3240 Fix Helm Release Timeout Issue
  docs/api_reference/v1beta2.en.md
  docs/api_reference/v1beta3.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/v1beta3/defaults.go
  pkg/apis/kubeone/v1beta3/types.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/localhelm/helm3.go
Labels: kind/bug, lgtm, release-note, size/M, approved, kind/api-change, dco-signoff: yes, docs/none

#3243 Fix local helm releases deletion issue
  pkg/apis/kubeone/validation/validation.go
  pkg/localhelm/helm3.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3251 Refactor the upgrade process to stop using config on upgrade
  pkg/scripts/kubeadm.go
  pkg/scripts/kubeadm_test.go
  pkg/scripts/testdata/TestKubeadmUpgrade-leader.golden
  pkg/scripts/testdata/TestKubeadmUpgrade-v1beta2.golden
  pkg/tasks/kubeadm_config.go
  pkg/tasks/kubeadm_upgrade.go
  pkg/tasks/tasks.go
  pkg/templates/kubeadm/kubeadm.go
  pkg/templates/kubeadm/kubeadmv1beta3.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
Labels: kind/feature, lgtm, release-note, size/L, approved, kind/design, dco-signoff: yes, docs/none

#3265 Use the same bastion_type on AWS as worker_type
  test/e2e/testdata/aws_rhel.tfvars
  test/e2e/testdata/aws_small.tfvars
  test/e2e/testdata/aws_stable_medium.tfvars
  test/e2e/testdata/aws_stable_small.tfvars
Labels: size/XS, release-note-none, lgtm, approved, kind/flake, dco-signoff: yes, docs/none

#3264 [release/v1.8] Fix bastion type in AWS E2E tests
  test/e2e/testdata/aws_rhel.tfvars
  test/e2e/testdata/aws_small.tfvars
  test/e2e/testdata/aws_stable_medium.tfvars
  test/e2e/testdata/aws_stable_small.tfvars
Labels: size/XS, release-note-none, lgtm, approved, kind/failing-test, dco-signoff: yes, cherry-pick-approved

#3266 Increase TEST_TIMEOUT to 90m for stable tests infrastructure
  .prow/generated.yaml
  test/e2e/tests_definitions.go
Labels: release-note-none, lgtm, size/L, approved, kind/flake, dco-signoff: yes, docs/none

#3269 Bind csi-snapshotter to v8.0.1
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, kind/cleanup, dco-signoff: yes, docs/none

#3271 Fix openstack CCM addon
  addons/ccm-openstack/Kustomization
  addons/ccm-openstack/README.md
  addons/ccm-openstack/ccm-openstack.yaml
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3273 Fix snapshot-webhook admitting non-supported objects and add default VolumeSnapshotClass for all supported providers
  addons/csi-external-snapshotter/webhook.yaml
  addons/default-storage-class/storage-class.yaml
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, kind/regression, docs/none

#3272 Be explicit about bastion type, as not all OSes support nano size
  test/e2e/testdata/aws_medium.tfvars
  test/e2e/testdata/aws_rhel.tfvars
  test/e2e/testdata/aws_small.tfvars
  test/e2e/testdata/aws_stable_medium.tfvars
  test/e2e/testdata/aws_stable_small.tfvars
Labels: size/XS, release-note-none, lgtm, approved, kind/failing-test, dco-signoff: yes, docs/none

#3277 VCD: Add bastion host to terraform configs
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/main.tf
  examples/terraform/vmware-cloud-director/output.tf
  examples/terraform/vmware-cloud-director/variables.tf
  test/e2e/testdata/vmware-cloud-director.tfvars
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#3282 Don't downgrade GCP CCM for v1.27 clusters
  pkg/templates/images/images.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/regression, docs/none

#3286 Add changelog for v1.8.1
  CHANGELOG/CHANGELOG-1.8.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#3290 Remove release date for 1.8.1
  CHANGELOG/CHANGELOG-1.8.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none
