Repository kubermatic/kubeone, pull requests merged in 2024-01, with the labels that each got.

#2992 Update KubeOne container image to Go 1.21.5
  Dockerfile
Labels: kind/feature, size/XS, release-note-none, lgtm, approved, dco-signoff: yes, docs/none

#2991 Make credentials file take precedence over environment.
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
Labels: kind/bug, lgtm, size/L, approved, release-note-action-required, dco-signoff: yes, docs/none

#2995 Add changelog for v1.7.2
  CHANGELOG/CHANGELOG-1.7.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#3000 Fix helm deploying resources in the wrong namespace
  pkg/localhelm/helm3.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3002 Update etcd to v3.5.10 if needed
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm_test.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/regression, docs/none

#3005 fix strictArp field usage
  pkg/apis/kubeone/config/testdata/config-full-v1beta1.yaml
  pkg/apis/kubeone/config/testdata/config-full-v1beta2.golden
  pkg/cmd/config.go
Labels: size/XS, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes, kind/chore, docs/none

#3013 Update AWS CSI driver
  addons/csi-aws-ebs/README.md
  addons/csi-aws-ebs/aws-csi.yaml
  addons/csi-aws-ebs/crd-volumesnapshotclasses.yaml
  addons/csi-aws-ebs/crd-volumesnapshotcontents.yaml
  addons/csi-aws-ebs/crd-volumesnapshots.yaml
  addons/csi-aws-ebs/csi-snapshot-controller.yaml
  addons/csi-aws-ebs/csi-snapshot-webhook.yaml
  addons/csi-aws-ebs/rbac-snapshot-controller.yaml
  addons/csi-aws-ebs/snapshot-crds.yaml
  pkg/addons/applier.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3014 Update OpenStack CCM / CSI driver
  addons/ccm-openstack/README.md
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#3016 Extract csi-external-snapshotter
  addons/csi-aws-ebs/csi-snapshot-controller.yaml
  addons/csi-aws-ebs/csi-snapshot-webhook.yaml
  addons/csi-azuredisk/ccm-azuredisk.yaml
  addons/csi-azurefile/ccm-azurefile.yaml
  addons/csi-digitalocean/crds.yaml
  addons/csi-digitalocean/snapshot-controller.yaml
  addons/csi-digitalocean/snapshot-validation-webhook.yaml
  addons/csi-external-snapshotter/controller-rbac.yaml
  addons/csi-external-snapshotter/controller.yaml
  addons/csi-external-snapshotter/crds.yaml
  addons/csi-external-snapshotter/webhook-rbac.yaml
  addons/csi-external-snapshotter/webhook.yaml
  addons/csi-gcp-compute-persistent/crds.yaml
  addons/csi-gcp-compute-persistent/rbac-snapshot-controller.yaml
  addons/csi-gcp-compute-persistent/rbac-snapshot-webhook.yaml
  addons/csi-gcp-compute-persistent/snapshot-webhook.yaml
  addons/csi-nutanix/README.md
  addons/csi-nutanix/nutanix-csi-snapshot.yaml
  addons/csi-nutanix/nutanix-webhook-certs.yaml
  addons/csi-openstack-cinder/snapshot-controller.yaml
  addons/csi-vsphere/crd-volumesnapshotclasses.yaml
  addons/csi-vsphere/crd-volumesnapshotcontents.yaml
  addons/csi-vsphere/crd-volumesnapshots.yaml
  addons/csi-vsphere/csi-snapshot-validatingwebhook.yaml
  addons/csi-vsphere/snapshot-controller-rbac.yaml
  addons/csi-vsphere/snapshot-controller.yaml
  pkg/addons/ensure.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, approved, size/XXL, kind/cleanup, dco-signoff: yes, docs/none

#3018 vSphere CSI / CPI upgrade
  addons/ccm-vsphere/README.md
  addons/ccm-vsphere/ccm-vsphere.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none
