Repository kubermatic/kubeone, pull requests merged in 2024-09, with the labels that each got.

#3367 Default addons field, fixes NPE
  pkg/apis/kubeone/v1beta3/defaults.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3370 Replace deprecated Hetzner (in fact, restricted) default cx21 instance type with cx22
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/variables.tf
Labels: size/XS, lgtm, approved, release-note-action-required, dco-signoff: yes, kind/regression, docs/none

#3378 [release/v1.8] Update vSphere images to use upstream image repository or our mirror
  pkg/templates/images/images.go
Labels: kind/bug, size/S, lgtm, approved, priority/critical-urgent, release-note-action-required, dco-signoff: yes, kind/regression, cherry-pick-approved

#3377 [release/v1.7] Update vSphere images to use upstream image repository or our mirror
  pkg/templates/images/images.go
Labels: kind/bug, size/S, lgtm, approved, priority/critical-urgent, release-note-action-required, dco-signoff: yes, kind/regression, cherry-pick-approved

#3379 Add changelogs for v1.8.3 and v1.7.6
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/CHANGELOG-1.8.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none

#3381 [release/v1.8] Add changelog for v1.8.3
  CHANGELOG/CHANGELOG-1.8.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#3380 [release/v1.7] Add changelog for v1.7.6
  CHANGELOG/CHANGELOG-1.7.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#3382 Fetch the latest Kubernetes version in tests
  .prow/generated.yaml
  test/e2e/helpers.go
  test/e2e/scenario_conformance.go
  test/e2e/scenario_install.go
  test/e2e/scenario_migrate_csi_ccm.go
  test/e2e/scenario_upgrade.go
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3383 Rerun failed Kubernetes conformance tests
  test/e2e/helpers.go
  test/e2e/sonobuoy.go
Labels: release-note-none, lgtm, size/M, approved, kind/failing-test, dco-signoff: yes, docs/none

#3385 [release/v1.7] Rerun failed Kubernetes conformance tests
  test/e2e/helpers.go
  test/e2e/sonobuoy.go
Labels: release-note-none, lgtm, size/M, approved, kind/failing-test, dco-signoff: yes, cherry-pick-approved

#3386 Fix rerunning failed conformance tests
  .prow/generated.yaml
  test/e2e/helpers.go
  test/e2e/sonobuoy.go
  test/e2e/tests_definitions.go
  test/go-test-e2e.sh
Labels: release-note-none, lgtm, approved, size/XXL, kind/failing-test, dco-signoff: yes, docs/none

#3387 Update the Kubernetes-related issue templates
  .github/ISSUE_TEMPLATE/kubernetes-support.md
  .github/ISSUE_TEMPLATE/update-images.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#3389 [release/v1.7] Fix rerunning failed conformance tests
  .prow/generated.yaml
  test/e2e/helpers.go
  test/e2e/prow.yaml
  test/e2e/sonobuoy.go
  test/e2e/tests_definitions.go
  test/go-test-e2e.sh
Labels: release-note-none, lgtm, approved, size/XXL, kind/failing-test, dco-signoff: yes, cherry-pick-approved

#3392 Add device_ownership_from_security_context containerd CRI config option
  docs/api_reference/v1beta2.en.md
  docs/api_reference/v1beta3.en.md
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/v1beta3/defaults.go
  pkg/apis/kubeone/v1beta3/types.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/initcmd/generate.go
  pkg/containerruntime/containerd_config.go
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-docker.io_mirror_registry.golden
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-multi_registry_mirrors.golden
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-override_insecure_registry.golden
  pkg/containerruntime/testdata/Test_marshalContainerdConfig-simple.golden
  pkg/localhelm/helm3.go
  pkg/pointer/pointer.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.26.0.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcar.golden
  pkg/scripts/testdata/TestMigrateToContainerd-insecureRegistry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-simple.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlFlatcar.golden
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/tbd

#3404 Add a testing issue generator
  go.mod
  go.sum
  test/e2e/helpers.go
  test/e2e/scenario_conformance.go
  test/e2e/scenario_install.go
  test/e2e/scenario_migrate_csi_ccm.go
  test/e2e/scenario_upgrade.go
  test/e2e/tests_definitions.go
  test/generator/github.go
  test/generator/main.go
Labels: kind/feature, release-note-none, lgtm, size/L, approved, dco-signoff: yes, docs/tbd

#3398 Ensure disable_auto_update is used for all E2E tests, add disable_auto_update for Equinix Metal
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/main.tf
  examples/terraform/equinixmetal/output.tf
  examples/terraform/equinixmetal/userdata_flatcar_upgrades.json
  examples/terraform/equinixmetal/variables.tf
  test/e2e/testdata/openstack_flatcar.tfvars
  test/e2e/tests_definitions.go
Labels: lgtm, release-note, size/M, approved, kind/flake, dco-signoff: yes, docs/none
