Repository kubermatic/kubeone, pull requests merged in 2024-04, with the labels that each got.

#3100 Fix kubelet file permissions according to CIS 1.8
  pkg/addons/manifest.go
  pkg/tasks/files.go
  pkg/tasks/tasks.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/regression, docs/none

#3106 Initialize host.Labels to avoid NPE
  pkg/tasks/nodes.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#3127 Add missing E2E tests
  .prow/generated.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#3130 Fix GCE in-tree upgrade test
  .prow/generated.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, size/S, lgtm, approved, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#3137 Fix upgrade tests
  .prow/generated.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#3138 Fix file permissions setting on flatcar
  pkg/executor/executorfs/fs.go
  pkg/tasks/files.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none, code-freeze-approved

#3139 Fix DigitalOcean CSI driver
  addons/csi-digitalocean/Kustomization
  addons/csi-digitalocean/driver.yaml
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#3142 Run E2E with verbose flag to see the logs output
  hack/run-ci-e2e-test.sh
  test/go-test-e2e.sh
Labels: release-note-none, lgtm, size/L, approved, kind/flake, dco-signoff: yes, docs/none, code-freeze-approved

#3144 Update and kustomize csi-azuredisk addon
  addons/ccm-azure/Kustomization
  addons/ccm-azure/README.md
  addons/ccm-azure/ccm-azure.yaml
  addons/ccm-azure/helm-values
  addons/csi-azuredisk/Kustomization
  addons/csi-azuredisk/README.md
  addons/csi-azuredisk/ccm-azuredisk.yaml
  addons/csi-azuredisk/csi-azuredisk.yaml
  addons/csi-azuredisk/helm-values
  pkg/templates/images/images.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#3146 Clean `yum` caches when configuring repos
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.26.0.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none, backport-needed, code-freeze-approved

#3149 Move Azure terraform example to Standard SKU for IP addresses
  examples/terraform/azure/README.md
  examples/terraform/azure/main.tf
  examples/terraform/azure/output.tf
  examples/terraform/azure/variables.tf
  pkg/templates/machinecontroller/cloudprovider_specs.go
  pkg/terraform/v1beta2/update.go
  test/e2e/tests_definitions.go
  test/go-test-e2e.sh
Labels: kind/feature, lgtm, size/M, approved, release-note-action-required, dco-signoff: yes, kind/regression, docs/none, code-freeze-approved

#3150 Fix azuredisk CSI hostNetwork
  addons/csi-azuredisk/csi-azuredisk.yaml
  addons/csi-azuredisk/helm-values
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#3152 Allow overriding interface used by Flannel and refactor network creation in example Terraform configs for Hetzner
  addons/cni-canal/Kustomization
  addons/cni-canal/canal-config.yaml
  addons/cni-canal/canal.yaml
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/variables.tf
Labels: kind/feature, lgtm, size/M, approved, release-note-action-required, dco-signoff: yes, docs/tbd, code-freeze-approved

#3154 Azure CCM crashloop fix
  .prow/generated.yaml
  addons/ccm-azure/Kustomization
  addons/ccm-azure/ccm-azure.yaml
  addons/ccm-azure/helm-values
  examples/terraform/azure/README.md
  examples/terraform/azure/variables.tf
  test/tests.yml
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/regression, docs/none, code-freeze-approved

#3155 Use Load Balancer for Hetzner E2E tests
  test/e2e/helpers.go
  test/e2e/scenario_conformance.go
  test/e2e/scenario_install.go
  test/e2e/scenario_upgrade.go
  test/e2e/testdata/containerd_simple_external.yaml
  test/e2e/testdata/legacy_machine_controller_containerd_external.yaml
Labels: release-note-none, size/S, lgtm, approved, kind/failing-test, dco-signoff: yes, docs/tbd, code-freeze-approved

#3157 Bind FLANNELD_IFACE statically to status.hostIP
  addons/cni-canal/Kustomization
  addons/cni-canal/canal.yaml
  test/e2e/testdata/containerd_simple_external.yaml
  test/e2e/testdata/legacy_machine_controller_containerd_external.yaml
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none, code-freeze-approved

#3159 Fix initKubeOneVersion for v1.27 E2E tests
  .prow/generated.yaml
  test/tests.yml
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, priority/critical-urgent, dco-signoff: yes, docs/none, code-freeze-approved

#3160 Increase version constraint for Azure with in-tree provider
  pkg/apis/kubeone/validation/validation.go
Labels: size/XS, release-note-none, lgtm, approved, priority/critical-urgent, dco-signoff: yes, kind/regression, docs/none, code-freeze-approved

#3164 [release/v1.6] bump OSM to 1.2.5
  pkg/templates/images/images.go
Labels: kind/bug, size/XS, lgtm, approved, release-note-action-required, dco-signoff: yes, cherry-pick-approved, code-freeze-approved

#3163 [release/v1.7] bump OSM to 1.3.5
  pkg/templates/images/images.go
Labels: kind/bug, size/XS, lgtm, approved, release-note-action-required, dco-signoff: yes, cherry-pick-approved, code-freeze-approved

#3165 Bump OSM to v1.5.1
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved
