Repository kubermatic/kubeone, pull requests merged in 2024-05, with the labels that each got.

#3169 [release/v1.6] CHANGELOG: Add changelog for v1.6.6
  CHANGELOG/CHANGELOG-1.6.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved, code-freeze-approved

#3168 [release/v1.7] CHANGELOG: Add changelog for v1.7.4
  CHANGELOG/CHANGELOG-1.7.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved, code-freeze-approved

#3172 bump OSM to v1.5.2
  pkg/templates/images/images.go
Labels: size/XS, lgtm, approved, release-note-action-required, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#3170 [release/v1.6] bump OSM to v1.2.6
  pkg/templates/images/images.go
Labels: size/XS, lgtm, approved, release-note-action-required, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#3171 [release/v1.7] bump OSM to v1.3.6
  pkg/templates/images/images.go
Labels: size/XS, lgtm, approved, release-note-action-required, dco-signoff: yes, kind/chore, cherry-pick-approved, code-freeze-approved

#3173 Fix incorrect args for AWS and Azure CCM
  addons/ccm-aws/ccm-aws.yaml
  addons/ccm-azure/Kustomization
  addons/ccm-azure/ccm-azure.yaml
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes, kind/regression, docs/none, code-freeze-approved

#3181 Use kube-system namespace for CSI snapshotter on vSphere
  pkg/addons/applier.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/regression, docs/none, code-freeze-approved

#3183 silence warning about unset logger in e2e tests
  test/e2e/helpers.go
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#3162 Support for passing additional args to API server, controller manager, and scheduler
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm_test.go
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes, docs/tbd, code-freeze-approved

#3184 Update machine-controller to v1.59.1 and remove fields added in v1.29 from kubelet and kubeproxy configs
  pkg/templates/images/images.go
  pkg/templates/kubernetesconfigs/kubelet.go
  pkg/templates/kubernetesconfigs/kubeproxy.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#3185 Update OWNERS to sig-cluster-management
  OWNERS
  OWNERS_ALIASES
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#3187 Sort files in csi-vsphere addon, fix tests
  .prow/generated.yaml
  addons/csi-vsphere/1-vsphere-csi-driver.yaml
  addons/csi-vsphere/2-validatingwebhook.yaml
  addons/csi-vsphere/3-poddisruptionbudgets.yaml
  test/e2e/helpers.go
  test/e2e/tests_definitions.go
  test/go-test-e2e.sh
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#3180 Add 1.8 changelog
  CHANGELOG/CHANGELOG-1.8.md
Labels: release-note-none, lgtm, size/L, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#3191 Reintroduce ip_range variable for Hetzner configs
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/main.tf
  examples/terraform/hetzner/variables.tf
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#3192 Update docs links to v1.8
  README.md
  addons/README.md
  addons/calico-vxlan/README.md
  addons/cluster-autoscaler/README.md
  addons/cni-cilium/README.md
  docs/README.md
  docs/proposals/20200224-apply.md
  docs/release_process.md
  examples/terraform/aws-dualstack/README.md
  examples/terraform/aws-dualstack/README.md.in
  examples/terraform/aws/README.md
  examples/terraform/aws/README.md.in
  examples/terraform/azure/README.md
  examples/terraform/azure/README.md.in
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/README.md.in
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/README.md.in
  examples/terraform/gce/README.md
  examples/terraform/gce/README.md.in
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/README.md.in
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/README.md.in
  examples/terraform/openstack/README.md
  examples/terraform/openstack/README.md.in
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/README.md.in
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/README.md.in
  examples/terraform/vsphere_centos/README.md
  examples/terraform/vsphere_centos/README.md.in
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/README.md.in
  pkg/cmd/config.go
  pkg/cmd/migrate.go
  pkg/tasks/machine_deployments.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#3193 Cleanup changelog for v1.8
  CHANGELOG/CHANGELOG-1.8.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none, code-freeze-approved

#3195 Add link to the v1.8 changelog
  CHANGELOG/README.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none, code-freeze-approved

#3194 [release/v1.8] Remove non-v1.8 changelogs
  CHANGELOG/CHANGELOG-0.x.md
  CHANGELOG/CHANGELOG-1.0.md
  CHANGELOG/CHANGELOG-1.1.md
  CHANGELOG/CHANGELOG-1.2.md
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-1.7.md
  CHANGELOG/README.md
Labels: release-note-none, lgtm, approved, size/XXL, kind/documentation, dco-signoff: yes, cherry-pick-approved, code-freeze-approved

#3199 Update canal to v3.27.3
  addons/cni-canal/Kustomization
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/regression, docs/none, code-freeze-approved

#3203 Hackathon 2024 UI
  go.mod
  go.sum
  pkg/clusterstatus/clusterstatus.go
  pkg/cmd/root.go
  pkg/cmd/ui.go
  pkg/dashboard/assets/favicon.png
  pkg/dashboard/assets/kubeone-logo.png
  pkg/dashboard/index.html
  pkg/dashboard/server.go
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes, docs/tbd

#3207 Fix default rockylinux EC2 image filter query in AWS terraform
  examples/terraform/aws/README.md
  examples/terraform/aws/variables.tf
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/regression, docs/none
