Repository kubermatic/kubeone, pull requests merged in 2024-02, with the labels that each got.

#3023 Update GCP CSI Driver
  addons/csi-gcp-compute-persistent/Kustomization
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#3024 Update unattended-upgrades
  addons/unattended-upgrades/README.md
  addons/unattended-upgrades/apt.yaml
  addons/unattended-upgrades/fluo.yaml
  addons/unattended-upgrades/fluo/Kustomization
  addons/unattended-upgrades/kured.yaml
  addons/unattended-upgrades/yum.yaml
Labels: lgtm, size/L, approved, release-note-action-required, dco-signoff: yes, kind/chore, docs/none

#3025 Update restic addon
  addons/backups-restic/backups-restic.yaml
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#3026 Update DigitalOcean CSI driver
  addons/csi-digitalocean/Kustomization
  addons/csi-digitalocean/README.md
  addons/csi-digitalocean/driver.yaml
  addons/default-storage-class/storage-class.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3028 Update Equinix Metal CCM
  addons/ccm-equinixmetal/Kustomization
  addons/ccm-equinixmetal/README.md
  addons/ccm-equinixmetal/base/secret.yaml
  addons/ccm-equinixmetal/ccm-equinixmetal.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none

#3027 Update digitalocean CCM
  addons/ccm-digitalocean/Kustomization
  addons/ccm-digitalocean/README.md
  addons/ccm-digitalocean/ccm-digitalocean.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none

#3030 fix: preserve containerd runtime config
  pkg/apis/kubeone/v1beta2/defaults.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, needs-ok-to-test, dco-signoff: yes, docs/none

#3029 Update nutanix CSI
  addons/csi-nutanix/.gitignore
  addons/csi-nutanix/Kustomization
  addons/csi-nutanix/README.md
  addons/csi-nutanix/generate-values-csi-snapshot
  addons/csi-nutanix/nutanix-csi-storage.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes, kind/chore, docs/none

#3031 Update VMWare Cloud Director CSI driver
  addons/csi-vmware-cloud-director/Kustomization
  addons/csi-vmware-cloud-director/README.md
  addons/csi-vmware-cloud-director/base/vcloud-csi-config.yaml
  addons/csi-vmware-cloud-director/csi-controller.yaml
  addons/csi-vmware-cloud-director/csi-driver.yaml
  addons/csi-vmware-cloud-director/csi-node.yaml
  addons/csi-vmware-cloud-director/driver.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes, kind/chore, docs/none

#3034 Add Nutanix CCM addon
  addons/ccm-nutanix/.gitignore
  addons/ccm-nutanix/Kustomization
  addons/ccm-nutanix/README.md
  addons/ccm-nutanix/nutanix-ccm.yaml
  addons/ccm-nutanix/nutanix-config.yaml
  addons/ccm-nutanix/values
  pkg/addons/ensure.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#3036 Build using Go 1.22
  .prow/generated.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  pkg/clientutil/create_or_update.go
  pkg/cmd/addons.go
  pkg/cmd/apply.go
  pkg/cmd/config.go
  pkg/cmd/init.go
  pkg/cmd/install.go
  pkg/cmd/kubeconfig.go
  pkg/cmd/local.go
  pkg/cmd/packaging.go
  pkg/cmd/reset.go
  pkg/tasks/ccm_csi_migration.go
  pkg/tasks/certs.go
  pkg/tasks/controlplane.go
  pkg/tasks/nodes.go
  pkg/tasks/prerequisites.go
  pkg/tasks/util.go
  test/e2e/cloudprovider.go
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3035 Replace JSON6902 with Strategic Merge in Nutanix CSI driver
  addons/csi-nutanix/Kustomization
  addons/csi-nutanix/README.md
  addons/csi-nutanix/nutanix-csi-storage.yaml
  addons/csi-nutanix/poddisruptionbudget.yaml
Labels: lgtm, release-note, size/L, approved, kind/cleanup, dco-signoff: yes, docs/none

#3038 Add GCP CCM
  .prow/generated.yaml
  addons/ccm-gcp/Kustomization
  addons/ccm-gcp/README.md
  addons/ccm-gcp/ccm-gcp.yaml
  pkg/addons/ensure.go
  pkg/apis/kubeone/helpers.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  pkg/templates/resources/resources.go
  test/e2e/prow.yaml
  test/e2e/tests_test.go
  test/go-test-e2e.sh
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none

#3039 Update and kustomize nodelocaldns
  addons/nodelocaldns/Kustomization
  addons/nodelocaldns/README.md
  addons/nodelocaldns/nodelocaldns.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none

#3040 Fix: Use containerd binary from path in Flatcar
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlFlatcar.golden
Labels: kind/bug, size/S, lgtm, release-note, approved, needs-ok-to-test, dco-signoff: yes, docs/none

#3043 Fix flatcar torcx issues
  pkg/tasks/probes.go
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/regression, docs/none

#3041 [release/v1.7] Fix Flatcar torcx issues
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlFlatcar.golden
  pkg/tasks/probes.go
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/regression, cherry-pick-approved

#3042 [release/v1.6] Fix Flatcar torcx issues
  pkg/scripts/render.go
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestMigrateToContainerd-flatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlFlatcar.golden
  pkg/tasks/probes.go
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/regression, cherry-pick-approved

#3045 Update helm to v3.14.1
  go.mod
  go.sum
  pkg/features/activate.go
  pkg/features/psp.go
  test/e2e/cloudprovider.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/regression, docs/none

#3046 Update metrics-server to v0.7.0
  addons/metrics-server/.gitignore
  addons/metrics-server/Kustomization
  addons/metrics-server/README.md
  addons/metrics-server/metrics-server.yaml
  addons/metrics-server/poddisruptionbudget.yaml
  addons/metrics-server/secret.yaml
  addons/metrics-server/values
  pkg/addons/ensure.go
  pkg/addons/helpers.go
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none

#3052 Improve error messaging when working with remote files over SSH
  pkg/executor/executorfs/fs.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3056 Update and kustomize AWS CCM
  addons/ccm-aws/.gitignore
  addons/ccm-aws/Kustomization
  addons/ccm-aws/README.md
  addons/ccm-aws/ccm-aws.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none
