Repository kubermatic/kubeone, pull requests merged in 2024-03, with the labels that each got.

#3057 Update machine-controller to v1.57.5
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3058 Update machine-controller to v1.56.6
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3061 Add changelogs for v1.7.3 and v1.6.5, and fix the changelog generation script
  CHANGELOG/CHANGELOG-1.6.md
  CHANGELOG/CHANGELOG-1.7.md
  hack/generate-changelog.sh
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#3062 [release/v1.6] Add changelog for v1.6.5
  CHANGELOG/CHANGELOG-1.6.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#3060 [release/v1.7] Update Go to 1.21.6
  .prow/generated.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  test/e2e/helpers.go
  test/e2e/prow.yaml
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, cherry-pick-approved

#3063 [release/v1.7] Add changelog for v1.7.3
  CHANGELOG/CHANGELOG-1.7.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#3059 Update machine-controller to v1.59.0-beta.0
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#3064 [release/v1.7] Update MC to v1.57.6
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3065 fix: Deploy User defined addons before external CCM initialization
  pkg/tasks/tasks.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3048 Add initial support for kubernetes 1.29
  .prow/generated.yaml
  docs/api_reference/v1beta2.en.md
  pkg/addons/ensure.go
  pkg/apis/kubeone/config/testdata/config-full-v1beta1.yaml
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
  pkg/cmd/config.go
  pkg/kubeflags/data.go
  pkg/kubeflags/flags.go
  pkg/scripts/os.go
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/os_flatcar.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-force.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmFlatcar-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIFlatcar.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  test/e2e/prow.yaml
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3072 update to Go 1.22.1
  .prow/generated.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  test/e2e/helpers.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3073 Make default stable kubernetes version == v1.29
  Makefile
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#3070 add logging to label step
  pkg/tasks/nodes.go
Labels: size/XS, release-note-none, lgtm, approved, kind/cleanup, dco-signoff: yes, docs/none

#3055 Canal & Calico CNI update
  addons/calico-vxlan/Kustomization
  addons/calico-vxlan/README.md
  addons/calico-vxlan/calico-config.yaml
  addons/calico-vxlan/calico-vxlan.yaml
  addons/cni-canal/Kustomization
  addons/cni-canal/README.md
  addons/cni-canal/canal-config.yaml
  addons/cni-canal/canal.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3080 Cleanup e2e tests after introduction of kubernetes v1.29
  .prow/generated.yaml
  pkg/apis/kubeone/validation/validation_test.go
  test/e2e/testdata/containerd_calico.yaml
  test/e2e/testdata/containerd_cilium.yaml
  test/e2e/testdata/containerd_weave.yaml
  test/e2e/testdata/legacy_machine_controller_containerd.yaml
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, kind/cleanup, dco-signoff: yes, docs/none

#3076 fix: debian apt-get update running before configuring repositories
  pkg/scripts/os_debian.go
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/tbd

#3081 New API to configure TLS cipher suites for kube-apiserver, etcd and kubelet
  docs/api_reference/v1beta2.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta1/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/cmd/config.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubeadm/v1beta3/kubeadm_test.go
  pkg/templates/kubernetesconfigs/kubelet.go
  pkg/templates/kubernetesconfigs/tls.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#3086 Update cluster-autoscaler with scale from zero instructions
  addons/cluster-autoscaler/README.md
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none

#3087 Follow up kubernets 1.29 support fixes
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/validation/validation.go
Labels: release-note-none, size/S, lgtm, approved, dco-signoff: yes, kind/regression, docs/none

#3090 E2E test upgrades of 1.28+ with main branch
  .prow/generated.yaml
  test/e2e/tests_test.go
  test/tests.yml
Labels: release-note-none, lgtm, size/L, approved, kind/cleanup, dco-signoff: yes, docs/none

#3089 Update cilium to v1.15
  .prow/generated.yaml
  addons/.gitignore
  addons/ccm-nutanix/.gitignore
  addons/cni-cilium/Kustomization
  addons/cni-cilium/README.md
  addons/cni-cilium/cilium-config-map.yaml
  addons/cni-cilium/cilium.yaml
  addons/cni-cilium/helm-values
  addons/cni-cilium/hubble.yaml
  addons/csi-nutanix/.gitignore
  addons/metrics-server/.gitignore
  pkg/templates/images/images.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3091 add preflight check for hostnames
  pkg/tasks/preflight_checks.go
  pkg/tasks/preflight_checks_test.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3075 Update CSI feature gates
  addons/ccm-gcp/Kustomization
  addons/ccm-gcp/ccm-gcp.yaml
  pkg/apis/kubeone/helpers.go
  pkg/apis/kubeone/validation/validation.go
  pkg/cmd/migrate.go
  pkg/state/context_test.go
  pkg/tasks/probes.go
Labels: lgtm, release-note, size/L, approved, kind/cleanup, dco-signoff: yes, docs/provided
