Repository kubermatic/kubeone, pull requests merged in 2025-02, with the labels that each got.

#3538 Cleanup stale objects
  go.mod
  go.sum
  pkg/tasks/cleanup.go
  pkg/tasks/tasks.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#3550 Add changelog for v1.9.2
  CHANGELOG/CHANGELOG-1.9.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none

#3555 Add changelog for v1.8.6
  CHANGELOG/CHANGELOG-1.8.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none

#3556 [release/v1.8] Add changelog for v1.8.6
  CHANGELOG/CHANGELOG-1.8.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, cherry-pick-approved

#3560 Add caBundle volume mounts to backups-restic addon
  addons/backups-restic/backups-restic.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none
