Repository kubermatic/kubeone, pull requests merged in 2025-07, with the labels that each got.

#3732 Update HetznerCCM to the v1.26.0
  addons/ccm-hetzner/Kustomization
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none, code-freeze-approved

#3731 GCE cloud fixes
  addons/ccm-gcp/Kustomization
  addons/ccm-gcp/ccm-gcp.yaml
  addons/csi-gcp-compute-persistent/Kustomization
  addons/csi-gcp-compute-persistent/README.md
  addons/csi-gcp-compute-persistent/csi-gcp-compute-persistent.yaml
  pkg/templates/images/images.go
Labels: kind/bug, release-note-none, lgtm, approved, size/XXL, dco-signoff: yes, docs/none, code-freeze-approved

#3709 Cleanup E2E tests
  .prow/generated.yaml
  test/e2e/scenario_migrate_csi_ccm.go
  test/e2e/tests_definitions.go
  test/e2e/tests_test.go
  test/generator/github.go
  test/tests.yml
Labels: release-note-none, lgtm, approved, size/XXL, kind/cleanup, dco-signoff: yes, docs/none, code-freeze-approved

#3739 [release/v1.10] Bump OSM to v1.6.7
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3742 Define missing CiliumEnvoy image
  pkg/templates/images/images.go
Labels: kind/bug, release-note-none, lgtm, approved, dco-signoff: yes, docs/none, code-freeze-approved

#3747 Fix canal dualstack
  addons/cni-canal/Kustomization
  addons/cni-canal/canal.yaml
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none, code-freeze-approved

#3752 [release/v1.10] Bump helm.sh/helm/v3 from 3.17.3 to 3.18.4
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  go.mod
  go.sum
  test/e2e/helpers.go
  test/e2e/scenario_conformance.go
  test/e2e/scenario_install.go
  test/e2e/scenario_migrate_csi_ccm.go
  test/e2e/scenario_upgrade.go
  test/e2e/tests_test.go
  test/testexec/exec_test.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes, kind/regression, docs/none, cherry-pick-approved

#3761 Fix CSI snapshot webhook name for Nutanix
  pkg/addons/applier.go
  pkg/templates/resources/resources.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3767 Changelog for v1.11.1
  CHANGELOG/CHANGELOG-1.11.md
Labels: release-note-none, size/S, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none

#3770 Restart kubelets sequentially
  pkg/tasks/certs.go
  pkg/tasks/tasks.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none
