Repository kubermatic/kubeone, pull requests merged in 2025-01, with the labels that each got.

#3523 Update codegen with copyright YEAR
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/v1beta2/zz_generated.defaults.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/zz_generated.deepcopy.go
  pkg/apis/kubeone/v1beta3/zz_generated.defaults.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
Labels: release-note-none, size/S, lgtm, approved, kind/failing-test, dco-signoff: yes, docs/none

#3522 feat: add flag to skip TLS verification
  addons/backups-restic/backups-restic.yaml
Labels: kind/feature, size/XS, lgtm, release-note, approved, needs-ok-to-test, dco-signoff: yes, docs/provided

#3524 Fix APT/RPM PGP key expiration issue for old kubernetes versiosn
  pkg/scripts/os_amzn.go
  pkg/scripts/os_centos.go
  pkg/scripts/os_debian.go
  pkg/scripts/testdata/TestKubeadmAmazonLinux-force.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-overwrite_registry.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-proxy.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-v1.26.0.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_cilium.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmAmazonLinux-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmCentOS-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmCentOS-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestKubeadmDebian-cilium_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-nutanix_cluster.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd.golden
  pkg/scripts/testdata/TestKubeadmDebian-with_containerd_with_insecure_registry.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNICentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeadmAndCNIDebian.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlAmazonLinux.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlCentOS.golden
  pkg/scripts/testdata/TestUpgradeKubeletAndKubectlDebian.golden
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3528 Always update MachineDeployment to the indicated kubernetes version
  pkg/tasks/machine_deployments.go
  pkg/tasks/tasks.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3369 Validate MachineController/OperatingSystemManager and cloudProvider None are mutually exclusive
  pkg/apis/kubeone/validation/validation.go
  pkg/apis/kubeone/validation/validation_test.go
Labels: lgtm, size/M, approved, release-note-action-required, kind/api-change, dco-signoff: yes, docs/none

#3534 Fix cloud config defaulting before terraform config apply
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta3/defaults.go
Labels: kind/bug, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#3537 Make sure no slash at the end of vcenterPrefix
  pkg/credentials/secret.go
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3535 Replace `kubeProxyReplacement` in `CiliumSpec` with a boolean
  addons/cni-cilium/cilium-config-map.yaml
  docs/api_reference/v1beta2.en.md
  docs/api_reference/v1beta3.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/conversion.go
  pkg/apis/kubeone/v1beta3/defaults.go
  pkg/apis/kubeone/v1beta3/types.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/apis/kubeone/validation/validation.go
Labels: lgtm, release-note, size/L, approved, kind/api-change, dco-signoff: yes, docs/none

#3529 Fix kubevirt csi addon template
  addons/csi-kubevirt/1-kubevirt-csi-driver.yaml
  addons/csi-kubevirt/2-kubevirt-csi-controller.yaml
Labels: kind/bug, release-note-none, size/S, lgtm, approved, dco-signoff: yes, docs/none

#3545 Fix toleration in csi-kubevirt addon
  addons/csi-kubevirt/2-kubevirt-csi-controller.yaml
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, docs/none

#3546 update Machine controller image
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3544 Labeling the Controle plane nodes before start applying addons and Helm releases
  pkg/tasks/tasks.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3547 [release/v1.9] Cherry-pick the required fixes for the `release/v1.9` branch
  addons/backups-restic/backups-restic.yaml
  addons/csi-kubevirt/1-kubevirt-csi-driver.yaml
  addons/csi-kubevirt/2-kubevirt-csi-controller.yaml
  go.mod
  go.sum
  pkg/apis/kubeone/config/config.go
  pkg/apis/kubeone/v1beta2/defaults.go
  pkg/apis/kubeone/v1beta3/defaults.go
  pkg/credentials/secret.go
  pkg/tasks/tasks.go
  pkg/templates/images/images.go
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3548 Include the infra namespace as a pod namespace env var for machine controller webhook
  addons/machinecontroller/webhook.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none
