Repository kubermatic/kubeone, pull requests merged in 2025-09, with the labels that each got.

#3814 Add bastion SSH private key file setting in host config
  docs/api_reference/v1beta2.en.md
  docs/api_reference/v1beta3.en.md
  examples/terraform/aws/README.md
  examples/terraform/aws/output.tf
  examples/terraform/aws/variables.tf
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/types.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/ssh/connection.go
  pkg/ssh/connector.go
  pkg/terraform/v1beta2/config.go
  pkg/terraform/v1beta3/config.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/provided

#3815 Add certificateValidityPeriod and caCertificateValidityPeriod API
  docs/api_reference/v1beta2.en.md
  docs/api_reference/v1beta3.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta2/zz_generated.deepcopy.go
  pkg/apis/kubeone/v1beta3/types.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/zz_generated.deepcopy.go
  pkg/apis/kubeone/zz_generated.deepcopy.go
  pkg/templates/kubeadm/v1beta4/kubeadm.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/provided

#3818 [release/v1.11] Bump MC to v1.62.1 and OSM to v1.7.6
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3819 [release/v1.10] Bump MC to v1.61.4 and OSM to v1.6.9
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3817 Bump MC to v1.63.1 and OSM to v1.7.6
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#3816 Replace lint job from prow to github actions
  .github/workflows/golangci-lint.yml
  .prow/verify.yaml
Labels: release-note-none, lgtm, size/M, approved, kind/cleanup, dco-signoff: yes, docs/none

#3808 Upgrade nutanix CSI driver to 3.3.4
  addons/csi-nutanix/Kustomization
  addons/csi-nutanix/generate-values-csi-storage
  addons/csi-nutanix/nutanix-csi-storage.yaml
  addons/csi-nutanix/secrets.yaml
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes, kind/chore, docs/none

#3805 Drop centos from azure terraform example
  examples/terraform/azure/README.md
  examples/terraform/azure/variables.tf
Labels: size/S, lgtm, release-note, approved, kind/cleanup, dco-signoff: yes, docs/none
