Repository kubermatic/kubeone, pull requests merged in 2025-06, with the labels that each got.

#3672 Update machine-controller to v1.61.3
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#3680 Remove machine-controller update from v1.10.1 changelog
  CHANGELOG/CHANGELOG-1.10.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none

#3673 [release/v1.10] Update machine-controller to v1.61.3
  pkg/templates/images/images.go
Labels: size/XS, lgtm, release-note, approved, dco-signoff: yes, kind/chore, cherry-pick-approved

#3682 Bump Go version to 1.24.4
  .prow/generated.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  test/e2e/helpers.go
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes, kind/chore, docs/none

#3683 Images updates
  addons/backups-restic/backups-restic.yaml
  addons/ccm-hetzner/Kustomization
  addons/ccm-hetzner/README.md
  addons/ccm-hetzner/ccm-hetzner.yaml
  addons/ccm-openstack/Kustomization
  addons/ccm-openstack/README.md
  addons/ccm-openstack/ccm-openstack.yaml
  addons/ccm-vsphere/ccm-vsphere.yaml
  addons/cni-canal/Kustomization
  addons/cni-canal/canal.yaml
  addons/csi-aws-ebs/aws-csi.yaml
  addons/csi-azuredisk/Kustomization
  addons/csi-azuredisk/csi-azuredisk.yaml
  addons/csi-azurefile/Kustomization
  addons/csi-azurefile/csi-azurefile.yaml
  addons/csi-gcp-compute-persistent/Kustomization
  addons/csi-gcp-compute-persistent/csi-gcp-compute-persistent.yaml
  addons/csi-hetzner/Kustomization
  addons/csi-hetzner/README.md
  addons/csi-hetzner/hcloud-csi.yml
  addons/csi-openstack-cinder/Kustomization
  addons/csi-openstack-cinder/README.md
  addons/csi-openstack-cinder/openstack-csi-cinder.yaml
  addons/csi-vsphere-ks/validatingwebhook.yaml
  addons/csi-vsphere-ks/vsphere-csi-driver.yaml
  addons/csi-vsphere/1-vsphere-csi-driver.yaml
  addons/csi-vsphere/2-validatingwebhook.yaml
  addons/csi-vsphere/Kustomization
  addons/csi-vsphere/README.md
  addons/csi-vsphere/configmap.yaml
  addons/csi-vsphere/secret.yaml
  addons/machinecontroller/deployment-controller.yaml
  addons/machinecontroller/webhook.yaml
  addons/operating-system-manager/deployment-controller.yaml
  pkg/addons/manifest.go
  pkg/addons/manifest_test.go
  pkg/templates/images/images.go
  pkg/templates/resources/resources.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3723 Update e2e upgrade tests to use release/v1.10 as a stable ref
  .prow/generated.yaml
  test/e2e/scenario_upgrade.go
Labels: kind/bug, release-note-none, lgtm, size/L, approved, dco-signoff: yes, docs/none, code-freeze-approved
