Repository kubermatic/kubeone, pull requests merged in 2025-03, with the labels that each got.

#3573 fix: fix the wrong error return value
  pkg/tasks/probes.go
Labels: kind/bug, size/XS, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes, docs/none

#3579 Update golang.org/x/net v0.37.0
  go.mod
  go.sum
Labels: release-note-none, lgtm, size/M, approved, dco-signoff: yes, kind/chore, docs/none

#3584 Repair cluster if etcd member count has exceeded control plane VM count
  pkg/clusterstatus/etcdstatus/etcdstatus.go
  pkg/cmd/apply.go
  pkg/tasks/tasks.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3568 Kubernetes 1.32 images
  .prow/generated.yaml
  addons/backups-restic/backups-restic.yaml
  addons/calico-vxlan/Kustomization
  addons/calico-vxlan/README.md
  addons/calico-vxlan/calico-config.yaml
  addons/calico-vxlan/calico-vxlan.yaml
  addons/ccm-azure/Kustomization
  addons/ccm-digitalocean/Kustomization
  addons/ccm-nutanix/Kustomization
  addons/ccm-nutanix/nutanix-ccm.yaml
  addons/cni-canal/Kustomization
  addons/cni-canal/canal.yaml
  addons/cni-cilium/Kustomization
  addons/cni-cilium/README.md
  addons/cni-cilium/cilium.yaml
  addons/cni-cilium/helm-values
  addons/cni-cilium/hubble.yaml
  addons/csi-aws-ebs/aws-csi.yaml
  addons/csi-aws-ebs/generated-values-csi
  addons/csi-azuredisk/Kustomization
  addons/csi-azuredisk/csi-azuredisk.yaml
  addons/csi-azurefile/Kustomization
  addons/csi-azurefile/README.md
  addons/csi-azurefile/csi-azurefile.yaml
  addons/csi-azurefile/helm-values
  addons/csi-digitalocean/Kustomization
  addons/csi-digitalocean/driver.yaml
  addons/csi-external-snapshotter/Kustomization
  addons/csi-external-snapshotter/README.md
  addons/csi-external-snapshotter/controller-rbac.yaml
  addons/csi-external-snapshotter/controller.yaml
  addons/csi-external-snapshotter/snapshotter.yaml
  addons/csi-external-snapshotter/webhook-rbac.yaml
  addons/csi-external-snapshotter/webhook.yaml
  addons/csi-hetzner/README.md
  addons/csi-hetzner/hcloud-csi.yml
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
  test/e2e/helpers.go
Labels: lgtm, approved, size/XXL, release-note-action-required, dco-signoff: yes, kind/chore, docs/none

#3587 Upgrade helm client
  go.mod
  go.sum
Labels: lgtm, release-note, size/L, approved, dco-signoff: yes, kind/chore, docs/none

#3590 Add kubernetes v1.32 and kernel v4.19+ safeguard
  .prow/generated.yaml
  go.mod
  pkg/state/cluster.go
  pkg/tasks/probes.go
  test/e2e/tests_test.go
  test/tests.yml
Labels: kind/feature, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none
