Repository kubermatic/kubeone, pull requests merged in 2025-08, with the labels that each got.

#3775 Cleanup /etc/kubernetes/tmp after upgrades
  pkg/tasks/nodes.go
  pkg/tasks/tasks.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3779 Make machine-controller -join-cluster-timeout configurable
  addons/machinecontroller/deployment-controller.yaml
Labels: kind/feature, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/tbd

#3780 refreshed cluster-autoscaler addon
  addons/cluster-autoscaler/Kustomization
  addons/cluster-autoscaler/README.md
  addons/cluster-autoscaler/cluster-autoscaler-values.yaml
  addons/cluster-autoscaler/cluster-autoscaler.yaml
  addons/cluster-autoscaler/poddisruptionbudget.yaml
Labels: lgtm, release-note, size/XL, approved, dco-signoff: yes, kind/chore, docs/none

#3782 Add --all flag to config images list command (#3759)
  pkg/cmd/config-images.go
  pkg/templates/images/images.go
Labels: kind/feature, lgtm, release-note, size/M, approved, needs-ok-to-test, dco-signoff: yes, docs/none

#3776 Fix Nutanix credentials
  addons/ccm-nutanix/nutanix-config.yaml
  addons/csi-nutanix/Kustomization
  addons/csi-nutanix/generate-values-csi-storage
  addons/csi-nutanix/nutanix-csi-storage.yaml
  pkg/credentials/credentials.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3507 feat(reset): add cleanup volumes and cleanup-load-balancers flag
  pkg/clientutil/service.go
  pkg/clientutil/volumes.go
  pkg/clientutil/webhook.go
  pkg/cmd/reset.go
  pkg/state/context.go
  pkg/tasks/reset.go
  pkg/tasks/tasks.go
Labels: kind/feature, lgtm, release-note, size/L, approved, dco-signoff: yes, docs/none

#3793 add option to enable non root device usage in worker nodes by osm
  addons/operating-system-manager/deployment-controller.yaml
  docs/api_reference/v1beta2.en.md
  docs/api_reference/v1beta3.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/types.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/templates/images/images.go
Labels: kind/feature, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3797 Default canal_iface_regex only for hetzner
  addons/cni-canal/canal-config.yaml
  pkg/addons/manifest.go
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3795 fix: add hubble-server-certs to cilium DaemonSet
  addons/cni-cilium/Kustomization
  addons/cni-cilium/cilium.yaml
Labels: kind/bug, lgtm, release-note, size/M, approved, ok-to-test, dco-signoff: yes, docs/provided
