Repository kubermatic/kubeone, pull requests merged in 2025-04, with the labels that each got.

#3616 Migrate external selector matchLabels selector
  pkg/addons/ensure.go
  pkg/addons/helpers.go
Labels: kind/bug, release-note-none, size/S, lgtm, approved, dco-signoff: yes, docs/none

#3622 Downgrade csi-external-snapshotter to v8.1.0
  addons/csi-external-snapshotter/controller-rbac.yaml
  addons/csi-external-snapshotter/controller.yaml
  addons/csi-external-snapshotter/crds.yaml
  addons/csi-external-snapshotter/webhook-rbac.yaml
  addons/csi-external-snapshotter/webhook.yaml
  addons/csi-external-snapshotter_v8.2.1/Kustomization
  addons/csi-external-snapshotter_v8.2.1/README.md
  addons/csi-external-snapshotter_v8.2.1/snapshotter.yaml
  pkg/addons/ensure.go
  pkg/addons/helpers.go
  pkg/templates/images/images.go
  pkg/templates/images/resource_string.go
Labels: kind/bug, lgtm, release-note, approved, size/XXL, dco-signoff: yes, docs/none

#3630 Update machine-controller v1.61.1 and OSM v1.6.4
  go.mod
  go.sum
  pkg/templates/images/images.go
Labels: size/S, lgtm, release-note, approved, dco-signoff: yes, kind/chore, docs/none

#3632 CNI Version on Flatcar now depends on the kubernetes version
  pkg/scripts/os_flatcar.go
  pkg/scripts/testdata/TestFlatcarScript-install_all.golden
  pkg/scripts/testdata/TestFlatcarScript-install_all_with_force.golden
  pkg/scripts/testdata/TestFlatcarScript-install_all_with_proxy.golden
  pkg/scripts/testdata/TestFlatcarScript-upgrade_kubeadm_and_kubectl.golden
  pkg/scripts/testdata/TestFlatcarScript-upgrade_kubeadm_and_kubectl_with_force.golden
  pkg/scripts/testdata/TestFlatcarScript-upgrade_kubelet.golden
Labels: kind/bug, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3634 Fix digitalocean terraform dpkg lock file issue
  addons/ccm-digitalocean/Kustomization
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/main.tf
  pkg/templates/images/images.go
Labels: kind/bug, size/S, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3636 Fix flatcar 1.31.x CNI plugins directory permissions
  pkg/scripts/os_flatcar.go
  pkg/scripts/testdata/TestFlatcarScript-install_all.golden
  pkg/scripts/testdata/TestFlatcarScript-install_all_with_force.golden
  pkg/scripts/testdata/TestFlatcarScript-install_all_with_proxy.golden
  pkg/scripts/testdata/TestFlatcarScript-upgrade_kubeadm_and_kubectl.golden
  pkg/scripts/testdata/TestFlatcarScript-upgrade_kubeadm_and_kubectl_with_force.golden
  pkg/scripts/testdata/TestFlatcarScript-upgrade_kubelet.golden
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3638 Add changelog for v1.10.0
  CHANGELOG/CHANGELOG-1.10.md
  CHANGELOG/README.md
Labels: release-note-none, lgtm, size/M, approved, kind/documentation, dco-signoff: yes, docs/none

#3639 Update docs links to v1.10
  README.md
  addons/README.md
  addons/cluster-autoscaler/README.md
  addons/cni-cilium/README.md
  docs/README.md
  docs/proposals/20200224-apply.md
  docs/release_process.md
  examples/terraform/aws-dualstack/README.md
  examples/terraform/aws-dualstack/README.md.in
  examples/terraform/aws/README.md
  examples/terraform/aws/README.md.in
  examples/terraform/azure/README.md
  examples/terraform/azure/README.md.in
  examples/terraform/digitalocean/README.md
  examples/terraform/digitalocean/README.md.in
  examples/terraform/equinixmetal/README.md
  examples/terraform/equinixmetal/README.md.in
  examples/terraform/gce/README.md
  examples/terraform/gce/README.md.in
  examples/terraform/hetzner/README.md
  examples/terraform/hetzner/README.md.in
  examples/terraform/nutanix/README.md
  examples/terraform/nutanix/README.md.in
  examples/terraform/openstack/README.md
  examples/terraform/openstack/README.md.in
  examples/terraform/vmware-cloud-director/README.md
  examples/terraform/vmware-cloud-director/README.md.in
  examples/terraform/vsphere/README.md
  examples/terraform/vsphere/README.md.in
  examples/terraform/vsphere_centos/README.md
  examples/terraform/vsphere_centos/README.md.in
  examples/terraform/vsphere_flatcar/README.md
  examples/terraform/vsphere_flatcar/README.md.in
  pkg/cmd/example-manifest.tmpl.yaml
  pkg/cmd/migrate.go
  pkg/tasks/machine_deployments.go
  pkg/tasks/probes.go
  pkg/tasks/tasks.go
Labels: release-note-none, lgtm, size/L, approved, kind/documentation, dco-signoff: yes, docs/none

#3640 Add a note to changelog for Helm OCI support
  CHANGELOG/CHANGELOG-1.10.md
Labels: size/XS, release-note-none, lgtm, approved, kind/documentation, dco-signoff: yes, docs/none

#3642 Fix CABundle flag for OSM
  addons/operating-system-manager/deployment-controller.yaml
Labels: kind/bug, size/XS, lgtm, release-note, approved, dco-signoff: yes, docs/none

#3631 Introduce mirror-images command
  go.mod
  go.sum
  pkg/apis/kubeone/validation/validation.go
  pkg/cmd/config-images.go
  pkg/cmd/mirror-images.go
  pkg/cmd/root.go
  pkg/cmd/shared.go
  pkg/semverutil/helper.go
Labels: kind/feature, lgtm, release-note, size/XL, approved, dco-signoff: yes, docs/provided

#3646 feat: override containerd sandbox image
  docs/api_reference/v1beta2.en.md
  docs/api_reference/v1beta3.en.md
  pkg/apis/kubeone/types.go
  pkg/apis/kubeone/v1beta2/conversion.go
  pkg/apis/kubeone/v1beta2/types.go
  pkg/apis/kubeone/v1beta2/zz_generated.conversion.go
  pkg/apis/kubeone/v1beta3/types.go
  pkg/apis/kubeone/v1beta3/zz_generated.conversion.go
  pkg/containerruntime/containerd_config.go
Labels: kind/feature, lgtm, release-note, size/M, approved, dco-signoff: yes, docs/none

#3618 Update to Go 1.24.2, golangci-lint 2.x
  .golangci.yml
  .prow/generated.yaml
  .prow/postsubmits.yaml
  .prow/verify.yaml
  Dockerfile
  pkg/apis/kubeone/validation/validation.go
  pkg/clusterstatus/clusterstatus.go
  pkg/clusterstatus/preflightstatus/preflightstatus.go
  pkg/cmd/migrate.go
  pkg/credentials/credentials.go
  pkg/dashboard/server.go
  pkg/tasks/preflight_checks.go
  pkg/tasks/probes.go
  pkg/tasks/util.go
  pkg/templates/kubeadm/v1beta3/kubeadm.go
  pkg/templates/kubeadm/v1beta4/kubeadm.go
  pkg/terraform/v1beta2/config.go
  pkg/terraform/v1beta3/config.go
  test/e2e/cloudprovider.go
  test/e2e/helpers.go
  test/e2e/scenario_migrate_csi_ccm.go
Labels: lgtm, release-note, approved, size/XXL, dco-signoff: yes, kind/chore, docs/none

#3648 Make kubeone go installa-ble again
  go.mod
Labels: size/XS, lgtm, release-note, approved, kind/cleanup, dco-signoff: yes, docs/none
